### PR TITLE
fix(loki sink): On `404` query top level for healthcheck

### LINKED ISSUE #6463: loki sink healthchecks fail for Grafana Cloud hosted Loki
Reported by user in discord: https://discord.com/channels/742820443487993987/746070604192415834/811356602220150844

It looks like Grafana Cloud doesn't expose the `/health` endpoint that`vector` expects:

```
ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=A non-successful status returned: 404 Not Found component_kind="sink" component_type="loki" component_name="loki"
```

For example, see:

```
$ curl -I https://logs-prod-us-central1.grafana.net/ready
HTTP/2 404 
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Tue, 16 Feb 2021 22:46:18 GMT
content-length: 19
via: 1.1 google
alt-svc: clear
```

It does return OK for top-level queries though:

```
$ curl -I https://logs-prod-us-central1.grafana.net/     
HTTP/2 200 
date: Tue, 16 Feb 2021 22:46:43 GMT
content-length: 2
content-type: text/plain; charset=utf-8
via: 1.1 google
alt-svc: clear
```

### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)

```

Ref: Loki API https://grafana.com/docs/loki/latest/api/#get-ready

### PR DESCRIPTION
**Pull request by ktff**
Closes #6463

Going through https://github.com/grafana/loki, loki returns one of:
* 500 Internal Server Error https://github.com/grafana/loki/blob/cd79adc8ab0c80c55a0f39b43322839c6ffb05d8/clients/pkg/promtail/server/server.go#L222
* 503 Service Unavailable https://github.com/grafana/loki/blob/cd79adc8ab0c80c55a0f39b43322839c6ffb05d8/pkg/loki/loki.go#L349
* 200 OK

So it should be ok to assume that on 404 we are dealing with Grafana Cloud, so instead we just check if its top level query is reacheable/OK.

We could also check if the provided endpoint ends with `grafana.net`, but that seems a bit fragile.

### TODO

- [x] Is there some better suited endpoint? Some loki specific? EDIT: Not really, non of the endpoints that should always be exposed are.

### CODE REVIEW

File: src/sinks/loki.rs [hunk 1]
```diff
@@ -289,11 +289,35 @@ async fn healthcheck(config: LokiConfig, client: HttpClient) -> crate::Result<()
...
+}
+
+async fn fetch_status(
+    endpoint: &str,
+    config: &LokiConfig,
+    client: &HttpClient,
+) -> crate::Result<http::StatusCode> {
+    let uri = format!("{}{}", config.endpoint.uri, endpoint);
+
+    let mut req = http::Request::get(uri).body(hyper::Body::empty()).unwrap();
```
Comment (jszwedko) [inline src/sinks/loki.rs:314]:
```suggestion
    let mut req = http::Request::get(uri).body(hyper::Body::empty()).expect("building request never fails");
```

Nit since `unwraps()` always stick out to me.

**Review by jszwedko — APPROVED** [review]
Makes sense, thanks @ktff !

File: src/sinks/loki.rs [hunk 2]
```diff
@@ -289,11 +289,35 @@ async fn healthcheck(config: LokiConfig, client: HttpClient) -> crate::Result<()
 
     let res = client.send(req).await?;
 
-    if res.status() != http::StatusCode::OK {
-        return Err(format!("A non-successful status returned: {}", res.status()).into());
+    let status = match fetch_status("ready", &config, &client).await? {
+        // Issue https://github.com/timberio/vector/issues/6463
+        http::StatusCode::NOT_FOUND => {
+            warn!("Endpoint `/ready` not found. Retrying healthcheck with top level query.");
```
Comment (jszwedko) [inline src/sinks/loki.rs:295]: Given this will be the common case when using Grafana Cloud, I think I might argue to reduce this to `debug!` to avoid spamming the logs.
