### PR TITLE
fix(config): Preload log scheme

### LINKED ISSUE #6394: docker_logs not using the host key defined in the configuration
### Vector Version

0.11.1

### Vector Configuration File

```toml
[log_schema]
  host_key = "host.hostname"
  timestamp_key = "@timestamp"

[sources.docker]
  type = "docker_logs"

[sinks.console]
  type = "console"
  inputs = ["docker"]
  encoding = "json"
```

### Debug Output

```json
{
  "@timestamp": "2021-02-08T16:38:35.639689800Z",
  "container_created_at": "2021-02-08T16:38:35.206171600Z",
  "container_id": "3f108cb61775cb261491e8ba47d49b9c9dcd455448bfa624250ad61ae1e80f66",
  "container_name": "goofy_mayer",
  "host": "HQSML-1719880",
  "image": "timberio/vector:nightly-debian",
  "message": "Feb 08 16:38:35.639  INFO vector::app: Log level is enabled. level=\"vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info\"",
  "source_type": "docker",
  "stream": "stdout"
}
```

### Expected Behavior

The hostname should be inserted as `host.hostname`.

### Actual Behavior

The hostname is inserted with the global default key `host`, not the override key name in the configuration.

### PR DESCRIPTION
**Pull request by ktff**
Closes  #6394

Resolves the race between loading log schema from the config file and using said schema for building the same config by first loading config and setting log schema and then loading config as usual. 

Replaces #6552

### Todo

- [ ] Check impact on start time 
- [ ] Add note to global options documentation how they can't be changed when reloading
- [x] Add whole program test

### CODE REVIEW

File: src/app.rs [hunk 1]
```diff
@@ -233,7 +231,7 @@ impl Application {
                         // Reload paths
                         config_paths = config::process_paths(&opts.config_paths_with_formats()).unwrap_or(config_paths);
                         // Reload config
-                        let new_config = config::load_from_paths(&config_paths, false).map_err(handle_config_errors).ok();
+                        let new_config = config::load_from_paths(&config_paths).map_err(handle_config_errors).ok();
```
Comment (jszwedko) [inline src/app.rs:234]: Don't we need to do the same preinit here in-case the globals changed? Is it possible to move the global log schema initialization into `config::load_from_paths`? I think that would avoid neglecting to call it together each time.

**Review by jszwedko — COMMENTED** [review]
Thanks @ktff !

I'm curious why you ended up needing to refactor the warning logic as part of this. Would you be able to describe? I think that would help me understand the changes better.

There are some failing checks and tests which you've probably already noticed 😄

**Comment by ktff** [comment]
> refactor the warning logic as part of this.

`deny_warnings` was an issue since neither true nor false was an option. For `true` warnings would become hard error so loading could fail on initialization when it would pass normally. For `false` we would print all warnings twice, once for initialization and once for regular load. So I opted for an alternative.

File: src/app.rs (hunk 1 above)
Comment (ktff) [reply src/app.rs:234]: > Don't we need to do the same preinit here in-case the globals changed?

Nope. We can only set global schema once, that's also the reason those two steps/functions are separated.

Comment (jszwedko) [reply src/app.rs:234]: I'm not sure I completely understand. If I had a config file like:

```toml
host_key = "foo"

// source, sinks, etc.
```

and then I modified it to:

```toml
host_key = "bar"

// source, sinks, etc.
```

Wouldn't we need to redo just the global config again before reinitializing the components so that they pick up the new default?

**Comment by jszwedko** [comment]
Could we add a test for this behavior too? It'd be nice to ensure it doesn't regress accidentally.

**Comment by drunkirishcoder** [comment]
noticed you didn't include the `docker_logs` source. 😄

File: src/app.rs (hunk 1 above)
Comment (ktff) [reply src/app.rs:234]: > Wouldn't we need to redo just the global config again before reinitializing the components so that they pick up the new default?

It's more complicated:
* we would need to change global `LOG_SCHEMA` variable to be changeable
* we would need to shutdown and rebuild even unchanged components. This is because when changing to a new configuration we compute the difference between topologies, retain the common part, shutdown removed, add new, and recreate changed components.

For similar reason `data_dir` can't be changed and we fail reloading if it's different from initial value, which we should also do for log schema which I've checked now and it seams we aren't checking for that so I'll add it.

Comment (ktff) [reply src/app.rs:234]: More generally any global option related to components can't be changed.

Comment (jszwedko) [reply src/app.rs:234]: Ah, interesting, that is a limitation I was now aware of. It seems like we could permit things like `data_dir` to be changed with the caveat that, if users change this, vector will forget whatever its previous state was.

In my opinion, we should let users change and reload global config values as well for consistency. But if we don't want to do that for now, I think it'd be good to explicitly fail the reload if global values were changed. Are we doing that?

Comment (ktff) [reply src/app.rs:234]: > In my opinion, we should let users change and reload global config values as well

It's doable by just rebuilding everything, and I agree it would be nice to cover that case so could you open an issue for that.

>  It seems like we could permit things like data_dir to be changed with the caveat that, if users change this, vector will forget whatever its previous state was.

We are flushing everything that is being removed by default so that won't be an issue.

> , I think it'd be good to explicitly fail the reload if global values were changed. Are we doing that?

I agree, and no we aren't so I'll add a check for that.

**Comment by ktff** [comment]
> noticed you didn't include the docker_logs source.

@drunkirishcoder well your fix is perfectly good.

**Comment by drunkirishcoder** [comment]
@ktff you are right, sorry total brain fart. forgot the other changes to "revert" are in the PR that we will close. I guess the only little thing can be changed is rename the fn from `default_host_key()` to `host_key()` as you have for the sinks.

File: src/app.rs (hunk 1 above)
Comment (jszwedko) [reply src/app.rs:234]: 👍 thanks for the discussion!

I opened https://github.com/timberio/vector/issues/6598 to track enhancing the reload to allow for changing global options.

Thanks for adding a check to explicitly fail. I think this will be better behavior than silently ignoring changes to these values.

File: src/topology/mod.rs [hunk 2]
```diff
@@ -207,8 +207,11 @@ impl RunningTopology {
     /// On Error, topology is in invalid state.
     /// May change componenets even if reload fails.
     pub async fn reload_config_and_respawn(&mut self, new_config: Config) -> Result<bool, ()> {
-        if self.config.global.data_dir != new_config.global.data_dir {
-            error!(message = "The data_dir cannot be changed while reloading config file; reload aborted.", data_dir = ?self.config.global.data_dir);
+        if self.config.global != new_config.global {
+            error!(
+                message =
+                    "Global options can't be changed while reloading config file; reload aborted."
```
Comment (jszwedko) [inline src/topology/mod.rs:213]:
```suggestion
                    "Global options can't be changed while reloading config file; reload aborted. Please restart vector to reload the configuration file."
```

File: src/config/log_schema.rs [hunk 3]
```diff
@@ -11,6 +14,27 @@ lazy_static::lazy_static! {
         source_type_key: String::from("source_type"),
     };
 }
+
+/// Loads Log Schema from configurations and sets global schema.
+/// Once this is done, configurations can be correctly loaded using
+/// seted log schema.
```
Comment (jszwedko) [inline src/config/log_schema.rs:20]:
```suggestion
/// configured log schema defaults.
```

File: src/config/log_schema.rs [hunk 4]
```diff
@@ -11,6 +14,27 @@ lazy_static::lazy_static! {
...
+/// If deny seted, will panic if schema has already been seted.
```
Comment (jszwedko) [inline src/config/log_schema.rs:21]:
```suggestion
/// If deny is set, will panic if schema has already been set.
```

File: src/config/log_schema.rs [hunk 5]
```diff
@@ -11,6 +14,27 @@ lazy_static::lazy_static! {
...
+pub fn init_log_schema(
+    config_paths: &[(PathBuf, FormatHint)],
+    deny_seted: bool,
```
Comment (jszwedko) [inline src/config/log_schema.rs:24]:
```suggestion
    deny_if_set: bool,
```

**Review by jszwedko — APPROVED** [review]
Thanks @ktff ! I appreciate you tackling this problem in a way that should handle it for all cases and make it hard to mess it up in the future.

Hopefully we can simplify this back down after https://github.com/timberio/vector/issues/6598 to avoid needing to separate out the warnings and check if globals have already been set.
