### PR TITLE
fix(kubernetes_logs source): Handle OK response from api_watcher with embedded desync elegantly

### LINKED ISSUE #5846: kubernetes_logs source doesn't detect new pods
There was an existing Nginx deployment **before** I deployed the vector-agent helm chart. Everything was working fine until I've decided to do a rolling restart of the Nginx deployment, what caused the pod to be scheduled to a different node (due to pod anti-affinity rules).
However after several hours I've noticed that sink (S3 bucket) doesn't receive any logs from the new Nginx pod, when I checked vector-agent logs from the corresponding Node, I didn't see any log messages that is started watching Nginx logs.

### Vector Version

```
timberio/vector:0.11.1-debian
```
**Kubernetes environment:** `1.17 (AWS EKS)`

### Vector Configuration File

```yaml
# Schema part of the generated `vector` config.
logSchema:
  hostKey: "host"
  messageKey: "message"
  sourceTypeKey: "source_type"
  timestampKey: "timestamp"

kubernetesLogsSource:
  enabled: true
  sourceId: kubernetes_logs
  rawConfig: |
    extra_field_selector = "metadata.namespace=ingress-nginx"

internalMetricsSource:
  enabled: true
  sourceId: internal_metrics
  rawConfig: null

# The "built-in" host metrics source emitting the metrics gathered from the node
# that Vector is executing on.
hostMetricsSource:
  # Disable to omit the host metrics source from being added.
  enabled: true
  # The name to use for the "built-in" host metrics source.
  sourceId: host_metrics
  # Raw TOML config to embed at the host metrics source.
  rawConfig: null

# The "built-in" prometheus sink exposing metrics in the Prometheus scraping
# format.
# When using this "built-in" sink, we automatically configure container ports,
# and ensure things are ready for discovery and scraping via Prometheus'
# `kubernetes_sd_configs` jobs.
prometheusSink:
  # Disable to omit the prometheus sink from being added.
  enabled: true
  # The name to use for the "built-in" prometheus sink.
  sinkId: prometheus_sink
  # Inputs of the built-in prometheus sink.
  # If you have built-in internal metrics source enabled, we'll add it as a
  # input here under the hood, so you don't have to pass it here.
  # Unless `excludeInternalMetrics` is set to `true`, in which case you're
  # responsible of wiring up the internal metrics.
  inputs: []
  # Set this to `true` to opt-out from automatically adding the built-in
  # internal metrics source to the inputs.
  excludeInternalMetrics: false
  # The address to listen at.
  listenAddress: "0.0.0.0"
  # The port to listen at.
  listenPort: "9090"
  # Raw TOML config to embed at the vector source.
  rawConfig: null
  # Add Prometheus annotations to Pod to opt-in for Prometheus scraping.
  # To be used in clusters that rely on Pod annotations in the form of
  # `prometheus.io/scrape` to discover scrape targets.
  addPodAnnotations: false
  # Use prometheus-operator `PodMonitor` to opt-in for Prometheus scraping.
  # To be used in clusters that rely on prometheus-operator to gether metrics.
  # You might want to set `podMonitorSelectorNilUsesHelmValues=false` if you're
  # using prometheus-operator Helm chart to allow `PodMonitor` resources
  # dicovery in all namespaces.
  podMonitor:
    # Whether to add the `PodMonitor` resource or not.
    # `prometheus-operator` CRDs are necessary, otherwise you'll get an error.
    enabled: false
    # Additional relabelings to include in the `PodMonitor`.
    extraRelabelings: []


transforms:
  app_logs:
    type: "swimlanes"
    inputs: ["kubernetes_logs"]
    rawConfig: |
      lanes.nginx."kubernetes.container_name.eq" = "nginx-ingress-controller"

# Sinks to add to the generated `vector` config.
sinks:
  nginx_s3:
    type: "aws_s3"
    inputs: ["app_logs.nginx"]
    rawConfig: |
      bucket = "..."
      region = "us-west-2"
      encoding.codec = "text"
      key_prefix = "date=%F/"

```

### Expected Behavior

Kubernetes source must pick up newly created pod and forward logs.

### Actual Behavior

Vector agent deployed on the node with the new pod, didn't detect it and no logs have been forwarded to the sink.

### Example Data

Logs from the vector agent deployed to the node where a new Nginx pod has been added by the deployment. Notice that there are no logs after Dec 30.

```
Dec 30 14:43:15.278  INFO vector::app: Log level is enabled. level="vector=info,codec=info,file_source=info,tower_limit=trace,rdkafka=info"
Dec 30 14:43:15.278  INFO vector::app: Loading configs. path=[("/etc/vector/managed.toml", None)]
Dec 30 14:43:15.280  INFO vector::sources::kubernetes_logs: Obtained Kubernetes Node name to collect logs for (self). self_node_name="ip-10-43-2-174.us-west-2.compute.internal"
Dec 30 14:43:15.295  INFO vector::topology: Running healthchecks.
Dec 30 14:43:15.295  INFO vector::topology: Starting source. name="kubernetes_logs"
Dec 30 14:43:15.295  INFO vector::topology: Starting transform. name="app_logs.nginx"
Dec 30 14:43:15.295  INFO vector::topology: Starting sink. name="nginx_s3"
Dec 30 14:43:15.295  INFO vector: Vector has started. version="0.11.1" git_version="v0.11.1" released="Thu, 17 Dec 2020 17:09:17 +0000" arch="x86_64"
Dec 30 14:43:15.295  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
Dec 30 14:43:15.296  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: file_source::checkpointer: Loaded checkpoint data.
Dec 30 14:43:15.331  INFO vector::topology::builder: Healthcheck: Passed.
Dec 30 14:44:16.779  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: vector::internal_events::file::source: Resuming to watch file. path="/var/log/pods/ingress-nginx_echoserver-6b856cc8dc-kcpcr_4997bd83-bc8f-46be-9fe0-6a138306e0fc/echoserver/0.log" file_position=558687
```

### LINKED ISSUE #5877: Kubernetes Reflector Silently Drops Errors
Whilst investigating #5846 I realised that watch stream errors are silently dropped as `Reflector::process_stream_item` silently ignores any watch event without a resource version. This would have made it significantly easier to diagnose the incorrect desync detection in #5846 as the logs would have been filled with too old resource version errors

### PR DESCRIPTION
**Pull request by eeyun**
Handles the case where a watcher desync response returns embedded inside a 200 OK.

We've refactored our API here to remove the `k8s_openapi::WatchResponse` type as in our investigation it became clear that the extra abstraction was unnecessary for us. In removing that type we've provider our own internal `Response` type which allows us to simplify the redirection here.

Closes #5877 
Closes #5846
Signed-off-by: Ian Henry <ianjhenry00@gmail.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
Cc @tustvold in case you want to review.

**Comment by binarylogic** [comment]
@eeyun does this close an issue?

**Comment by eeyun** [comment]
Closes #5877 and #5846

**Review by MOZGIII — CHANGES_REQUESTED** [review]
All looks good, but we need more tests cases at API Watcher to cover the rest of the input kinds, as discussed.
- non-desync status error
- invalid json
- unexpected resource kind (i.e. Pod expected but Namespace was sent)

Also, ideally:
- network error at the stream level
- network error at the invocation level

File: src/kubernetes/api_watcher.rs [hunk 1]
```diff
@@ -482,6 +482,74 @@ mod tests {
...
+            // Non-desync Stream Error
+            (
+                Box::new(|when, then| {
+                    when.method(GET).path("/api/v1/pods");
+                    then.status(500);
+                }),
+                vec![Box::new(|item| {
+                    let error = item.unwrap_err();
+                    match error {
+                        watcher::stream::Error::Other { .. } => {}
```
Comment (MOZGIII) [inline src/kubernetes/api_watcher.rs:494]: Would be great if we actually destructure and assert this error more knowingly - i.e. assert that it's an http error under the hood. One of the goals here is to ensure the errors are propagated correctly, and we get exactly the errors we expect to get, rather than "some" error that's not a desync.

File: src/kubernetes/api_watcher.rs [hunk 2]
```diff
@@ -152,3 +164,457 @@ pub mod invocation {
...
+                                    "status": "Failure"
+                                }
+                            }"#,
+                        );
+                }),
+                vec![Box::new(|item| {
+                    // panic! on pass is err is what we expected
+                    let error = item.unwrap_err();
+                    match error {
+                        watcher::stream::Error::Desync { .. } => {}
```
Comment (MOZGIII) [inline src/kubernetes/api_watcher.rs:373]: Can we assert the underlying error here? I feel like it makes a lot of sense to not just assert that this is a desync error, but to ensure the concrete variant of an error.
In addition to a more strict test, it would be kind of useful as a reference for the readers, if they ever want to unpack this error

The same applies to the rest of the assertions.

File: src/kubernetes/api_watcher.rs [hunk 3]
```diff
@@ -152,3 +164,457 @@ pub mod invocation {
...
+                            r#"
+                            "type": "ADDED",
+                            "object":
+                                "kind": "Pod",
+                                "apiVersion": "v1",
+                                "metadata": {
+                                    "uid": "uid0"
+                                }
+                            }
+                         }"#,
```
Comment (MOZGIII) [inline src/kubernetes/api_watcher.rs:535]: Can we make it clearer this is an invalid JSON?
```suggestion
                            r#"not a valid json"#,
```

File: src/kubernetes/api_watcher.rs [hunk 4]
```diff
@@ -152,3 +164,457 @@ pub mod invocation {
...
+                        );
+                }),
+                vec![Box::new(|item| {
+                    let error = item.unwrap_err();
+                    match error {
+                        watcher::stream::Error::Other { .. } => {}
```
Comment (MOZGIII) [inline src/kubernetes/api_watcher.rs:541]: I'm very curious to what's the underlying error is here, so this is double the value compared to https://github.com/timberio/vector/pull/6053/files#r563191159

File: src/kubernetes/api_watcher.rs [hunk 5]
```diff
@@ -152,3 +164,457 @@ pub mod invocation {
...
+                        _ => panic!("Expect an 'other' error"),
+                    }
+                })],
+            ),
```
Comment (MOZGIII) [inline src/kubernetes/api_watcher.rs:572]: I'd expect a watch response, rather than a stream-level error here, interesting that tests are passing. Something might be off. https://github.com/timberio/vector/pull/6053/files#r563191159 should help with resolving this.

File: src/kubernetes/api_watcher.rs [hunk 6]
```diff
@@ -152,3 +164,457 @@ pub mod invocation {
...
+        }
+    }
+
+    /// Test that it can handle stream errors.
+    #[tokio::test]
+    async fn test_stream_errors() {
+        let cases: Vec<(
+            Box<dyn FnOnce(When, Then)>,
+            Vec<Box<dyn FnOnce(Result<WatchResponse<Pod>, watcher::stream::Error<stream::Error>>)>>,
+        )> = vec![
```
Comment (MOZGIII) [inline src/kubernetes/api_watcher.rs:290]: I think we want to be able to trigger and test more of the possible stream item variants.

What's already covered:
- `Ok(WatchResponse::Ok(WatchEvent::Added { ... }))`
- `Err(watcher::stream::Error::Desync { ... }))` - should assert the underlying value (the `...` should be a concrete value matching the test input to assert the data is porperly passed)
- `Err(watcher::stream::Error::Other { ... }))` - same as above
- `Ok(WatchResponse::Ok(WatchEvent::ErrorStatus(Status { ... })))` (covered by the non-desync status error case)

What we probably should cover as well:
- `Ok(WatchResponse::Ok(WatchEvent::ErrorOther(RawExtension { ... })))` - pass the response event with some non-standard `type` (i.e. `extension_test`)
- `Ok(WatchResponse::Other(Ok(Some(serde_json::Value { ... })))` - pass a valid JSON that is not a valid `WatchResponse` - sth like `{"a":"b"}` should do
- `Ok(WatchResponse::Other(Ok(None))` - pass nothing?
- `Ok(WatchResponse::Other(Err(...))` - I presume this should be the value when passing an invalid JSON? It would be great to add a test that illustrates how to trigger this error

**Comment by eeyun** [comment]
This is ready to be tested! @tustvold (or anyone interested in testing this case) if you're curious to test I've created a docker image from this PR that can be pulled down like so:
```
docker pull eeyun/vector-k8s-test:error_misfire
```

**Review by MOZGIII — APPROVED** [review]
Great job!

File: Cargo.toml [hunk 7]
```diff
@@ -137,7 +137,7 @@ rand_distr = "0.4.0"
 regex = "1.3.9"
 bytes = { version = "0.5.6", features = ["serde"] }
 stream-cancel = "0.6.2"
-hyper = "0.13"
+hyper = "0.13.10"
```
Comment (fanatid) [inline Cargo.toml:140]: Unfortunately `0.13.10` not include `a00cc20afc597cb55cbc62c70b0b25b46c82a0a6`..
`0.13.0` commits: https://github.com/hyperium/hyper/commits/v0.13.10
`0.13.x` commits: https://github.com/hyperium/hyper/commits/0.13.x
`hyper` will be updated in #6217

Comment (eeyun) [reply Cargo.toml:140]: well that sucks! thanks for the heads up!

Comment (MOZGIII) [reply Cargo.toml:140]: Thanks, that's a good find! Thanks, great job!

Comment (fanatid) [reply Cargo.toml:140]: I moved `hyper` update from #6217 to separate PR for faster merge: https://github.com/timberio/vector/pull/6407 Will be grateful for approval there.

**Comment by uthng** [comment]
Hello,

Thanks a lot for the correction. But anyone can tell me when the new release including this is planed please ?
