### PR TITLE
enhancement: Add DataDog's `distribution` metric

### LINKED ISSUE #2603: statsd source not supporting Dogstatsd distribution type of metrics
https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/?tab=python#distribution

https://docs.datadoghq.com/developers/metrics/types/?tab=distribution#definition

All tested on latest nightly.

Simple example script in python
```
from datadog import initialize, statsd
import time
import random

options = {
    'statsd_host':'127.0.0.1',
    'statsd_port':8125
}

initialize(**options)

tags_list=["environment:dev"]

@statsd.timed('ss.test_metric.timer', tags=tags_list)
def my_function():
  time.sleep(random.randint(0, 10))

i = 0
while(1):
  i += 1
  statsd.set('ss.test_metric.set', i, tags=tags_list)

  my_function()

  statsd.increment('ss.test_metric.increment', tags=tags_list)
  statsd.decrement('ss.test_metric.decrement', tags=tags_list)

  statsd.gauge('ss.test_metric.gauge', i, tags=tags_list)

  statsd.increment('ss.test_metric.count_rate', sample_rate=0.5, tags=tags_list)

  statsd.distribution('ss.test_metric.distribution', random.randint(0, 20), tags=tags_list)

  statsd.histogram('ss.test_metric.histogram', random.randint(0, 20), tags=tags_list)

  time.sleep(2)
```

Will produce for distribution emit data this in Vector logs for statsd source

```
May 14 14:05:26 ip-10-105-195-187 vector[30693]: May 14 14:05:26.721 ERROR source{name=statsd type=statsd}: vector::sources::statsd: Statsd parse error: UnknownMetricType("d")
May 14 14:05:36 ip-10-105-195-187 vector[30693]: May 14 14:05:36.728 ERROR source{name=statsd type=statsd}: vector::sources::statsd: Statsd parse error: UnknownMetricType("d")
```

### Implementation
DataDog distribution type of metrics will be supported by expanding Vector `distribution` metric to, besides `histogram` statistic, support `summary` statistic. In sinks, this statistic differs only in two things from `histogram`:
- Aggregation of distribution points is done with sample statistic. This statistic mirrors Datadog distribution by producing aggregates defined at https://docs.datadoghq.com/developers/metrics/types/?tab=distribution#definition. #2913.
- 'datadog metric' sink maps `summary` to Datadog distribution metric. #3130

While we accept it through:
 - `statsd` source tagged with `d` which corresponds to Datadog distribution metric tag. #2913.
 - `log_to_metric` transform. #3726

Originally I thought we could reduce the amount of work by making `summary` to only differ from `histogram` in `datadog metric` sink, but that would make this feature inconsistent.

### Alternatives
Support the metric only in datadog metric' sink and `statsd` source/sink, while in other places default to histogram behavior. In documentation we would only add that we support `d` tag in `statsd` source/sink which is passed to `datadog metric` sink.

### Todo

Support of Dogstatsd distribution type of metrics

- [x] Add support to `log_to_metric` transform #3726

- [x] Update `influxdb_metrics` sink. #3846

- [x] Update `prometheus` sink. #4032 

- [x] Update docs. Waiting for implementations to be done.
    - [x] Consider better naming
    - [x] data-model/metric
    - [x] `log_to_metric` transform
    - [x] `datadog_metrics` sink
    - [x] `influxdb_metrics` sink
    - [x] `prometheus` sink
    - [x] recheck others

### PR DESCRIPTION
**Pull request by ktff**
Ref. #2603

PR expands the following:
* Our `metric` scheme with [`summary` metric](https://docs.datadoghq.com/developers/metrics/types/?tab=distribution#definition) by expanding `MetricValue::Distribution` to have `StatisticKind`. 
* `statsd` source to accept `d`.
* `statsd` sink to emit `d`.

Other sinks treat the new metric as `histogram`.

### Documentation
Minimal amount has been changed. 

We could update documentation for metric sinks:
* `aws_cloudwatch_metrics`
* `datadog_metrics`
* `prometheus`
* `influxdb_metrics`

but I'm unsure if we would like to do it now in this state.

### Naming
Instead of name `distribution`, `summary` was chosen for clarity in context of our `metric` scheme, and `MetricValue::Distribution` was not renamed so to avoid breaking change. 

### Todo

- [x] Use some other naming scheme?

- [x] Is changing `proto` a breaking change? (EDIT: in this case not)

- [x]  Documentation

   - [x] Update website documentation.

   - [x] Set timestamp to null in website documentation for `statsd` source ?   (EDIT: They show the end result)

   - [x] Recheck existing docmentation.

### CODE REVIEW

**Comment by ktff** [comment]
It has more to do with our code than DataDogs. The original `MetricValue::Distribution` could be split into two parts:
1. Collection of sample values
2. Aggregating those samples 

In the original version, the 2. part was calculating histogram. Since this new DataDog `distribution` also has those same steps with the 2. one being different, it made sense to explicitly split `MetricValue::Distribution` into those two steps so that we could reuse 1. step and have a bit simpler model since we now expose through type that there are two steps in this.

`AggregatedHistorgram` is just that, samples that have passed through 2. step which we only do in some of the sinks. If we would aggregate the samples in the sources we would do 2.step for all of the sinks which is not clear that we would want and would also be a breaking change.

Regarding naming scheme, I agree, it is confusing, the top level `Distribution` is now more akin to sample collection, so `Samples` could be a more appropriate name.

**Comment by ktff** [comment]
@lukesteensen `Distribution` has been renamed to better reflect what it is.

File: src/sinks/datadog/metrics.rs [hunk 1]
```diff
@@ -281,66 +218,106 @@ fn encode_events(events: Vec<Metric>, interval: i64, namespace: &str) -> Datadog
...
+                                                (q * 100.0) as u32
+                                            ),
+                                            DatadogMetricType::Gauge,
+                                            v,
+                                        ))
+                                    }
+
+                                    result
+                                }
+                                // https://docs.datadoghq.com/developers/metrics/types/?tab=distribution#definition
```
Comment (lukesteensen) [inline src/sinks/datadog/metrics.rs:279]: If I'm reading these docs correctly, it sounds like we should not be aggregating anything at all here:

> Unlike the HISTOGRAM metric type, which aggregates on the Agent during a given time interval, a DISTRIBUTION metric sends all the raw data during a time interval to Datadog, and aggregations occur server-side.

I think the aggregations you've defined here are the ones DataDog will calculate on their end, not the ones they expect to receive.

Comment (ktff) [reply src/sinks/datadog/metrics.rs:279]: True, I'll change it.

Comment (ktff) [reply src/sinks/datadog/metrics.rs:279]: It can't be done over Datadog's HTTP API. It doesn't have a way to submit Distribution points. We need to specify `interval` for the points, but their documentation says it's to be defined for `rate` and `count` only. https://docs.datadoghq.com/api/v1/metrics/

We can document this behavior on the website, it shouldn't be too suprising. 

`statsd` sink can be used to get this behavior.

**Comment by ktff** [comment]
cc @lukesteensen

File: src/sinks/datadog/metrics.rs (hunk 1 above)
Comment (lukesteensen) [reply src/sinks/datadog/metrics.rs:289]: Sorry for the slow response here @ktff. I've been digging into some DataDog code to see how these are sent and I think I have a pretty good idea.

The in-app libraries seem to forward these points to the datadog agent over the statsd protocol with the `d` type indicator. Within the agent, it seems that the individual points are aggregated into Datadog's custom [sketch](https://github.com/DataDog/sketches-go) data structure and then forwarded via an undocumented v2 API based on protocol buffers.

This is important because if we're not sending the individual points or that custom sketch type, we do not actually support DataDog distributions. That's way we're summarizing the points here does not allow them to be merged together on the server to determine quantiles across a whole infrastructure, which is the whole point of distributions over histograms.

As far as I can tell, there is no straightforward way for us to support this. We would have to implement DDSketch as a data structure internally and then reverse-engineer how to serialize and send them over the new undocumented API. We can't just fake it by aggregating locally since the whole point is to have the ability to aggregate globally.

**Comment by lukesteensen** [comment]
Moving forward, I think the best thing to do here is to accept the `d` statsd type in our statsd source and collect them into the histogram data type. Anything more complex than that is going to require a bit of research and experimentation.

File: src/sinks/datadog/metrics.rs (hunk 1 above)
Comment (ktff) [reply src/sinks/datadog/metrics.rs:289]: > We can't just fake it by aggregating locally since the whole point is to have the ability to aggregate globally.

True.

> there is no straightforward way for us to support this

I agree.

**Comment by ktff** [comment]
> accept the d statsd type in our statsd source

@lukesteensen what about extending this to `statsd` sink so that it can output `d` type, and every other sink can deal with it as a histogram? With it we can, accept `d`, pass it through, and we would have the backbone to approach this later, incrementally if needed.

**Comment by lukesteensen** [comment]
@ktff That sounds like a good plan to me!

**Comment by ktff** [comment]
@binarylogic 
Regarding timestamp in documentation of `statsd` source, examples show a concrete timestamp, while we are later mentioning that they are `null` value, which is also true in code. Going by this, examples should show `null`.

**Comment by ktff** [comment]
@binarylogic @lukesteensen could you review this? 

This turned out more complex than anticipated so after merging this I'll update #2603 with a proper plan.

I'm also unsure how to fix the `netlify` checks.
