### PR TITLE
fix(prometheus_exporter sink): Fix prometheus exposition format

### LINKED ISSUE #5907: Prometheus Sink Invalid Output Format
### Vector Version

```
v0.11.1
```

### Issue

The prometheus exposition format mandates that all metrics of a given type are output in a single group - see [here](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#grouping-and-sorting).

The prometheus_sink currently produces output that is interleaved, which breaks some parsers including the python prometheus client - see [here](https://github.com/prometheus/client_python/blob/master/prometheus_client/parser.py#L144).

I will look at getting a PR in to fix this

### PR DESCRIPTION
**Pull request by tustvold**
Closes #5907

Creating as draft whilst I test

### CODE REVIEW

**Comment by jamtur01** [comment]
Hi @tustvold! JUst FYI that the `Test Suite / Checks (pull_request)` job is failing because you need to run `cargo fmt` over the code.

File: src/sinks/prometheus/collector.rs [hunk 1]
```diff
@@ -221,29 +220,34 @@ impl MetricCollector for StringCollector {
...
-            None => writeln!(&mut self.result, " {}", value),
-            Some(timestamp) => writeln!(&mut self.result, " {} {}", value, timestamp),
+            None => writeln!(result, " {}", value),
+            Some(timestamp) => writeln!(result, " {} {}", value, timestamp),
         };
     }
 
     fn finish(self) -> String {
-        self.result
+        self.processed.into_iter().map(|(_, value)| value).collect()
```
Comment (bruceg) [inline src/sinks/prometheus/collector.rs:238]: Cool, I didn't know you could collect directly into a string. That's handy.

**Review by bruceg — APPROVED** [review]
Looks good, thanks!
