### PR TITLE
fix!(stdin source): switch off of broadcast channel

### LINKED ISSUE #3608: Lack of backpressure internal to stdin source leads to lost data
The stdin source can be easily overwhelmed by input and does not properly apply backpressure, resulting in a fatal error and lost data.

To reproduce, simply `cat` a large log file into the stdin source and you will see an error similar to the following:

```
ERROR source{name=in type=stdin}: vector::sources::stdin: Error reading line: Lagged(7795)
```

This happens because we're using a broadcast channel instead of a normal channel to pass data from the stdin thread. The broadcast channel we're using does not block writes when a reader falls behind and will overwrite the oldest data it has stored when a reader falls further behind than the total capacity of the channel. That reader then gets the `Lagged` error above, indicated that it did not keep up and missed messages.

This is obviously not how we want the stdin source to work, and it seems like the intent was to use the broadcast channel's ability to count its readers for shutdown purposes. While this is clever, we should find an alternative that does not compromise the runtime behavior of the source.

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #3608

There are three meaningful changes here. If any of them are controversial I can break this up, but they're all related and it was easy to simplify all at once.

## Use `mpsc` channel instead of `broadcast`

This is the big one. As described in #3608, the use of `tokio::sync::broadcast` channels here created the possibility for the background IO thread to outrun the forwarding task, which lead to lost data and an immediate shutdown. On my machine at least, this was extremely reproducible. 

The fix is to switch to normal `mpsc` channels that provide backpressure. This will slow down reads when the consumer can't keep up for any reason. It also actually simplifies the shutdown logic, since we are told directly by `send` when the consumer side of the channel has been shut down.

## Don't try to support multiple instances

The previous implementation contained a good deal of complexity that seemed intended to support running multiple instances of this source at the same time. It locked to ensure that only one background thread would be spawned and allowed later sources to tap in to the output of that existing thread. 

While this was a clever implementation, I do not believe this is a use case we need to support. I can think of no legitimate reason to run multiple instances of the stdin source over the lifetime of a vector process. I'd even go so far as to disallow configs that contain multiple.

By dropping this support, the implementation can also be dramatically simplified.

## Don't automatically break on IO errors

This is relatively minor, but it was a bit of a simplification to pass `std::io::Result`s through the channel and no special case them in the background thread to break on errors. The difference in behavior here would only come in the case of a non-fatal read error from stdin. Previously we would stop and shut down, but now we will continue. I'm not aware of a case where reading from stdin would return an error without closing the pipe, so I don't think this is meaningful in practice.

### CODE REVIEW

**Comment by binarylogic** [comment]
> I can think of no legitimate reason to run multiple instances of the stdin source over the lifetime of a vector process. I'd even go so far as to disallow configs that contain multiple.

👍

**Comment by jszwedko** [comment]
> I can think of no legitimate reason to run multiple instances of the stdin source over the lifetime of a vector process. I'd even go so far as to disallow configs that contain multiple.

The only reason I can think of is consistency in configuration. Assuming all other sources can be specified multiple times, this introduces an anomaly.

With regards to stdin specifically though, it seems like it'd be fairly rare. The only reason I can think of would be to vary the configuration parameters allowed (`host_key` and `max_length`).

**Comment by bruceg** [comment]
> I can think of no legitimate reason to run multiple instances of the stdin source over the lifetime of a vector process.

Ditto :+1:

**Comment by ktff** [comment]
> I can think of no legitimate reason to run multiple instances of the stdin source over the lifetime of a vector process. 

True. 

> I just think it is a little weird to special case sources; it seems like we'd generally allow multiple of a given type.

Most sources are technically limited in some way, ex. `socket` tcp source by the amount of ports, this is just the extreme version of that. That gives a precedence to limit the number of `stdin` sources to only one by checking it in the source itself and raising a build error, without loosing on consistency. I would prefer for this be added rather than leaving to those rare users that are experimenting with configuration to figure out why vector isn't behaving because they for ex. have two config files each using their own `stdin` source for locality/clarity sake.

**Comment by MOZGIII** [comment]
This should have `!` in the title as a breaking change cause it might break stuff for people using multiple `stdin` sources.

**Comment by jszwedko** [comment]
> Most sources are technically limited in some way, ex. socket tcp source by the amount of ports, this is just the extreme version of that.

True, but that is externally limited by system resources rather than an "artificial" limit imposed by vector.

Still, if it saves a lot of headaches, I think it's fine given that I think it'd be pretty rare. We can always add it back later if someone comes up with a compelling use-case.

>  I would prefer for this be added rather than leaving to those rare users that are experimenting with configuration to figure out why vector isn't behaving because they for ex. have two config files each using their own stdin source for locality/clarity sake.

Agreed :+1:

**Comment by jszwedko** [comment]
Actually, I see what you are saying. There really is only one stdin pipe. You've convinced me. :smile:

File: src/sources/stdin.rs [hunk 1]
```diff
@@ -82,102 +70,40 @@ pub fn stdin_source<R>(
...
-                            break;
-                        }
-                        Ok(line) => {
-                            if sender.send(Bytes::from(line)).is_err() {
-                                // There are no active receivers.
-                                // Try to stop.
-                                let mut guard =
-                                    CRITICAL_SECTION.lock().expect("CRITICAL_SECTION poisoned");
+    // Start the background thread
+    thread::spawn(move || {
```
Comment (fanatid) [inline src/sources/stdin.rs:81]: It's not related with this PR, but should we use [tokio::task::spawn_blocking](https://docs.rs/tokio/0.2.22/tokio/task/fn.spawn_blocking.html) everywhere instead `std::thread`? Currently, we use both options.

Comment (MOZGIII) [reply src/sources/stdin.rs:81]: It's a good question, I think it makes sense to use a thread for a case like this, where we have a loop inside. From the docs:

> This function is intended for non-async operations that eventually finish on their own. If you want to spawn an ordinary thread, you should use `thread::spawn` instead.

In this case the operation does finish on it's own though. I think it all depends on if it's "ok" to access the executor from the inside of `tokio::task::spawn_blocking`.

Either way, it's not clear to me either, so I'm looking forward to figuring this out.

**Comment by ktff** [comment]
> Actually, I think I see what you are saying. There really is only one stdin pipe. You've convinced me. smile

Yep, shame I didn't figured this out while introducing broadcast in the first place.

File: src/sources/stdin.rs (hunk 1 above)
Comment (lukesteensen) [reply src/sources/stdin.rs:81]: My understanding is that `spawn_blocking` is more for situations where a relatively fixed amount of work is done before the task completes. In our case, we are spawning a loop that runs essentially for the life of the process so I think a normal thread is more appropriate.
