### PR TITLE
fix(tests): work around internal_logs lack of isolation

### LINKED ISSUE #8301: `vector::sources::internal_logs::tests` tests are flakey
I see this one fail pretty frequently:

https://github.com/timberio/vector/runs/3070701946?check_suite_focus=true#step:9:133

I believe the issue is that the tests assume they are running in isolation as the tracing stuff is global, so sometimes they catch logs from other tests.

Maybe @bruceg has some ideas here.

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #8301

### CODE REVIEW

File: src/sources/internal_logs.rs [hunk 1]
```diff
@@ -99,17 +100,21 @@ mod tests {
 
     #[tokio::test]
     async fn receives_logs() {
+        let test_id: u8 = rand::random();
         let start = chrono::Utc::now();
```
Comment (bruceg) [inline src/sources/internal_logs.rs:104]: Could you just use this start time to provide a unique-enough ID? It contains at least a microsecond portion.

File: src/sources/internal_logs.rs [hunk 2]
```diff
@@ -99,17 +100,21 @@ mod tests {
...
 
-        error!(message = "After source started.");
+        error!(message = "After source started.", %test_id);
 
         sleep(Duration::from_millis(1)).await;
-        let events = collect_ready(rx).await;
+        let mut events = collect_ready(rx).await;
+        events.retain(|event| {
+            event.as_log().get("test_id") == Some(&Value::from(test_id.to_string()))
+        });
```
Comment (bruceg) [inline src/sources/internal_logs.rs:117]: This ends up repeatedly generating the `Value`. It's harmless since it's a test, but `rustfmt` may skip the extra block expansion this way:
```suggestion
        let test_id = Value::from(test_id.to_string());
        events.retain(|event| event.as_log().get("test_id") == Some(&test_id));
```

**Review by bruceg — APPROVED** [review]
This makes sense, and should work. I have a couple questions about making it a little trimmer.

File: src/sources/internal_logs.rs (hunk 1 above)
Comment (lukesteensen) [reply src/sources/internal_logs.rs:104]: I liked this idea initially, but it doesn't actually seem to simplify much. We'd need to stringify the timestamp to pass it as a field, and doing so in a way that's consistent and precise enough to be unique is a bit more than I'd want to inline all three places. So the end result is the same number of lines, a bit more complicated, and brings back the original concern of timing collisions.

Comment (bruceg) [reply src/sources/internal_logs.rs:104]: Fair enough.

**Review by jszwedko — APPROVED** [review]
Yessss! Thank you!
