### PR TITLE
fix(setup): Add support for detecting glibc version to installer script

### LINKED ISSUE #5415: Add support for detecting glibc version to installer script
For versions with glibc older than 2.18 use musl, alternatively use gnu.

https://dev.to/0xbf/how-to-get-glibc-version-c-lang-26he

### PR DESCRIPTION
**Pull request by jamtur01**
Closes #5415 

Signed-off-by: James Turnbull <james@lovedthanlost.net>

This is going to need careful eyes over. Basically:

1. Replaced ldd -version check with a function (get_gnu_musl_glibc)
2. This command runs ldd --version
3. If GNU then extracts glibc version and compares (using bc because bash doesn't speak float) to 2.18. If earlier it returns 'musl' otherwise returns 'gnu'
4. If musl then returns 'musl'.

### CODE REVIEW

File: distribution/install.sh [hunk 1]
```diff
@@ -207,6 +207,29 @@ add_to_path() {
 # be updated if necessary.
 # ------------------------------------------------------------------------------
 
+get_gnu_musl_glibc() {
+  need_cmd ldd
```
Comment (Hoverbear) [inline distribution/install.sh:211]: I think it might be a bit presumptuous to assume folks have `ldd`? Could we have a safe fallback?

Comment (jamtur01) [reply distribution/install.sh:211]: We already presume it in the current script so this is status quo.

File: distribution/install.sh [hunk 2]
```diff
@@ -207,6 +207,29 @@ add_to_path() {
...
+    _glibc_version=$(echo "$_ldd_version" | awk '/ldd/{print $NF}')
+    if [ 1 -eq "$(echo "${_glibc_version} < 2.18" | bc)" ]; then
+      echo "musl"
+    else
+      echo "gnu"
+    fi
+elif [[ $_ldd_version =~ "musl" ]]; then
+  echo "musl"
+else
+  err "Unknown architecture from ldd"
```
Comment (jszwedko) [inline distribution/install.sh:229]: Maybe we could print out the ldd version output here? That might help with bug reports at least.

File: distribution/install.sh [hunk 3]
```diff
@@ -207,6 +207,29 @@ add_to_path() {
 # be updated if necessary.
 # ------------------------------------------------------------------------------
 
+get_gnu_musl_glibc() {
+  need_cmd ldd
+  need_cmd bc
+  need_cmd awk
+  # Detect both gnu and musl
+  # Also detect glibc versions older than 2.18 and return musl for these
```
Comment (jszwedko) [inline distribution/install.sh:215]: Could we add a link to https://github.com/timberio/vector/issues/5412 here?

File: distribution/install.sh [hunk 4]
```diff
@@ -207,6 +207,29 @@ add_to_path() {
...
+  local _ldd_version
+  local _glibc_version
+  _ldd_version=$(ldd --version)
+  if [[ $_ldd_version =~ "GNU" ]]; then
+    _glibc_version=$(echo "$_ldd_version" | awk '/ldd/{print $NF}')
+    if [ 1 -eq "$(echo "${_glibc_version} < 2.18" | bc)" ]; then
```
Comment (jszwedko) [inline distribution/install.sh:221]: Not that I expect we'll actually run into this, but this would falsely result in it returning true once glibc hits version `2.100`.

I see some bash semvar comparison implementations on: https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash

Comment (jamtur01) [reply distribution/install.sh:221]: I want to hope this is fixed prior to 2.100 but let's take a look. :P

Comment (jamtur01) [reply distribution/install.sh:222]: I'm not going to change it for now - I think this works for the foreseeable future with less complexity than alternatives.

Comment (jszwedko) [reply distribution/install.sh:222]: :+1: yeah, that's fine. It seems unlikely we'll hit it before `cross` is patched or those old distros fall out of service.

Rather than a full semvar comparison, you could split the glibc version on `.` and compare major / minor independently with `bc`.

Or add a timebomb that would fail the script if `glibc_version` is longer than 4 characters (indicating that it hit `2.100`.

**Review by jszwedko — APPROVED** [review]
