### PR TITLE
fix(datadog_metrics sink): Use header auth

### LINKED ISSUE #2441: Datadog sink should use header authentication.
The `datadog` sink should use header authentication as specified in https://docs.datadoghq.com/api/?lang=bash#authentication.

This will prevent us from sending the API key as part of the URI and thus prevent us from logging it on more verbose logging levels.

### PR DESCRIPTION
**Pull request by LucioFranco**
Fixes #2441 

I am having some trouble actually sending metrics to datadog as I am getting a 404. That said, I've verified the healthcheck passes and we are getting the same 404 with the new changes. Since, this is my first time actually using this sink I could totally be doing something wrong so if someone has more experience could get that working that would be super helpful. Beyond that, this conforms to the docs and the healthcheck passes and we don't get any unauthenticated responses.

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
https://github.com/timberio/vector/issues/2427 is for the 404 error.

File: src/sinks/datadog/metrics.rs [hunk 1]
```diff
@@ -159,17 +159,21 @@ impl HttpSink for DatadogSink {
 
         http::Request::get(self.uri.clone())
             .header("Content-Type", "application/json")
+            .header("DD-API-KEY", self.config.api_key.clone())
```
Comment (lukesteensen) [inline src/sinks/datadog/metrics.rs:162]: Were we not doing anything with the API key for non-healthcheck requests before...?

Comment (lukesteensen) [reply src/sinks/datadog/metrics.rs:162]: Ah, we're still putting it in the URI on 118.
