### PR TITLE
fix(host_metrics source): Fix filtering of filesystem by device

### LINKED ISSUE #6920: host_metrics filesystem filtering by device patterns is not working
### Vector Version

```
vector 0.12.1 (v0.12.1 x86_64-unknown-linux-gnu 2021-03-12)
```

### Vector Configuration File

```toml
[sources.host_metrics_raw]
type = "host_metrics"
collectors = [
    "filesystem",
]
namespace = "Vector/EC2"
scrape_interval_secs = 15

[sources.host_metrics_raw.filesystem.devices]
includes = [
    "/dev/root",
]

[sinks.metrics_out]
type = "console"
inputs = ["host_metrics_raw"]
encoding.codec = "json"
```

### Expected Behavior

Expected to get metrics for only `/dev/root`.

### Actual Behavior

No metrics for any filesystem.

### Additional Context

I've tried several permutations of the includes filtering. By default, vector includes tons and tons of devices that I do not want. I only want the physical block devices.

For example, my desired setting is: `includes = ["/dev/root", "/dev/hd*", "/dev/sd*", "/dev/nvme*", "/dev/xvd*"]` .

When executing vector without any filtering (`includes = ["*"]`) then I get tons of stuff including cgroups, overlay filesystems, tmpfs, shm, etc. This is great but I want to filter it. Notably, one of the records I want shows up below:

```
{"name":"filesystem_free_bytes","namespace":"Vector/EC2","tags":{"collector":"filesystem","device":"/dev/root","filesystem":"ext4","host":"DUMMY_INSTANCE","mountpoint":"/"},"timestamp":"2021-03-29T17:08:53.463635035Z","kind":"absolute","gauge":{"value":126504243200.0}}
```

With an output like `"device":"/dev/root"` I cannot understand why the filter is not working and even at trace level there is no output on what devices match what patterns.

I also tried filtering by filesystem, such as `filesystem.filesystems.includes = ["ext4"]` and this did result in the desired output so it appears specific to the devices filtering.

A couple other things worth noting:

I also tried without the `/dev/` prefix to no avail.

`/dev/root` is not a symlink, and it is apparently what is picked up when running vector on an ubuntu:20.04 AMI on EC2 for the root filesystem by vector, not `/dev/nvme*`. It is the same as the value from `cat /proc/cmdline`.

### PR DESCRIPTION
**Pull request by jszwedko**
Fixes #6920

Previously specifying any `includes` for device would cause no matches
due to bad boolean logic.

### CODE REVIEW

File: src/sources/host_metrics.rs [hunk 1]
```diff
@@ -545,13 +545,10 @@ impl HostMetricsConfig {
                     .filter_map(|partition| async { partition })
                     // Filter on configured devices
                     .map(|partition| {
-                        (self.filesystem.devices.is_empty()
-                            && partition
```
Comment (jszwedko) [inline src/sources/host_metrics.rs:549]: I could have also switched this to `||` here, but removing that part of the boolean check seems to match up better with how the other filtering is done.

File: src/sources/host_metrics.rs [hunk 2]
```diff
@@ -1214,6 +1207,7 @@ mod tests {
             .await;
 
             assert!(filtered_metrics_with.len() <= all_metrics.len());
+            assert!(filtered_metrics_with.len() > 0);
```
Comment (jszwedko) [inline src/sources/host_metrics.rs:1210]: This test was previously passing because nothing would match.

File: src/sources/host_metrics.rs (hunk 1 above)
Comment (bruceg) [reply src/sources/host_metrics.rs:549]: I think you're right on both counts. The `&&` is definitely wrong here. I broke the logic when I changed to this from an `if/else` block. Something is nagging me that the the `is_empty` guard is still needed (with a `||` of course) due to the desired semantics for when the filesystem has no device, but I can't work out when that might be the case.

File: src/sources/host_metrics.rs [hunk 3]
```diff
@@ -751,10 +748,6 @@ pub fn init_roots() {
 }
 
 impl FilterList {
-    fn is_empty(&self) -> bool {
```
Comment (bruceg) [inline src/sources/host_metrics.rs:754]: Looks like this is still needed for tests.

**Review by bruceg — CHANGES_REQUESTED** [review]

File: src/sources/host_metrics.rs (hunk 3 above)
Comment (jszwedko) [reply src/sources/host_metrics.rs:754]: Ah yes it is. Thanks!

File: src/sources/host_metrics.rs (hunk 1 above)
Comment (jszwedko) [reply src/sources/host_metrics.rs:549]: If the filesystem has no device it seems like the `map()` below would just skip any filtering and then it would default to returning `true` via the `unwrap_or()`.

I think this is OK behavior for this circumstance though I could maybe see users wanting to exclude filesystems with no devices if they specify an `includes` list.

Comment (bruceg) [reply src/sources/host_metrics.rs:549]: Ah yes, that was it. The `includes` list has the semantics of "only include the ones listed here". However, the `unwrap` would *also* include all the no-device filesystems, which is not desired.

**Comment by mmerickel** [comment]
This might be working as intended but while you're in this code I wanted to point out that the "devices" list here does not match `.disk.devices` in the `disk` collector. The `disk` collector outputs devices like `"device":"nvme0n1p1"` etc, without the `/dev/` prefix. 

An example is below:

```
{"name":"disk_read_bytes_total","namespace":"Vector/EC2","tags":{"collector":"disk","device":"nvme0n1","host":"DUMMY_INSTANCE"},"timestamp":"2021-03-29T18:31:15.691637235Z","kind":"absolute","counter":{"value":295421952.0}}
{"name":"disk_reads_completed_total","namespace":"Vector/EC2","tags":{"collector":"disk","device":"nvme0n1p1","host":"DUMMY_INSTANCE"},"timestamp":"2021-03-29T18:31:15.691651296Z","kind":"absolute","counter":{"value":10086.0}}
{"name":"filesystem_free_bytes","namespace":"Vector/EC2","tags":{"collector":"filesystem","device":"/dev/root","filesystem":"ext4","host":"DUMMY_INSTANCE","mountpoint":"/"},"timestamp":"2021-03-29T18:31:15.691926367Z","kind":"absolute","gauge":{"value":126497755136.0}}
```

The `/dev/root` fs is equivalent to `/dev/nvme0n1` and it's kind of a bummer that they don't match, but at the least I'd point out that the `filesystem` collector has the `/dev/` prefix and the `disk` collector does not.

**Comment by mmerickel** [comment]
Also, wow, thanks for working on this so quickly! Much appreciated :-)

File: src/sources/host_metrics.rs (hunk 1 above)
Comment (jszwedko) [reply src/sources/host_metrics.rs:549]: I think the `if_empty` guard won't result in the right behavior either though.

Imagine I specify `includes = ["foo"]`. `if_empty()` would return `true` and then it would do the below check by `map`ing and return the default of `true` if the filesystem has no device.

I think we want `unwrap_or(false)` with the `is_empty` check, but that won't cover the case where only `excludes` are supplied. That is, if I specify only `excludes = ["foo"]` I'd still expect to see filesystems with no devices.

This does highlight the possible need to explicitly include or exclude filesystems with no devices with some sort of "null" value. For example, `includes = ["foo", null]`. Perhaps some sort of sentinel string like `$empty` or `$null` could be used. What do you think?

Comment (bruceg) [reply src/sources/host_metrics.rs:549]: Hmm, yes, this logic defies a simple resolution. It might need a special matcher in `FilterList`.

There would be value in being able to match filesystems with no device, however I would say it is out of the scope of this issue and good for follow-up work.

Comment (jszwedko) [reply src/sources/host_metrics.rs:549]: :+1: I pushed https://github.com/timberio/vector/pull/6921/commits/6f2bfa750181c279132384dd34266d1e8d1f2bd4 which rectors the filtering logic to handle when the value being filtered on is not there. If `includes` is specified, and the value is `None`, it is excluded. If `excludes` is specified, and the value is `None`, it is allowed through.

Does that match what you were thinking?

I'll open a separate issue for allowing explicitly including or excluding null values.

Comment (jszwedko) [reply src/sources/host_metrics.rs:549]: Follow-up issue: https://github.com/timberio/vector/issues/6923

**Comment by jszwedko** [comment]
@mmerickel 

> This might be working as intended but while you're in this code I wanted to point out that the "devices" list here does not match `.disk.devices` in the `disk` collector. The `disk` collector outputs devices like `"device":"nvme0n1p1"` etc, without the `/dev/` prefix.

Hmm, that is an odd difference that seems to be from the underlying library we use to collect these metrics, heim. I'll open a separate issue for that. Thanks for pointing it out!

File: src/sources/host_metrics.rs [hunk 4]
```diff
@@ -751,42 +747,57 @@ pub fn init_roots() {
...
-        self.includes.is_none() && self.excludes.is_none()
-    }
-
-    fn contains_str(&self, value: &str) -> bool {
-        (match &self.includes {
+    fn contains_str(&self, value: Option<&str>) -> bool {
+        (match (&self.includes, value) {
```
Comment (bruceg) [inline src/sources/host_metrics.rs:751]: Hmm, it's unfortunate this has to change to support testing, as it is always called with `Some(…)`.

File: src/sources/host_metrics.rs [hunk 5]
```diff
@@ -751,42 +747,57 @@ pub fn init_roots() {
...
-        }) && match &self.excludes {
+            (Some(includes), Some(value)) => {
+                includes.iter().any(|pattern| pattern.matches_str(value))
+            }
+        }) && match (&self.excludes, value) {
             // No excludes, list excludes nothing
-            None => true,
+            (None, _) => true,
+            // No value, never excluded
+            (_, None) => true,
```
Comment (bruceg) [inline src/sources/host_metrics.rs:764]: I think this branch (and the parallel line in `contains_path`) should read `(Some(_), None)`

**Review by bruceg — APPROVED** [review]
Yes, this matches what I was thinking. I wonder if it would be worth making a common function to merge `contains_str` and `contains_path` to eliminate the need for `fn contains_test` which is largely only needed to keep the logic of those two in sync. Not needed to close this, though.

File: src/sources/host_metrics.rs (hunk 4 above)
Comment (jszwedko) [reply src/sources/host_metrics.rs:751]: Yeah, I thought that too though the parity is nice.

**Comment by jszwedko** [comment]
@bruceg I pushed https://github.com/timberio/vector/pull/6921/commits/ed3abf6a0280177d4587b2ec3cad3d80d60cf66c refactoring `contains_str` and `contains_path` to just `contains` and got rid of `contains_test`. Is something like that what you would have done? Or is there a better way?

**Comment by bruceg** [comment]
> @bruceg I pushed [ed3abf6](https://github.com/timberio/vector/commit/ed3abf6a0280177d4587b2ec3cad3d80d60cf66c) refactoring `contains_str` and `contains_path` to just `contains` and got rid of `contains_test`.

Hmm, I actually hadn't thought of doing it that way, but that doesn't mean it's a bad idea. I'd probably move the `match` into `enum FilterValue`, but that's a trivial difference.

My thought had been for `contains_path` and `contains_str` to call a common method with an extra closure parameter that would do the match. ie something like:
```rust
impl FilterList {
    fn contains_common<T, M>(&self, value: Option<&T>, matches: M)
        where M: Fn(&PatternWrapper, &T) -> bool;
    fn contains_str(&self, value: Option<&str>) -> bool {
        self.contains_common(value, |pattern, s| pattern.matches_str(s))
    }
}
```
I'm not sure which is the better pattern.

**Review by bruceg — APPROVED** [review]
Still LGTM :+1:
