### PR TITLE
fix(windows platform): Fix Windows metrics

### LINKED ISSUE #2305: Windows build step is broken
https://circleci.com/gh/timberio/vector/94082?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
   Compiling vector v0.9.0 (C:\Users\circleci\project)
   Compiling rdkafka v0.23.1
error[E0425]: cannot find value `metrics_trigger` in this scope
   --> src\main.rs:388:9
    |
388 |         metrics_trigger.cancel();
    |         ^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `vector`.
```

@Hoverbear @a-rodin any idea what's going on here? It's blocking `0.9.0`, which can wait until tomorrow.

### PR DESCRIPTION
**Pull request by Hoverbear**
Fixes #2305

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -385,7 +385,6 @@ fn main() {
 
         info!("Shutting down.");
         let shutdown = topology.stop();
-        metrics_trigger.cancel();
```
Comment (Hoverbear) [inline src/main.rs:388]: @lukesteensen I can't find this var around, I guess it was removed?

Comment (lukesteensen) [reply src/main.rs:388]: Yes. Sad we didn't notice before now :disappointed:
