### PR TITLE
fix: Emit `processed_events_total` after transform has processed event

### LINKED ISSUE #5596: `processed_events_total` for transforms is emmited before the event is processed
With #5492 the emission of `processed_events_total` metric was moved and unified to topology level where it is emitted when passing the event to the transform, and not actually when the event is processed. so the naming is not quite correct, although close, which can cause ordering issues and confusion. 

Before #5492, half of the transforms emitted before and half after the event was processed. 

Some ways of solving this are:
* Find a way to emit `processed_events_total` after it was processed. 
    * The main problem with this is `Transform::Task` type of transforms into which such emitting code can't be added to the right place so some changes to the architecture would be needed.
* Rename `processed_events_total` to `received_events_total` which would reflect it's current behavior. 
    * Will require changing api and it's consumers to handle both metrics.
* Go the middle route and only emit `processed_events_total` on topology level for `Transform::Function`, and return emitting of  `processed_events_total` back inside `Transform::Task`. 
    * It would more taxing for developers to follow this rule.
    * Athough this could reintroduce double counting issues, I don't expect for this kind of transforms to be reused.

cc. @MOZGIII

### PR DESCRIPTION
**Pull request by ktff**
Closes #5596

This fix takes the approach of moving the emits to happen after the events have been processed.

For `Transform::Function` that was trivial, but for `Transform::Task` we are assuming that when we pass an event to the transform and then the transform requests another event it has processed the first event. 

For all current `Task` transforms this holds. Generally this will hold so long as the events are consumed in a loop one after the other. This should hold in most cases, but some examples of when this doesn't hold are when the consumer batches events, or if it goes away and does something unrelated to the event which it has already processed. In such cases this construct can still be used, but it won't be accurate.

### CODE REVIEW

**Comment by ktff** [comment]
Failing test `tests::api_graphql_files_source_metrics` doesn't seem to be related.

**Review by jszwedko — COMMENTED** [review]
Nice @ktff !

The implementation looks sensible to me, but it did get me thinking about how we want to report these topology metrics more generally.

Also, it looks like the `filter` transform is still independently reporting `events_processed_total`. Should we drop that? I imagine it would result in double-counting.

Regarding general thoughts about reporting event metrics for the topology, I think your point about knowing when a task transform has truly processed a message is precscient. All we can say for sure is that the transform has accepted the event, but it might not be "processed" until much later. For the `reduce` transform, for example, it wouldn't truly be "processed" until the reduced event is emitted. For the `lua` or `wasm` transforms, we'd never really know. This seems related to @bruceg's concerns about propagating metadata.

My small proposal would be to, instead of having a singular `events_processed_total` metric that each component reports, we instead report separate `in` and `out` metrics, like:

* `events_in_total`: counts the events that been accepted by the components. For `transform` and `sink` components, we could emit at the topology layer similar as you are doing now, for `source` components, I think this metric is less useful, but the sources themselves could emit as they parse events, but before they flush them downstream.
* `events_out_total`: counts the events that have been emitted by the component, For the `source` and `transform` components, we could emit at the topology layer similar as you are doing now. For `sink` components, I think this metric is still useful given that sinks commonly do batching so it is useful to know the number of events that have actually been flushed to the external system. I think this would require instrumentation by each sink or possibly in the batching layer.

I think this would clearly convey that these are simply events going in and out of components rather than when an event has been "processed". It would also make it easy to see when transforms either reduce events by combining them or create a number of events from a single event.

Anyway, I'm happy to see this merged as-is though, as it simply improves things, but it did get me thinking. I'm curious if you have any thoughts on this.

**Comment by ktff** [comment]
>  it looks like the filter transform is still independently reporting events_processed_total. Should we drop that?

@jszwedko yes we should, good catch.

> instead of having a singular events_processed_total metric that each component reports, we instead report separate in and out metrics

@MOZGIII proposed something similar so #5596 and #5595 were created. I like the idea, its easier to define and gives more insight in what's going on.

This PR only puts `processed_events_total` of transforms in line with the other components so let's move this discussion to a separate issue, and closing  #5595 in favor of it.

File: src/stream.rs [hunk 1]
```diff
@@ -119,3 +135,51 @@ pub(crate) async fn tripwire_handler(closed: bool) {
...
+/// Calls function F after an item from stream has been processed
+/// by the consumer.
+///
+/// This assumes that the stream is being consumed in a loop, so when
+/// the consumer get's an item and then comes for another one
+/// we assume that it has processed the first item.
+/// This should hold in most cases. One example of when this doesn't
+/// hold is when the consumer batches items, or if it goes away and
+/// does something unrelated to the item which it has already processed.
+/// In such cases this construct can still be used, but it won't be accurate.
```
Comment (MOZGIII) [inline src/stream.rs:148]: What if the stream idles for a prolonged time? I think the assumption does not hold then, and I deem this would be a critical case - one we want to properly support.

Comment (jszwedko) [reply src/stream.rs:148]: I think this is also related to my thoughts that we should just have metrics for in/out rather than trying to determine when an event has been "processed" by a transform.

**Comment by jszwedko** [comment]
I opened https://github.com/timberio/vector/issues/6367 to track discussion around replacing this metric with in/out metrics.

**Comment by leebenson** [comment]
Good thoughts @jszwedko 👍 

In the context of the API.. would you imagine both in/out metrics being available?

Do you have an opinion on which would be the more compelling stat for `top`? (thinking, given the limited screen real estate, we might prefer one over the other.)

File: src/stream.rs (hunk 1 above)
Comment (ktff) [reply src/stream.rs:148]: > What if the stream idles for a prolonged time? 

It holds since the the stream will be polled in either case, so the emit will happen.

> I think this is also related to my thoughts that we should just have metrics for in/out rather than trying to determine when an event has been "processed" by a transform. 

I do agree, but I also don't think that we should wait for in/out to be added.

This is not perfect, but it works in our cases so I'm for going forward with this.

**Review by jszwedko — APPROVED** [review]
Looks good, thanks @ktff !
