### PR TITLE
fix(kubernetes_logs source): Replace incorrect invocation error with WatchStreamFailed

### LINKED ISSUE #7008: Invalid internal event used at kubernetes::instrumenting_watcher
https://github.com/timberio/vector/blob/1e18f1b3d97d5422d23cb979fe891384ab950669/src/kubernetes/instrumenting_watcher.rs#L57-L59

This is supposed to be a `internal_events::WatchStreamFailed`, but `WatchRequestInvocationFailed` is reused here mistakenly - it's only supposed to be used once later down in the code.

Not sure if `internal_events::WatchStreamFailed` exists yet, but if not - it has to be created (copied over from `WatchRequestInvocationFailed` with a corrected log message and metrics) and this code should be updated to use that.

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@gmail.com>

Closes #7008

### CODE REVIEW

File: src/internal_events/kubernetes/instrumenting_watcher.rs [hunk 1]
```diff
@@ -26,6 +26,21 @@ impl<E: Debug> InternalEvent for WatchRequestInvocationFailed<E> {
...
+    pub error: E,
+}
+
+impl<E: Debug> InternalEvent for WatchStreamFailed<E> {
+    fn emit_logs(&self) {
+        error!(message = "Watch stream failed.", error = ?self.error, internal_log_rate_secs = 5);
+    }
+
+    fn emit_metrics(&self) {
+        counter!("k8s_watch_stream_failed_total", 1);
```
Comment (jszwedko) [inline src/internal_events/kubernetes/instrumenting_watcher.rs:40]: I think we'll want to add this to the docs too: https://github.com/timberio/vector/blob/1e54aca6970a3f141749bd56d8cd8c98ba6e3fab/docs/reference/components/sources/kubernetes_logs.cue#L567-L574

Comment (spencergilbert) [reply src/internal_events/kubernetes/instrumenting_watcher.rs:40]: On a quick glance I think the docs are missing several metrics, do you want me to open another issue or just add them while I'm here?

Comment (jszwedko) [reply src/internal_events/kubernetes/instrumenting_watcher.rs:40]: 😢 if you don't mind adding them while you are looking, that would be nice. It could be a separate PR though, if you prefer to just add this one for now.

Eventually I think it'd be cool to extract these metrics from the rust code.

File: docs/reference/components/sources/kubernetes_logs.cue [hunk 2]
```diff
@@ -569,6 +569,15 @@ components: sources: kubernetes_logs: {
 		k8s_format_picker_edge_cases_total:     components.sources.internal_metrics.output.metrics.k8s_format_picker_edge_cases_total
 		k8s_docker_format_parse_failures_total: components.sources.internal_metrics.output.metrics.k8s_docker_format_parse_failures_total
 		k8s_event_annotation_failures_total:    components.sources.internal_metrics.output.metrics.k8s_event_annotation_failures_total
+		k8s_reflector_desyncs_total:		components.sources.internal_metrics.output.metrics.k8s_reflector_desyncs_total
```
Comment (jszwedko) [inline docs/reference/components/sources/kubernetes_logs.cue:572]: This file seemingly needs formatted via `cue fmt`.

**Review by jszwedko — APPROVED** [review]
Nice! Thanks for documenting all of the other missing metrics as well.

**Comment by spencergilbert** [comment]
The unit test fail seems related to the OOMs we've started to see in our CI runs, do we want to resolve that before merging this PR?
