### PR TITLE
fix(remap): Parse µs durations

### LINKED ISSUE #6884: VRL `parse_duration` doesn't support `µs`
Reported by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/824663949244760096

```
$ parse_duration!("49.437µs", "ms")
function call error for "parse_duration" at (0:34): unable to parse duration: '49.437µs'
```

We do support `µs` for the units argument, but not when parsing.

### PR DESCRIPTION
**Pull request by jszwedko**
Fixes #6884 

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

File: lib/vrl/stdlib/src/parse_duration.rs [hunk 1]
```diff
@@ -164,9 +164,16 @@ mod tests {
             tdef: TypeDef::new().fallible().float(),
         }
 
-        error_us {
+        us_s {
```
Comment (JeanMertz) [inline lib/vrl/stdlib/src/parse_duration.rs:167]: nit

```suggestion
        us_ms {
```

File: lib/vrl/stdlib/src/parse_duration.rs [hunk 2]
```diff
@@ -164,9 +164,16 @@ mod tests {
...
+            args: func_args![value: "1 µs",
+                             unit: "ms"],
+            want: Ok(0.001),
+            tdef: TypeDef::new().fallible().float(),
+        }
+
+        error_invalid {
             args: func_args![value: "foo",
-                             unit: "µs"],
+                             unit: "ms"],
```
Comment (JeanMertz) [inline lib/vrl/stdlib/src/parse_duration.rs:176]: I can't figure out why this change was required 🤔

**Review by JeanMertz — APPROVED** [review]

**Comment by JeanMertz** [comment]
@jszwedko updated the PR title, `remap transform` is the scope for the transform within Vector, whereas `remap` is the scope for the VRL language itself. 😄

File: lib/vrl/stdlib/src/parse_duration.rs (hunk 2 above)
Comment (jszwedko) [reply lib/vrl/stdlib/src/parse_duration.rs:176]: Aha, yeah, it isn't required. I just did it before making the other change to ensure this one was failing because `foo` is not a duration rather than `µs` was not a valid unit.

File: lib/vrl/stdlib/src/parse_duration.rs (hunk 1 above)
Comment (jszwedko) [reply lib/vrl/stdlib/src/parse_duration.rs]: 👍

**Comment by jszwedko** [comment]
> @jszwedko updated the PR title, `remap transform` is the scope for the transform within Vector, whereas `remap` is the scope for the VRL language itself. 😄

Aha, good to know 😄 Thanks! I'll make sure to use the labels and scopes that way.
