### PR TITLE
fix(lua transform): support sub-second timestamp resolution

### LINKED ISSUE #2331: Lua os.date table is not parsed as Vector timestamp if missing wday, yday, or isdst
The docs say https://vector.dev/docs/reference/transforms/lua/

> If such a table is passed from Lua to Vector, the fields yday, wday, and isdst can be omitted.

However the code requires that `yday`, `wday`, and `isdst` must be present.

https://github.com/timberio/vector/blob/ff4a6dccefc16f56910d49b996f797ef75de1759/src/transforms/lua/v2/interop/util.rs#L22

### Repro

```toml
[transforms.my_transform_id]
  type = "lua"
  inputs = ["my-source-id"]
  version = "2"

  # Hooks
  hooks.process = """
  function (event, emit)
    event.log.timestamp = {year = 2020, month = 1, day = 1, hour = 1, min = 1, sec = 1}
    event.log.message = "<msg>"
    emit(event)
  end
  """

[[tests]]
  name = "test my_transform_id"
  [[tests.inputs]]
    type = "raw"
    insert_at = "my_transform_id"
    value = "<ignore>"
  [[tests.outputs]]
    extract_from = "my_transform_id"
    [[tests.outputs.conditions]]
      type = "check_fields"
      "timestamp.eq" = "2020-01-01T01:01:01Z"
      "message.eq" = "<msg>"
```

### LINKED ISSUE #2332: No native way to pass sub-second timestamp resolution from Lua
The lua transform currently supports parsing a `os.date` table into a Vector timestamp. However, the Lua `os.date` table doesn't support sub-second resolution.

There's a couple ways to go about supporting sub-second resolution timestamps from Lua into Vector:

1. Do nothing and use a `coercer` transform to convert a Lua string into a timestamp. This currently works.

2. Support floats as the `sec` field in a Lua `os.date` table. This isn't a great idea because existing lua functions like `os.date` require `sec` to be an integer. Additionally, floats lose precision once you get into nanosecond range.

3. Add an optional field `nanosecond`. This is my preference. It plays nicely with existing Lua functions and doesn't lose precision.

### PR DESCRIPTION
**Pull request by jschaf**
Add an optional `nanosecond` field to the `FromLua` code to support
sub-second resolution in timestamps.

The default Lua table format for timestamps has an integer seconds
field. There's no sub-second field like milliseconds in the table
timestamp format. This means it's not possible to send timestamps
with sub-second resolution from Lua to Vector using the timestamp
table format alone.

Closes #2332.

### CODE REVIEW

File: src/transforms/lua/v2/interop/util.rs [hunk 1]
```diff
@@ -35,7 +33,8 @@ pub fn table_to_timestamp<'a>(t: LuaTable<'a>) -> LuaResult<DateTime<Utc>> {
     let hour = t.get("hour")?;
     let min = t.get("min")?;
     let sec = t.get("sec")?;
-    Ok(Utc.ymd(year, month, day).and_hms(hour, min, sec))
+    let nano = t.get("nanosecond").unwrap_or(0);
```
Comment (jschaf) [inline src/transforms/lua/v2/interop/util.rs:36]: I'm a rust newbie, not sure what the appropriate idiom is here.

File: website/metadata.js [hunk 2]
```diff
@@ -64,6 +64,15 @@ module.exports = {
       },
       "description": "Take Vector from zero to production in under 10 minutes.",
       "guides": [
+        {
```
Comment (jschaf) [inline website/metadata.js:67]: Ran `make generate` because that's what test failure said.

File: src/transforms/lua/v2/interop/util.rs (hunk 1 above)
Comment (a-rodin) [reply src/transforms/lua/v2/interop/util.rs:36]: I think it is better to use something like `t.get::<_, Option<u64>>("nanosecond")?.unwrap_or(0)`. The difference is that if a `Result` is not `Ok(...)`, then the error might be caused by reasons other than missing key, such as runtime errors. On the other hand, if there are no runtime errors, but the key is missing, then `get::<_, Option<u64>>?` would result in `None` and then applying `unwrap_or(..)` on an `Option`, as opposed to a result, would not mean ignoring any errors.

Also see https://github.com/timberio/vector/issues/2332#issuecomment-614047567 about the name of the field.

File: website/metadata.js (hunk 2 above)
Comment (binarylogic) [reply website/metadata.js:67]: Could you rebase with `master`? This should be resolved.

Comment (jschaf) [reply website/metadata.js]: Rebased fixed it.

File: src/transforms/lua/v2/interop/util.rs (hunk 1 above)
Comment (jschaf) [reply src/transforms/lua/v2/interop/util.rs]: Done, thanks for explaining.

**Comment by a-rodin** [comment]
Should the `nanosec` field also be added when the timestamps are passed from Rust to Lua?

**Comment by jschaf** [comment]
> Should the nanosec field also be added when the timestamps are passed from Rust to Lua? Also, the documentation should be updated, see DOCUMENTING.md.

`nanosec` should probably go both ways. I implemented it for both `FromLua` and `ToLua`.  I added documentation with an example of parsing a timestamp format since that's probably what most people need.

**Comment by jschaf** [comment]
@binarylogic What's the merge process? I can't merge because I don't have write access.

**Comment by binarylogic** [comment]
Hi @jschaf let me get a second set of eyes on the code. @a-rodin is out this week on vacation. We'll try to merge shortly if everything checks out.

File: website/docs/reference/transforms/lua.md [hunk 3]
```diff
@@ -717,7 +717,7 @@ by the following table:
...
-| [`Timestamp`][docs.about.data-model.log#timestamps] | [`table`][urls.lua_table] | There is no dedicated timestamp type in Lua. Because of that timestamps are represented as tables using the convention defined by [`os.date`][urls.lua_os_date] and [`os.time`][urls.lua_os_time]. The table representation of a timestamp  contain fields `year`, `month`, `day`, `hour`, `min`, `sec`, `yday`, `wday`, `isdst`. If such a table is passed from Lua to Vector, the fields  `yday`, `wday`, and `isdst` can be omitted. |
+| [`Timestamp`][docs.about.data-model.log#timestamps] | [`table`][urls.lua_table] | There is no dedicated timestamp type in Lua. Timestamps are represented as tables using the convention defined by [`os.date`][urls.lua_os_date] and [`os.time`][urls.lua_os_time]. The table representation of a timestamp contains the fields `year`, `month`, `day`, `hour`, `min`, `sec`, `yday`, `wday`, and `isdst`. If such a table is passed from Lua to Vector, the fields  `yday`, `wday`, and `isdst` can be omitted. In addition to the `os.time` representation, Vector supports sub-second resolution with a `nanosec` field in the table. |
```
Comment (LucioFranco) [inline website/docs/reference/transforms/lua.md:720]: Is this missing a mention to `nanosec`?

Comment (binarylogic) [reply website/docs/reference/transforms/lua.md:720]: I'll update.

**Comment by binarylogic** [comment]
Thanks @jschaf!
