### PR TITLE
fix(regex_parser transform): make truncation utf8-aware

### LINKED ISSUE #1349: panicked at 'byte index 55 is not a char boundary...
# parsed file
```
<http://somedata.int/demo/РискСрываПроекта_b1c766bdf9eed3acaeb35d56c09db0aa> <http://somedata.int/demo/createdForObject> <http://somedata.int/demo/КоммерческаяОрганизация_6986583>.
<http://somedata.int/demo/РискСрываПроекта_b1c766bdf9eed3acaeb35d56c09db0aa> <http://somedata.int/demo/createdByRule> "6"^^<http://www.w3.org/2001/XMLSchema#string>}
2019-10-22 14:54:01.569420 INSERT DATA { <http://somedata.int/demo/РискСрываПроекта_59a87d3659f01cd4ab31ec6526506c11> rdf:type <http://somedata.int/demo/РискСрываПроекта>.
<http://somedata.int/demo/РискСрываПроекта_59a87d3659f01cd4ab31ec6526506c11> rdf:type <http://www.w3.org/2002/07/owl#NamedIndividual>.
<http://somedata.int/demo/РискСрываПроекта_59a87d3659f01cd4ab31ec6526506c11> <http://somedata.int/demo/createdForObject> <http://somedata.int/demo/КоммерческаяОрганизация_6986583>.
<http://somedata.int/demo/РискСрываПроекта_59a87d3659f01cd4ab31ec6526506c11> <http://somedata.int/demo/createdByRule> "6"^^<http://www.w3.org/2001/XMLSchema#string>}
2019-10-22 14:54:35.782030 INSERT DATA { <http://somedata.int/demo/РискСрываПроекта_7c10fbcb680c383e70a345b78a8e48ef> rdf:type <http://somedata.int/demo/РискСрываПроекта>.
<http://somedata.int/demo/РискСрываПроекта_7c10fbcb680c383e70a345b78a8e48ef> rdf:type <http://www.w3.org/2002/07/owl#NamedIndividual>.
<http://somedata.int/demo/РискСрываПроекта_7c10fbcb680c383e70a345b78a8e48ef> <http://somedata.int/demo/createdForObject> <http://somedata.int/demo/КоммерческаяОрганизация_6986583>.
<http://somedata.int/demo/РискСрываПроекта_7c10fbcb680c383e70a345b78a8e48ef> <http://somedata.int/demo/createdByRule> "6"^^<http://www.w3.org/2001/XMLSchema#string>}
```

# config
```
[sources.sparql]
  type = "file"
  include = ["/var/log/test/sparql_updates_*.log"]
  message_start_indicator = '^([\d:\.\- ]+) ([\w ]+) (\{*)'
  start_at_beginning = true

[transforms.tfsparql]
  inputs = ["sparql"]
  type = "regex_parser"
  drop_field = false
  regex = '^(?P<timestamp>[\d:\.\- ]+) (?P<cmd>[\w ]+) (?P<message>(?s)\{*)'

[transforms.tfsparql.types]
  timestamp = "timestamp|%Y-%m-%d %H:%M:%S%.f"
  timestamp = "timestamp|%d.%m.%Y %H:%M:%S"
```

# error_log
```
[root@elastic1 vector]# RUST_BACKTRACE=1 vector --config ./test.toml
Dec 11 10:03:27.761  INFO vector: Log level "info" is enabled.
Dec 11 10:03:27.761  INFO vector: Loading config. path="./test.toml"
Dec 11 10:03:27.768  INFO vector: Vector is starting. version="0.4.0-dev" git_version="v0.5.0" released="Thu, 10 Oct 2019 18:39:52 GMT" arch="x86_64"
Dec 11 10:03:27.772  INFO vector::topology: Running healthchecks.
Dec 11 10:03:27.772  INFO vector::topology: Starting source "sparql"
Dec 11 10:03:27.772  INFO vector::topology: Starting transform "tfsparql"
Dec 11 10:03:27.772  INFO vector::topology: Starting sink "ttyout"
Dec 11 10:03:27.773  INFO healthcheck{name=ttyout}: vector::topology::builder: Healthcheck: Passed.
Dec 11 10:03:27.774  INFO source{name="sparql"}: vector::sources::file: Starting file server. include=["/var/log/test/sparql_updates_*.log"] exclude=[]
Dec 11 10:03:27.779  INFO source{name="sparql"}:file_server: file_source::file_server: Found file to watch. path="/var/log/test/sparql_updates_fusekidemo.log" file_position=0
thread 'tokio-runtime-worker-0' panicked at 'byte index 55 is not a char boundary; it is inside 'т' (bytes 54..56) of `<http://somedata.int/demo/РискСрываПроекта_b1c766bdf9eed3acaeb35d56c09db0aa> <http://somedata.int/demo/createdForObject> <http://somedata.int/demo/КоммерческаяОрганизация_6986583>.
<http://somedata.int/demo/РискС`[...]', src/libcore/str/mod.rs:2068:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: std::panicking::rust_panic_with_hook
   3: <unknown>
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::str::slice_error_fail
   7: <unknown>
   8: <vector::transforms::regex_parser::RegexParser as vector::transforms::Transform>::transform
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __rust_maybe_catch_panic
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: __rust_maybe_catch_panic
  24: <unknown>
  25: <unknown>
  26: tokio_threadpool::worker::Worker::run
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: __rust_maybe_catch_panic
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: start_thread
  40: clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Dec 11 10:03:27.792 ERROR transform{name="tfsparql"}: vector::topology: Unhandled error
Dec 11 10:03:27.792  INFO vector: Shutting down.
Dec 11 10:03:27.793 ERROR source-pump{name="sparql"}: vector::buffers: sender error: SendError("...")
Dec 11 10:03:27.793 ERROR source-pump{name="sparql"}: vector::topology: Unhandled error

```

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #1349 

When a regex pattern fails to match, we log a warning message that contains the value of the field we tried to match against. To keep the logs tidy, we truncate that value to a reasonable length.

The bug was that our truncation function didn't take into account multi-byte UTF-8 characters. If the byte index at which we attempted to truncate was not at a Unicode character boundary (i.e. in the middle of a multi-byte character), the string slice operation would panic and cause Vector to shut down.

### CODE REVIEW

File: src/transforms/regex_parser.rs [hunk 1]
```diff
@@ -177,7 +177,11 @@ impl Transform for RegexParser {
 
 fn truncate_string_at(s: &str, maxlen: usize) -> Cow<str> {
     if s.len() >= maxlen {
-        format!("{}[...]", &s[..maxlen - 5]).into()
+        let mut len = maxlen - "[...]".len();
+        while !s.is_char_boundary(len) {
+            len -= 1;
+        }
+        format!("{}[...]", &s[..len]).into()
```
Comment (bruceg) [inline src/transforms/regex_parser.rs]: Would it be worth making the `"[...]"` a `const` here?
