### PR TITLE
fix(buffers): Trigger `leveldb` compact after certain amount of deleted bytes

### LINKED ISSUE #2925: The LOG file of disk buffer becomes very large.
```
ubuntu@ip-192-168-20-141:/var/lib/vector$ ls -alh sink_tcp_log_buffer
total 21G
drwxr-xr-x 2 vector vector 3.6M Jul  1 02:49 .
drwxr-xr-x 4 vector vector 4.0K May 26 07:55 ..
-rw-r--r-- 1 vector vector  426 May 28 03:44 001249.ldb
-rw-r--r-- 1 vector vector    0 Jul  1 02:49 31102680.log
-rw-r--r-- 1 vector vector  827 Jul  1 02:49 31102681.ldb
-rw-r--r-- 1 vector vector   16 May 28 03:44 CURRENT
-rw-r--r-- 1 vector vector    0 May 26 07:53 LOCK
-rw-r--r-- 1 vector vector  20G Jul  1 02:49 LOG
-rw-r--r-- 1 vector vector 368K May 28 03:29 LOG.old
-rw-r--r-- 1 vector vector 1.7G Jul  1 02:49 MANIFEST-001238
```
Could I delete the LOG file?

vector.toml

```
[sinks.sink_tcp_log]
  inputs = ["src_tcp_log"]
  type = "socket"
  address = "the_address_of_vector_cluster"
  mode = "tcp" # required
  healthcheck = true # optional, default

  buffer.type = "disk"
  buffer.max_size = 1073741824 # 1G
  buffer.when_full = "block" # optional behavior: drop_newest

  encoding.codec = "text"
```

### LINKED ISSUE #3594: Vector buffer never get cleaned on SUSE 42.2 with Vector sink
```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

```toml
[sources.in]
  type = "journald" 

[sinks.vector]
  type = "vector"
  inputs = ["in"]
  address = "1.2.3.4:5000"
  healthcheck = true

  buffer.max_size = 504900000
  buffer.type = "disk"
  buffer.when_full = "block"
```

### Debug Output
```
https://gist.github.com/alpi-ua/dc498aa6a67ac73ff7f34cdddab7f37e
```

### Expected Behavior

ls /var/lib/vector/vector_buffer/ | wc -l
9
this output is from ubuntu

vector deleting files correctly on SUSE.

### Actual Behavior

Vector is not deleting buffer files and is holding them opened while running and have stable connection to the server.
Vector start consuming CPU due to a massive io blocking.

### Additional Context
cat /etc/osrelease
ID=opensuse
VERSION_ID="42.2"

uname -r
4.4.27-2-default

uname -m
x86_64

### PR DESCRIPTION
**Pull request by ktff**
Closes #2925
Closes #3594

In worst case scenario we were calling compaction of whole database for every event which caused all sorts of problems:
* #2925, all these compactions filled the log file. With this fix and in the reported situation the log file should be drastically smaller, somewhere in range of KiB.
* #3594, leveldb compaction algorithm is complex, but from what I can see, in essence, it stores compacted database to new file but there is a bug where it can sometimes leave old files, old logs, etc. It also possible that the old files are being used in some way, but since their size hasn't changed they keep occupying disk space.
* All this compactions basically throttled every event once the sink wasn't able to keep up with the source.

The fix is to trigger compaction once we have deleted `buffer.max_size/2` amount of bytes, and on shutdown. This will significantly reduce the amount of times we are compacting so avoiding the above issues. This should limit the size of database on file system to ~ `buffer.max_size*2` but there is no guarantee.

This PR also adds `rate` option to `blackhole` sink since it was useful in debuging this, but kinda off topic so we can separate this if there is any contention about it.

Config to replicate the issue:
```
[sources.source]
  type = "generator"
  format = "shuffle"
  lines = ["Line 1", "Line 2"]
  sequence = true 
  count = 2000

[sinks.sink]
  type = "blackhole" 
  inputs = ["source"] 
  rate = 100
  buffer.max_size = 1073741824
  buffer.type = "disk" 
  buffer.when_full = "block" 

```

### Open questions

- [x] Add benchmark for this scenario? (EDIT: We already have them)

### CODE REVIEW

**Comment by ktff** [comment]
cc. @lukesteensen

**Comment by ktff** [comment]
@lukesteensen  thought so, here are the relevant benchmark results
```
Benchmarking isolated_buffers/leveldb/reading
Benchmarking isolated_buffers/leveldb/reading: Warming up for 3.0000 s

Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 7.6s, or reduce sample count to 60.
Benchmarking isolated_buffers/leveldb/reading: Collecting 100 samples in estimated 7.5703 s (100 iterations)
Benchmarking isolated_buffers/leveldb/reading: Analyzing
isolated_buffers/leveldb/reading
                        time:   [36.358 ms 36.407 ms 36.458 ms]
                        thrpt:  [52.317 MiB/s 52.390 MiB/s 52.460 MiB/s]
                 change:
                        time:   [-83.778% -83.756% -83.732%] (p = 0.00 < 0.05)
                        thrpt:  [+514.71% +515.61% +516.45%]
                        Performance has improved.e are the relevant benchmark tests:
```
```
 Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 7.5s, or reduce sample count to 60.
Benchmarking isolated_buffers/leveldb/both: Collecting 100 samples in estimated 7.5383 s (100 iterations)
Benchmarking isolated_buffers/leveldb/both: Analyzing
isolated_buffers/leveldb/both
                        time:   [68.960 ms 69.022 ms 69.083 ms]
                        thrpt:  [27.609 MiB/s 27.634 MiB/s 27.659 MiB/s]
                 change:
                        time:   [-73.156% -73.130% -73.104%] (p = 0.00 < 0.05)
                        thrpt:  [+271.80% +272.16% +272.53%]
                        Performance has improved.
```

We should try to include this in 0.12

File: src/buffers/disk/leveldb_buffer.rs [hunk 1]
```diff
@@ -278,6 +295,9 @@ impl super::DiskBuffer for Buffer {
 
         let initial_size = db.value_iter(ReadOptions::new()).map(|v| v.len()).sum();
         let current_size = Arc::new(AtomicUsize::new(initial_size));
+        // We don't know what the real size is, but ,all things equal, it should have
+        // uniform distribution and one half of max is right in the middle of it.
+        let uncompacted_size = (initial_size as f64 * MAX_UNCOMPACTED * 0.5) as usize;
```
Comment (lukesteensen) [inline src/buffers/disk/leveldb_buffer.rs:300]: We could also trigger compaction on startup so that we don't have to guess. It's likely redundant with the compaction we do when shutting down, but shouldn't hurt anything.

File: src/buffers/disk/leveldb_buffer.rs [hunk 2]
```diff
@@ -239,16 +244,28 @@ impl Reader {
...
 
-            self.db.compact(&Key(0), &Key(self.delete_offset));
-
             let size_deleted = self.unacked_sizes.drain(..num_to_delete).sum();
             self.current_size.fetch_sub(size_deleted, Ordering::Relaxed);
+
+            self.uncompacted_size += size_deleted;
+            if self.uncompacted_size as f64 > self.max_size as f64 * MAX_UNCOMPACTED {
+                self.compact();
+            }
```
Comment (lukesteensen) [inline src/buffers/disk/leveldb_buffer.rs:253]: My only real concern here is that this can cause us to use significantly more disk space than `max_size`, which is already a somewhat confusing configuration option for users.

Maybe instead of `uncompacted_size` being in addition to `max_size`, we split `max_size` and use ~90% for normal data and ~10% for uncompacted data (or 95/5 or something like that)? This will reduce how much we store when the buffer is full but should help us stay within `max_size` for total disk use and avoid the situation where we compact on every write.

**Review by lukesteensen — COMMENTED** [review]
This looks really good, thanks @ktff! Noted my one concern about how this affects our total disk usage vs `max_size`.

File: src/buffers/disk/leveldb_buffer.rs (hunk 1 above)
Comment (ktff) [reply src/buffers/disk/leveldb_buffer.rs:300]: True.

File: src/buffers/disk/leveldb_buffer.rs (hunk 2 above)
Comment (ktff) [reply src/buffers/disk/leveldb_buffer.rs:253]: > Maybe instead of uncompacted_size being in addition to max_size, we split max_size and use ~90% for normal data and ~10% for uncompacted data

True, that will make more sense.  I'll play a bit with 20%, 10%, and 5%, and see what's happening.

Comment (ktff) [reply src/buffers/disk/leveldb_buffer.rs]: 10% will do fine. I'm curious what the benchmarks will show though.

Comment (ktff) [reply src/buffers/disk/leveldb_buffer.rs]: They still show the same improvement, so let's go with 10%.

File: src/buffers/disk/leveldb_buffer.rs [hunk 3]
```diff
@@ -239,16 +247,30 @@ impl Reader {
...
             self.delete_offset = new_offset;
 
-            self.db.compact(&Key(0), &Key(self.delete_offset));
-
             let size_deleted = self.unacked_sizes.drain(..num_to_delete).sum();
             self.current_size.fetch_sub(size_deleted, Ordering::Relaxed);
+
+            self.uncompacted_size += size_deleted;
+            if self.uncompacted_size as f64
+                > self.max_size as f64 * MAX_UNCOMPACTED / (1.0 - MAX_UNCOMPACTED)
```
Comment (lukesteensen) [inline src/buffers/disk/leveldb_buffer.rs:255]: It might be simpler to pass down a `max_uncompacted` the same way we pass down the new `max_size`, just to make this math easier to understand at a glance. Then it could be just `max_size * MAX_UNCOMPACTED` in `build` below. It's also clearer that we aren't recalculating the max every time.

**Review by lukesteensen — APPROVED** [review]
One small comment, but otherwise this looks good! This is a much better tradeoff than we were making before, so thanks for doing this @ktff.

File: src/buffers/disk/leveldb_buffer.rs (hunk 3 above)
Comment (ktff) [reply src/buffers/disk/leveldb_buffer.rs]: True, that's now much clearer.

**Comment by jszwedko** [comment]
Just noting a couple of nice benchmark improvements from this:

```
 isolated_buffers/leveldb/reading                                                                     35.163 ms  -84.042%     54.243 MiB/s    +526.66%           0.00  improved
isolated_buffers/leveldb/both                                                                        66.277 ms  -73.647%     28.778 MiB/s    +279.46%           0.00  improved
```
