### PR TITLE
fix(internal_metrics source): Rework defaults and a minimal scraping interval value

### LINKED ISSUE #5680: Disallow a `scrape_interval` value of <= 0.5 seconds
We should disallow a `scrape_interval` value of <= 0.5 for all metrics sources. I chose this value since it seems like the lowest value that would not produce high CPU usage. I'd be happy to allow a lower value if we could demonstrate that it does not significantly increase CPU usage.

### PR DESCRIPTION
**Pull request by MOZGIII**
This PR fixes a bug with the scarping interval being 0 if the setting is omitted in the config file.

It also adds a lower limit to the interval value.

Closes #5680.

### CODE REVIEW

File: src/sources/internal_metrics.rs [hunk 1]
```diff
@@ -9,23 +9,12 @@ use futures::{stream, SinkExt, StreamExt};
 use serde::{Deserialize, Serialize};
 use tokio::time;
 
-#[serde(deny_unknown_fields)]
-#[derive(Deserialize, Serialize, Debug, Clone)]
+#[derive(Deserialize, Serialize, Debug, Clone, Derivative)]
+#[derivative(Default)]
+#[serde(deny_unknown_fields, default)]
 pub struct InternalMetricsConfig {
-    #[serde(default = "default_scrape_interval_secs")]
```
Comment (jszwedko) [inline src/sources/internal_metrics.rs:15]: Did you find why this wasn't being applied? Just wondering so we can avoid this situation.

File: src/sources/internal_metrics.rs [hunk 2]
```diff
@@ -9,23 +9,12 @@ use futures::{stream, SinkExt, StreamExt};
...
-}
-
-impl Default for InternalMetricsConfig {
-    fn default() -> Self {
-        Self {
-            scrape_interval_secs: default_scrape_interval_secs(),
-        }
-    }
+    #[derivative(Default(value = "2.0"))]
+    scrape_interval_secs: f64,
```
Comment (jszwedko) [inline src/sources/internal_metrics.rs:17]: I think this change to `f64` is ok, but we may want to update the `scrape_interval_secs` on other components (like the `prometheus_scrape` source) to be `f64`s to avoid confusion. Alternatively, we put this back to `u64` with a lower-bound of `1` (which we may also want to roll out to other `scrape_interval_secs`).

File: src/sources/internal_metrics.rs [hunk 3]
```diff
@@ -44,12 +33,16 @@ impl SourceConfig for InternalMetricsConfig {
...
-        Ok(Box::pin(run(
-            get_controller()?,
-            self.scrape_interval_secs,
-            out,
-            shutdown,
-        )))
+        let interval = time::Duration::from_secs_f64(self.scrape_interval_secs);
+        if interval < time::Duration::from_millis(500) {
+            return Err(format!(
+                "interval set too low ({} secs), use interval >= 0.5 secs",
```
Comment (jszwedko) [inline src/sources/internal_metrics.rs:39]: Assuming we want to keep this a float, I'm wondering if this should be a warning rather than an error as there is nothing technically stopping them from using a lower value, it just may increase CPU utilization.

File: src/sources/internal_metrics.rs (hunk 1 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs:15]: I didn't find the exact cause, but I suspect the cause was the lack of `default` in serde macro.

https://github.com/timberio/vector/blob/491302313e3e60839bf5ce962ef20302c4caa3d4/src/sources/internal_metrics.rs#L14

File: src/sources/internal_metrics.rs (hunk 2 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs:17]: Let's change everything to `f64` - it makes way more sense to specify seconds with floats rather than integers.

Comment (MOZGIII) [reply src/sources/internal_metrics.rs:17]: Don't want to do in for all of the components in this PR though. Would the resolution be to revert to seconds here and revisit it in a separate PR that addresses just that? Or should we let this one pass as `f64`?

File: src/sources/internal_metrics.rs (hunk 3 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs:39]: Well, this is reasonable, I'll change to warning.

File: src/sources/internal_metrics.rs (hunk 2 above)
Comment (jszwedko) [reply src/sources/internal_metrics.rs:17]: :+1: I'm fine with switching them all. My preference would be to leave this as `u64` and have a separate PR that changes them all at once.

File: src/sources/internal_metrics.rs (hunk 1 above)
Comment (jszwedko) [reply src/sources/internal_metrics.rs:15]: Hrm, that _shouldn't_ be the case from my understanding. Putting `default` on the container causes it to use the `Default` implementation for the container, but I don't think that is required for using `default` on individual fields.

For example, it worked fine on the `apache_metrics` source:

https://github.com/timberio/vector/blob/ef45085f1c217fea58c9c608314baeae596945e2/src/sources/apache_metrics/mod.rs#L27-L34

I feel like something else must have been going on here.

Comment (jszwedko) [reply src/sources/internal_metrics.rs:15]: The default actually seems fine on `master` for me:

```
{"name":"vector_started_total","timestamp":"2020-12-23T16:24:18.317974885Z","tags":null,"kind":"absolute","counter":{"value":1.0}}
{"name":"uptime_seconds","timestamp":"2020-12-23T16:24:20.317064449Z","tags":null,"kind":"absolute","gauge":{"value":2.0}}
{"name":"vector_started_total","timestamp":"2020-12-23T16:24:20.317135170Z","tags":null,"kind":"absolute","counter":{"value":1.0}}
{"name":"uptime_seconds","timestamp":"2020-12-23T16:24:22.317164079Z","tags":null,"kind":"absolute","gauge":{"value":4.0}}
{"name":"vector_started_total","timestamp":"2020-12-23T16:24:22.317218451Z","tags":null,"kind":"absolute","counter":{"value":1.0}}
{"name":"uptime_seconds","timestamp":"2020-12-23T16:24:24.316297392Z","tags":null,"kind":"absolute","gauge":{"value":6.0}}
{"name":"vector_started_total","timestamp":"2020-12-23T16:24:24.316355289Z","tags":null,"kind":"absolute","counter":{"value":1.0}}
{"name":"uptime_seconds","timestamp":"2020-12-23T16:24:26.316387415Z","tags":null,"kind":"absolute","gauge":{"value":8.0}}
{"name":"vector_started_total","timestamp":"2020-12-23T16:24:26.316443145Z","tags":null,"kind":"absolute","counter":{"value":1.0}}
{"name":"uptime_seconds","timestamp":"2020-12-23T16:24:28.317004368Z","tags":null,"kind":"absolute","gauge":{"value":10.0}}
{"name":"vector_started_total","timestamp":"2020-12-23T16:24:28.317064219Z","tags":null,"kind":"absolute","counter":{"value":1.0}}
```

With:

```toml
[sources.in]
  type = "internal_metrics"

[sinks.out]
  type = "console"
  encoding.codec = "json"
  inputs = ["in"]
```

Am I misunderstanding the issue?

Comment (jszwedko) [reply src/sources/internal_metrics.rs:15]: I'm wondering if maybe the metrics collection itself, in the loop, was taking more than 2 seconds causing it to look like there was no default?

Comment (MOZGIII) [reply src/sources/internal_metrics.rs:15]: Well, I first added a log print at the source `run` fn and checked through that - the value was `0`, so didn't bother looking any further. :laughing: 
Interesting, if it works on `master`...
I'll have to double-check everything. :+1:

**Comment by jamtur01** [comment]
@MOZGIII What's the status here?

File: src/sources/internal_metrics.rs (hunk 3 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs]: Done

File: src/sources/internal_metrics.rs (hunk 2 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs]: Switched to `u64`.

File: src/sources/internal_metrics.rs (hunk 1 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs:15]: You're right, it is quite odd. We can still merge this PR though I guess - it simplifies things and adds a safety warning - still useful.

File: src/sources/internal_metrics.rs [hunk 4]
```diff
@@ -44,12 +33,15 @@ impl SourceConfig for InternalMetricsConfig {
...
-        Ok(Box::pin(run(
-            get_controller()?,
-            self.scrape_interval_secs,
-            out,
-            shutdown,
-        )))
+        let interval = time::Duration::from_secs(self.scrape_interval_secs);
+        if interval < time::Duration::from_millis(500) {
+            warn!(
+                "Interval set too low ({} secs), use interval >= 0.5 secs.",
```
Comment (jszwedko) [inline src/sources/internal_metrics.rs:39]:
```suggestion
                "Interval set to 0 secs, this could result in high CPU utilization.It is suggested to use interval >= 1 secs.",
```

Given this is a `u64` now, I think using `0.5` in the warning is a bit weird. I also tried to clarify the expected bad result of using `0`.

File: src/sources/internal_metrics.rs [hunk 5]
```diff
@@ -44,12 +33,15 @@ impl SourceConfig for InternalMetricsConfig {
...
+                interval.as_secs_f64()
```
Comment (jszwedko) [inline src/sources/internal_metrics.rs:40]:
```suggestion
```

It seems like this is a no-op since the value is never used?

**Review by jszwedko — COMMENTED** [review]
Thanks! I left a couple of comments, but otherwise this looks good. I guess the only functional change is the user will get a warning if they use 0 here given it seems like the default was previously being applied correctly already.

File: src/sources/internal_metrics.rs (hunk 5 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs:40]: Yep, together with the code suggestion above. You can create multi-line suggestions btw - just press on the line number and drag up or down when creating a comment!

File: src/sources/internal_metrics.rs (hunk 4 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs]: Thanks! Applied

File: src/sources/internal_metrics.rs (hunk 5 above)
Comment (jszwedko) [reply src/sources/internal_metrics.rs]: Aha! I didn't know that. Thanks!

File: src/sources/internal_metrics.rs [hunk 6]
```diff
@@ -44,12 +33,14 @@ impl SourceConfig for InternalMetricsConfig {
...
         out: Pipeline,
     ) -> crate::Result<super::Source> {
-        Ok(Box::pin(run(
-            get_controller()?,
-            self.scrape_interval_secs,
-            out,
-            shutdown,
-        )))
+        let interval = time::Duration::from_secs(self.scrape_interval_secs);
+        if interval < time::Duration::from_millis(500) {
```
Comment (jszwedko) [inline src/sources/internal_metrics.rs:37]:
```suggestion
        if interval < time::Duration::from_secs(1) {
```

Not a big deal, but I think this would be more consistent with the use of `u64` here.

**Review by jszwedko — APPROVED** [review]
Looks good!

File: src/sources/internal_metrics.rs (hunk 6 above)
Comment (MOZGIII) [reply src/sources/internal_metrics.rs:37]: Shouldn't this be <= 0 to match the warning?

Comment (MOZGIII) [reply src/sources/internal_metrics.rs]: Added https://github.com/timberio/vector/pull/5682/commits/874edc53c855f310460c888b2683a7ba92c99a78 instead

Comment (jszwedko) [reply src/sources/internal_metrics.rs]: :+1: that works too.
