### PR TITLE
fix(config): error on duplicate inputs

### LINKED ISSUE #8920: Duplicate inputs in a sink/transform cause panic: Duplicate output id in fanout, src/topology/fanout.rs:52:9
```
vector 0.16.1 (x86_64-unknown-linux-gnu 739e878 2021-08-26)
```

we had a mistake in our vector.toml leading to an input being defined twice in a sink:

```toml
[sinks.loki]
type = "loki"
inputs = [
  "journald_field_adder",
  "apt_term_logs_field_adder",
  "apt_history_logs_field_adder",
  "iptables_blocked_packets_field_adder",
  "nginx_access_logs_remap",
  "nginx_error_logs_remap",
  "nginx_access_logs_remap",
]
```

removing the duplicate input made the error go away.

we didn't get full debug output but I think this is the relevant part:

```
thread 'vector-worker' panicked at 'Duplicate output id in fanout', src/topology/fanout.rs:52:9
stack backtrace:
   0: std::panicking::begin_panic
   1: vector::topology::fanout::Fanout::add
   2: vector::topology::fanout::Fanout::process_control_messages
   3: <vector::topology::fanout::Fanout as futures_sink::Sink<vector_core::event::Event>>::poll_flush
   4: <futures_util::stream::stream::Forward<St,Si> as core::future::future::Future>::poll
   5: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
   6: tokio::runtime::task::harness::poll_future
   7: tokio::runtime::task::raw::poll
   8: tokio::runtime::thread_pool::worker::Context::run_task
   9: tokio::runtime::thread_pool::worker::run
  10: tokio::runtime::task::raw::poll
```

if needed I can try to make a minimally reproducible example, but maybe the error is obvious enough that it's not needed? let me know. thanks for an awesome piece of software!

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #8920

This also cleans up a small error message regression from when we
implemented full input glob patterns. Instead of saying that an input
doesn't match any components, we would say that the component had no
inputs, which isn't quite right.

Signed-off-by: Luke Steensen <luke.steensen@gmail.com>

### CODE REVIEW

File: src/config/validation.rs [hunk 1]
```diff
@@ -69,14 +69,27 @@ pub fn check_shape(config: &ConfigBuilder) -> Result<(), Vec<String>> {
...
         }
 
+        let mut frequencies = HashMap::new();
         for input in inputs {
+            let entry = frequencies.entry(input.clone()).or_insert(0usize);
+            *entry += 1;
             if !config.sources.contains_key(&input) && !config.transforms.contains_key(&input) {
                 errors.push(format!(
-                    "Input \"{}\" for {} \"{}\" doesn't exist.",
+                    "Input \"{}\" for {} \"{}\" doesn't match any components.",
```
Comment (jszwedko) [inline src/config/validation.rs:78]: 👍

**Review by jszwedko — APPROVED** [review]
Nice, thanks!
