### PR TITLE
fix(remap): allow uppercase and underscores in identifiers.

### LINKED ISSUE #6625: VRL doesn't allow uppercase characters in unquoted path fields
Spotted on [Discord](https://discord.com/channels/742820443487993987/764187584452493323/817079342626111518).

According to our [docs](https://master.vector.dev/docs/reference/vrl/expressions/#path_segments) path fields can be `_ (a-zA-Z0-9_)`. 

However VRL only accepts lowercase characters, as per [here](https://github.com/timberio/vector/blob/master/lib/vrl/parser/src/lex.rs#L1076).

Also, VRL does not allow underscores `_` at the first character position. 

These are allowed in our Toml config:

```toml
[transforms.rename]
type = "rename_fields"
inputs = ["json"]
fields._OLD_CHILD_NAME = "_NEW_CHILD_NAME" # example
```

So these should be allowed in VRL too.

### PR DESCRIPTION
**Pull request by FungusHumungus**
Closes #6625 

This updates VRL to allow uppercase characters in identifiers and underscores at the start of identifiers as per the [docs](https://master.vector.dev/docs/reference/vrl/expressions/#path_segments).

Previously underscores at the start of identifiers were being used to access test functions in the parser. I can't see these being used, but I have updated them to be `?`.

Signed-off-by: Stephen Wakely <stephen.wakely@datadoghq.com>

### CODE REVIEW

File: lib/vrl/parser/src/lex.rs [hunk 1]
```diff
@@ -500,10 +500,13 @@ impl<'input> Iterator for Lexer<'input> {
                     ':' => Some(Ok(self.token(start, Colon))),
                     ',' => Some(Ok(self.token(start, Comma))),
 
-                    '_' if self.test_peek(char::is_alphabetic) => {
+                    '_' if !self.test_peek(is_ident_continue) => {
+                        Some(Ok(self.token(start, Underscore)))
+                    }
+
+                    '?' if self.test_peek(char::is_alphabetic) => {
```
Comment (jszwedko) [inline lib/vrl/parser/src/lex.rs:507]: I almost want to make this some sort of obscure unicode character, but `?` seems like a fairly safe bet.

**Review by jszwedko — APPROVED** [review]
Thanks @FungusHumungus !

**Review by JeanMertz — APPROVED** [review]
Good catch 👍

> Previously underscores at the start of identifiers were being used to access test functions in the parser. I can't see these being used, but I have updated them to be ?.

I disabled those tests for the time being, but it would be wise to re-add them at some point, since we currently don't have any tests specifically targetting the parser (we have low-level lexer and compiler tests, and high-level integration tests, but no parser tests).

We'll be re-enabling the function tests, at which point I'd also like to invest some time to re-enable the parser tests (and expand on the set of compiler tests as well).
