### PR TITLE
fix(aws service): Allow zero size compressed messages

### LINKED ISSUE #7710: Avoid trying to decompress 0-byte files
A user reported an issue they are seeing with the `aws_s3` source where it fails to consume 0-byte gzip files and so does not consume the SQS message.

The error looks like:

```
WARN source{component_kind="source" component_name=input-us-east-1 component_type=aws_s3}: vector::internal_events::aws_s3::source: Failed to process SQS. self.message_id=0ffbafee-acd2-4512-a084-d696ef84038a self.error=Failed to read all of s3://***-prod-alb-logs-us-east-1/***/sand/AWSLogs/***/elasticloadbalancing/us-east-1/2021/06/01/***_elasticloadbalancing_us-east-1_app.awseb-AWSEB-B69UZE6O2334.df3b790b2ac0dace_20210601T1950Z_10.27.1.124_52kw5m7g.log.gz: unexpected end of file
```

We should skip decompression if the file is 0-bytes.

We probably have this issue in other places where we do decompression as well (like the `file` source).

### PR DESCRIPTION
**Pull request by ktff**
Closes  #7710

Enable for individually compressed messages to be empty for sources:
* `aws_kinesis_firehose`
* `aws_s3`

Other sources either don't have sub messages or they can't be individually compressed.

### CODE REVIEW

File: src/sources/aws_s3/mod.rs [hunk 1]
```diff
@@ -145,16 +147,23 @@ enum CreateSqsIngestorError {
...
     content_type: Option<&str>,
-    body: rusoto_s3::StreamingBody,
+    mut body: rusoto_s3::StreamingBody,
 ) -> Box<dyn tokio::io::AsyncRead + Send + Unpin> {
-    use async_compression::tokio::bufread;
+    let first = if let Some(first) = body.next().await {
+        first
+    } else {
+        return Box::new(tokio::io::empty());
+    };
```
Comment (bruceg) [inline src/sources/aws_s3/mod.rs:162]: Could this be accomplished more easily with `peekable`?
```suggestion
    let mut body = body.peekable();
    if body.peek().is_none() {
        return Box::new(tokio::io::empty());
    };
```
Then there's no need to chain this `first` with the rest of the body.

**Review by bruceg — APPROVED** [review]
Looks reasonable, though peekable might simplify one part.

File: src/sources/aws_kinesis_firehose/mod.rs [hunk 2]
```diff
@@ -204,9 +204,10 @@ mod tests {
             Compression::Auto => panic!("cannot encode records as Auto"),
             Compression::Gzip => {
                 let mut buffer = Vec::new();
-
-                let mut gz = GzEncoder::new(record, flate2::Compression::fast());
-                gz.read_to_end(&mut buffer)?;
+                if !record.is_empty() {
```
[the remark this answers is not in the document]
Comment (ktff) [reply src/sources/aws_kinesis_firehose/mod.rs:207]: It is added, just there bellow
```
            (
                Compression::Gzip,
                Compression::Gzip,
                true,
                Vec::new(),
                Vec::new(),
            ),
```

File: src/sources/aws_s3/mod.rs (hunk 1 above)
Comment (ktff) [reply src/sources/aws_s3/mod.rs:162]: > Could this be accomplished more easily with peekable?

Yes, but the compiler was complaining that `body.peekable().into_async_read()` doesn't implement `AsyncRead`, lost some 2h on that at which point I just gave up and implemented it like this. Trimming 1-2 lines of that isn't worth the time, although it would be good to know what was the issue.
