### PR TITLE
enhancement(elasticsearch sink): Improve retry error messages

### LINKED ISSUE #3789: ES error reporting should be better
As reported on [discord](https://discordapp.com/channels/742820443487993987/746070591097798688/753329583423619163), we don't do a great job surfacing certain errors in the ES sink.

We emit a [warning log](https://github.com/timberio/vector/blob/50a9c3af6779b887f9e72a313f7caee4c0d3c41c/src/sinks/elasticsearch.rs#L333-L338) directly when some messages in a request fail, and we also emit a more generic [error log](https://github.com/timberio/vector/blob/50a9c3af6779b887f9e72a313f7caee4c0d3c41c/src/sinks/util/retries.rs#L111) of the same error. The more specific warning log is rate limited while the error log is not, which can be confusing.

The simplest improvement here would be to consolidate these two log messages into one that provides both the high-level context (we are not retrying the request) and the details (ES error type and reason). In general, we should look for places like this where we're logging twice and try to ensure that it's clear where that logging should happen and that it has all the relevant information.

### PR DESCRIPTION
**Pull request by juchiast**
closes #3789 

Signed-off-by: Duy Do <juchiast@gmail.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks @juchiast. I saw the log message changes here, it seem like they might be inconsistent with https://github.com/timberio/vector/pull/3850, which will enforce this going forward.

**Comment by juchiast** [comment]
@binarylogic good call! I capitalized the messages.

File: src/sinks/elasticsearch.rs [hunk 1]
```diff
@@ -306,47 +306,26 @@ impl RetryLogic for ElasticSearchRetryLogic {
...
+                        Some(error) => {
+                            format!("error type: {}, reason: {}", error.err_type, error.reason)
                         }
+                        None => format!("error response: {}", body),
                     },
-                    None => RetryAction::Successful,
-                }
+                };
+
+                RetryAction::DontRetry(reason)
```
Comment (bruceg) [inline src/sinks/elasticsearch.rs:328]: This can be done without a `return`:
```rust
if body.contains("\"errors":true") {\
    …
} else {
    RetryAction::Successful
}
```

File: src/sinks/elasticsearch.rs [hunk 2]
```diff
@@ -306,47 +306,26 @@ impl RetryLogic for ElasticSearchRetryLogic {
...
-                                ),
-                            };
-                            RetryAction::DontRetry("some messages failed".into())
+
+                if !body.contains("\"errors\":true") {
+                    return RetryAction::Successful;
+                }
+
+                let reason = match serde_json::from_str::<ESResultResponse>(&body) {
+                    Err(json_error) => format!("could not parse response, error: {}", json_error),
```
Comment (bruceg) [inline src/sinks/elasticsearch.rs:319]: I think this loses the "some messages failed" context. In particular, the error is not that we could not parse the response, the error is that ES told us it wouldn't accept all the events, and we couldn't parse the message they gave us to describe what went wrong.

**Review by bruceg — CHANGES_REQUESTED** [review]

File: src/sinks/elasticsearch.rs (hunk 1 above)
Comment (juchiast) [reply src/sinks/elasticsearch.rs:328]: I used early return to avoid nesting too many matches.

File: src/sinks/elasticsearch.rs (hunk 2 above)
Comment (juchiast) [reply src/sinks/elasticsearch.rs]: added "some messages failed".

File: src/sinks/elasticsearch.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/elasticsearch.rs]: I think I will persist with my objection to this one. Since this function is somewhat long both with or without the early return, consider moving out some of the nested matches into a function.

Comment (juchiast) [reply src/sinks/elasticsearch.rs]: added `get_err_reason`

Comment (bruceg) [reply src/sinks/elasticsearch.rs]: This looks excellent.

**Review by bruceg — APPROVED** [review]
