### PR TITLE
fix(aws_cloudwatch_logs sink): Fix healthcheck to allow for log group creation at runtime

### LINKED ISSUE #7592: (sink) aws_cloudwatch_logs: healthcheck errors if log group doesn't exist
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Vector Configuration File

```toml
[sources.journald]
type = "journald"

[transforms.filter_journald]
  type = "filter"
  inputs = ["journald"]
  condition = """
  (to_int(.PRIORITY) ?? 0) < 4
  """

[transforms.remap_journald]
  type = "remap"
  inputs = ["journald"]
  source = """
  if !contains(.message,"boot") {
  abort
  }
  """

[sinks.out1]
type = "aws_cloudwatch_logs"
inputs = [ "filter_journald" ]
group_name = "journald_server_logs"
region = "eu-central-1"
stream_name = "aws1_journald"
encoding.codec = "json"

[sinks.out2]
type = "aws_cloudwatch_logs"
inputs = [ "remap_journald" ]
group_name = "boot_server_logs"
region = "eu-central-1"
stream_name = "aws1_boot"
encoding.codec = "json"
```

### Debug Output

```
ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=No log group found component_kind="sink" component_type="aws_cloudwatch_logs" component_name="out2" 
```

### Expected Behavior

Healthcheck passes, vector will create any missing log group by default.

### Actual Behavior

`aws_cloudwatch_logs` has a healthcheck that checks if the `log_group` is going to be dynamically generated from the log (using templating) [ref](https://github.com/timberio/vector/blob/master/src/sinks/aws_cloudwatch_logs/mod.rs#L499-L501). However, if a user is expecting Vector to use the default behavior of creating log group and log streams but with _hard coded_ `log_group`, like the example above with two separate sinks, the healthcheck will fail since it only looks for dynamism.

It seems to me that the conditional should rather check that the `create_missing_group` config is true, which is already more important than the group being dynamic. A dynamic group with `create_missing_group = false` _should_ fail by my understanding.

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@gmail.com>

Closes #7592

### CODE REVIEW

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 1]
```diff
@@ -529,7 +529,14 @@ async fn healthcheck(
                     Err(HealthcheckError::GroupNameError.into())
                 }
             }
-            None => Err(HealthcheckError::NoLogGroup.into()),
+            None => {
+                if config.create_missing_group.unwrap() == true {
```
[the remark this answers is not in the document]
Comment (spencergilbert) [reply src/sinks/aws_cloudwatch_logs/mod.rs:533]: I wasn't sure about that, because at the time of healthchecking the config should never be `None` - since the config as you say would default to true if unset

[the remark this answers is not in the document]
Comment (jszwedko) [reply src/sinks/aws_cloudwatch_logs/mod.rs:533]: It could be `None` there still. The values are defaulted when the `CloudwatchLogsSvc` struct is created: 

https://github.com/timberio/vector/blob/4d1ea4f336a0d7b97aa8e82fee55180ae063f8fe/src/sinks/aws_cloudwatch_logs/mod.rs#L281-L300

This healthcheck function just gets the raw config though.

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 2]
```diff
@@ -529,7 +529,14 @@ async fn healthcheck(
...
+                    info!("Cloudwatch group_name will be created at runtime");
```
Comment (jszwedko) [inline src/sinks/aws_cloudwatch_logs/mod.rs:534]: Seeing this written out, I'm actually coming around to the idea that we should just skip the healthcheck completely if `create_missing_group` is `true` similar to how we skip it if `log_group` is a template. In either case, the health check just always returns true.

File: src/sinks/aws_cloudwatch_logs/mod.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (spencergilbert) [reply src/sinks/aws_cloudwatch_logs/mod.rs:533]: Ah, so at this point the values could be Some(true), Some(false), or None?

File: src/sinks/aws_cloudwatch_logs/mod.rs (hunk 2 above)
Comment (spencergilbert) [reply src/sinks/aws_cloudwatch_logs/mod.rs:534]: Like add an `or create_missing_group == true` at this point?

File: src/sinks/aws_cloudwatch_logs/mod.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (jszwedko) [reply src/sinks/aws_cloudwatch_logs/mod.rs:533]: Yep! That's right.

File: src/sinks/aws_cloudwatch_logs/mod.rs (hunk 2 above)
Comment (jszwedko) [reply src/sinks/aws_cloudwatch_logs/mod.rs:534]: Well, I might have two separate conditionals to output two different log messages, but otherwise yeah.

Comment (spencergilbert) [reply src/sinks/aws_cloudwatch_logs/mod.rs:534]: The only reason I didn't want to completely short-circuit there was since the config defaults to true, it would make the healthcheck somewhat "pointless" but looking at the possible ways the healthcheck fails they're pretty much all related to the group name being problematic

Comment (jszwedko) [reply src/sinks/aws_cloudwatch_logs/mod.rs:534]: 🤔 yeah, that's true. I suppose this would still check that the AWS credentials can access the `DescribeLogGroups` API though we skip even that currently if the `group_name` is dynamic. I think we should have it be consistent for both. That is:

* If either `log_group` name is dynamic or `create_missing_group` is true, then check the API permissions, but otherwise don't fail
* If either `log_group` name is dynamic or `create_missing_group` is true, then skip the check entirely

My preference would be for the former.

Comment (spencergilbert) [reply src/sinks/aws_cloudwatch_logs/mod.rs:534]: Agreed - I'll take some time this afternoon to try larger rewrite

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 3]
```diff
@@ -529,7 +524,17 @@ async fn healthcheck(
                     Err(HealthcheckError::GroupNameError.into())
                 }
             }
-            None => Err(HealthcheckError::NoLogGroup.into()),
+            None => {
+                if config.group_name.is_dynamic() {
+                    info!("Cloudwatch group_name is dynamic.");
```
Comment (jszwedko) [inline src/sinks/aws_cloudwatch_logs/mod.rs:529]:
```suggestion
                    info!("Skipping healthcheck log group check: `group_name` is dynamic.");
```

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 4]
```diff
@@ -529,7 +524,17 @@ async fn healthcheck(
...
+                    return Ok(());
+                } else if config.create_missing_group.unwrap_or(true) {
+                    info!("Cloudwatch group_name will be created if missing.");
```
Comment (jszwedko) [inline src/sinks/aws_cloudwatch_logs/mod.rs:532]:
```suggestion
                    info!("Skipping healthcheck log group check: `group_name` will be created if missing.");
```

**Review by jszwedko — APPROVED** [review]
Nice! I adjusted the left a couple of suggestions for the info messages to provide more context since I don't think they will otherwise have much.

**Comment by spencergilbert** [comment]
> Nice! I left a couple of suggestions for the info messages to provide more context since I don't think they will otherwise have much.

Doh, sorta figured it'd be built out like `component_name::healthcheck message` - updated.
