### PR TITLE
fix(blackhole sink): Count total bytes for logs

### LINKED ISSUE #4704: Blackhole does not count full event bytes
Mentioned in discord: https://discordapp.com/channels/742820443487993987/751109034827972709/768956157972578334

@lucperkins observed that the `blackhole` sink was reporting 0 bytes processed for log events even though events were flowing through. This turned out to be due to the fact that his logs did not contain a `message` field which is what the `blackhole` sink currently counts for logs.

```toml
[sources.logs]
type = "docker"
include_containers = ["flog"]

[sinks.out]
type = "blackhole"
inputs = ["logs"]
```

### PR DESCRIPTION
**Pull request by jszwedko**
I opted to encode event as JSON to match `Metric` handling. I could be
convinced that we should use `size_of()` instead here and possibly in
other places that report processed bytes in relation to events.

**EDIT**: This now uses std::mem::size_of_val instead rather than serializing the event.

Fixes #4704

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by jszwedko** [comment]
Actually, I think I've come around to wanting to just use the memory size. I'll update this tomorrow and see what people think.

At least one other person agrees: https://discordapp.com/channels/742820443487993987/746070604192415834/768975478681239573 :smile:

File: src/sinks/blackhole.rs [hunk 1]
```diff
@@ -70,14 +70,11 @@ impl StreamSink for BlackholeSink {
...
-                Event::Log(log) => log
-                    .get(crate::config::log_schema().message_key())
-                    .map(|v| v.as_bytes().len())
-                    .unwrap_or(0),
-                Event::Metric(metric) => {
-                    serde_json::to_string(&metric).map(|v| v.len()).unwrap_or(0)
-                }
-            };
+                Event::Log(log) => serde_json::to_string(&log),
+                Event::Metric(metric) => serde_json::to_string(&metric),
```
Comment (Hoverbear) [inline src/sinks/blackhole.rs:74]: Perhaps there is a better measurement of bytes processed since the internal representation of metrics are much more compact than the expanded form. 🤔 

But, c'est la vie, this seems correct given the situation at hand.

**Review by Hoverbear — APPROVED** [review]
Seems good =D

File: src/sinks/blackhole.rs (hunk 1 above)
Comment (binarylogic) [reply src/sinks/blackhole.rs:74]: Agree, this change is solely for logs. But knowing total bytes for all data is still nice.

**Comment by jszwedko** [comment]
@Hoverbear @binarylogic I ended up switching to `std::mem::size_of_val` since this seems more relevant for this sink.

**Review by Hoverbear — APPROVED** [review]
I'm not sure this will be what you want since this will be the size of the event type?

**Review by Hoverbear — CHANGES_REQUESTED** [review]
Wrong button

**Comment by jszwedko** [comment]
> I'm not sure this will be what you want since this will be the size of the event type?

Ah, yeah, you are right. I misunderstood what that method did.

I started looking at the [`heapsize`](https://crates.io/crates/heapsize) and [`deepsize`](https://crates.io/crates/deepsize) crates to get the actual size of the value on the heap. This led me to https://internals.rust-lang.org/t/sizeof-trait-and-derive-sizeof/12672.

I started trying out `deepsize` given the restrictions mentioned regarding `heapsize` in https://github.com/servo/servo/blob/faf3a183f3755a9986ec4379abadf3523bd8b3c0/components/malloc_size_of/lib.rs#L11-L21, but this ended up spidering out quite a bit as it requires implementing or deriving `DeepSizeOf` which necessitated wrapping types like; `struct Map<T, U>(BTreeMap<T, U>); ` for `LogEvent.fields` so that I could implement `DeepSizeOf` on it.

Given this measurement is currently only useful for the `blackhole` sink, I switched this back to the JSON serialization approach. This isn't perfect, but is an improvement over the current implementation. If we find measuring the heap size useful in other contexts, we can revisit integrating `deepsize` or `heapsize`.

**Review by Hoverbear — APPROVED** [review]
