### PR TITLE
fix(buffers): Re-enable buffering reclaim test

### LINKED ISSUE #1253: Re-enable buffering tests on all platforms
Currently this test is enabled only on Unix platforms (see https://github.com/timberio/vector/pull/1205#issuecomment-557081933):

https://github.com/timberio/vector/blob/f9c486ce4abcd77cf61ddc7fe2fadb4aeae3b806/tests/buffering.rs#L13-L88 

The problem with it is that the first 10 messages which are stored to the disk buffer are consumed, but the last 10 messages are lost, so this assertion fails: https://github.com/timberio/vector/blob/f9c486ce4abcd77cf61ddc7fe2fadb4aeae3b806/tests/buffering.rs#L87

@LucioFranco suggested in https://github.com/timberio/vector/pull/1219#issuecomment-558161354 that resolving some futures on Windows might require reactors or timers. It is possible that problems with this test have the same nature, however I was not able to isolate them because `rt::block_on` call is there in this case.

### PR DESCRIPTION
**Pull request by LucioFranco**
Related to #1417

Closes #1253

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

File: tests/buffering.rs [hunk 1]
```diff
@@ -317,6 +316,7 @@ fn test_reclaim_disk_space() {
         .map(|m| m.len())
         .sum();
 
-    println!("after {}, before {}", after_disk_size, before_disk_size);
-    assert!(after_disk_size < before_disk_size);
+    // Ensure that the disk after is _atleast_ more than half as small
+    // as it was before.
```
Comment (lukesteensen) [inline tests/buffering.rs]: "at least more than half as small" is breaking my brain

Comment (LucioFranco) [reply tests/buffering.rs]: haha, yeah I thought it made sense coming out of my brain but I guess hearing it out it doesn't. Let me fix that.
