### PR TITLE
fix(vrl): handle complex ruby objects

### LINKED ISSUE #8872: Parse_ruby_hash not handling underscores
Hi,
The `parse_ruby_hash!` function doesn't seem to handle underscores. It fails for me when any key contains an underscore, which makes it unusable since Ruby uses snake case as naming convention.

### Vector Version

```
0.15.2
```

### Vector Configuration File

I've created a minimal example that fails when running a unit test on it.

```json
  "transforms": {
    "ruby_hash_parser": {
      "type": "remap",
      "inputs": ["rails_log"],
      "source": ".params = parse_ruby_hash!(\"{my_param => 123}\")"
    }
  },
```

### Expected Behavior

Should convert the hash to `"params": {"my_param":123}`

### Actual Behavior

Fails with the following error
```
WARN vector::internal_events::remap: Mapping failed with event. error="function call error for \"parse_ruby_hash\" at (270:307): 0: at line 1, in Tag:\n{my_param => 123}\n   ^\n\n1: at line 1, in map:\n{my_param => 123}\n^\n\n" internal_log_rate_secs=30
```

### PR DESCRIPTION
**Pull request by jdrouet**
Fixes #8872

### CODE REVIEW

File: lib/vrl/stdlib/src/parse_ruby_hash.rs [hunk 1]
```diff
@@ -109,36 +140,57 @@ fn parse_nil<'a, E: ParseError<&'a str>>(input: &'a str) -> IResult<&'a str, Val
...
 
+fn parse_simple_key<T, E: ParseError<T>>(input: T) -> IResult<T, T, E>
+where
+    T: InputTakeAtPosition,
+    <T as InputTakeAtPosition>::Item: AsChar,
+{
+    input.split_at_position1_complete(
+        |item| {
+            let c = item.as_char();
+            !c.is_alphanum() && c.as_char() != '_'
```
Comment (pablosichert) [inline lib/vrl/stdlib/src/parse_ruby_hash.rs:157]: Isn't `c` a `char` here after the call to `item.as_char()`?

```suggestion
            let c = item.as_char();
            !c.is_alphanum() && c != '_'
```

Comment (pablosichert) [inline lib/vrl/stdlib/src/parse_ruby_hash.rs:157]: Looks like symbol keys in ruby hashes don't allow starting with a digit:

```bash
$ irb
irb(main):001:0> foo = { 1: 123 }
Traceback (most recent call last):
        3: from /usr/bin/irb:23:in `<main>'
        2: from /usr/bin/irb:23:in `load'
        1: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
SyntaxError ((irb):1: syntax error, unexpected ':', expecting =>)
foo = { 1: 123 }
         ^
```

Starting with a character or underscore is fine

File: lib/vrl/stdlib/src/parse_ruby_hash.rs [hunk 2]
```diff
@@ -109,36 +140,57 @@ fn parse_nil<'a, E: ParseError<&'a str>>(input: &'a str) -> IResult<&'a str, Val
...
-            preceded(char('\"'), cut(terminated(parse_str::<'a, E>, char('\"')))),
-            |value| Bytes::copy_from_slice(value.as_bytes()),
-        ),
+        map(alt((parse_str('"'), parse_str('\''))), |value| {
+            Bytes::copy_from_slice(value.as_bytes())
+        }),
     )(input)
 }
 
+fn parse_simple_key<T, E: ParseError<T>>(input: T) -> IResult<T, T, E>
```
Comment (pablosichert) [inline lib/vrl/stdlib/src/parse_ruby_hash.rs:149]: I'd rename this to `parse_symbol_key` to match Ruby's terminology: https://ruby-doc.org/core-2.5.1/Hash.html

File: lib/vrl/stdlib/src/parse_ruby_hash.rs [hunk 3]
```diff
@@ -232,9 +289,49 @@ mod tests {
...
+        let result = result.as_object().unwrap();
+        assert!(result.get("with-dash").unwrap().is_bytes());
+    }
+
+    #[test]
+    fn test_parse_quote() {
+        let result = parse(r#"{ "with'quote" => "and\"double\"quote" }"#).unwrap();
+        assert!(result.is_object());
+        let result = result.as_object().unwrap();
+        assert!(result.get("with'quote").unwrap().is_bytes());
```
Comment (pablosichert) [inline lib/vrl/stdlib/src/parse_ruby_hash.rs:329]: I think it would be worth asserting on the value as well here, instead of checking for `is_bytes` only. Especially in the case of `and"double"quote`, but I would also match the value in the other test cases.

**Review by pablosichert — COMMENTED** [review]
Looks very good! I just got some small remarks.

File: lib/vrl/stdlib/src/parse_ruby_hash.rs (hunk 1 above)
Comment (pablosichert) [reply lib/vrl/stdlib/src/parse_ruby_hash.rs:157]: Weird, `foo = { 1 => 123 }` seems to be valid, though. (Note the `=>` vs `:`)

**Review by JeanMertz — CHANGES_REQUESTED** [review]
Nice!

There's still some issues to solve, but I think we're close 👌

File: lib/vrl/stdlib/src/parse_ruby_hash.rs (hunk 1 above)
Comment (pablosichert) [reply lib/vrl/stdlib/src/parse_ruby_hash.rs:157]: Ah, the comment from @JeanMertz contains the explanation: https://github.com/timberio/vector/pull/8956#discussion_r698425097.

The part before `=>` is evaluated, so `1` resolves to the literal value `1` and is not a symbol.

File: lib/vrl/stdlib/src/parse_ruby_hash.rs [hunk 4]
```diff
@@ -232,9 +289,49 @@ mod tests {
...
+        assert!(result.get("42").unwrap().is_bytes());
+    }
+
+    #[test]
+    fn test_parse_key_colon() {
+        let result = parse(r#"{ :colon => "hello world" }"#).unwrap();
+        assert!(result.is_object());
+        let result = result.as_object().unwrap();
+        assert!(result.get(":colon").unwrap().is_bytes());
+    }
```
[the remark this answers is not in the document]
Comment (spencergilbert) [reply lib/vrl/stdlib/src/parse_ruby_hash.rs:306]: I love how many ways Ruby gives you to do the same thing /s

[the remark this answers is not in the document]
Comment (jdrouet) [reply lib/vrl/stdlib/src/parse_ruby_hash.rs:306]: I didn't really appreciate Ruby until now, I think I'm fixed now 🤔

File: lib/vrl/stdlib/src/parse_ruby_hash.rs (hunk 1 above)
Comment (jdrouet) [reply lib/vrl/stdlib/src/parse_ruby_hash.rs]: to follow @JeanMertz 's comment `since we're not an actual Ruby parser`, should we care about `{ 1: 234 }`? If it's not valid, then we should not have it. If we have it, we'll have `{ "1": "234" }` 🤷

File: lib/vrl/stdlib/src/parse_ruby_hash.rs [hunk 5]
```diff
@@ -109,50 +140,88 @@ fn parse_nil<'a, E: ParseError<&'a str>>(input: &'a str) -> IResult<&'a str, Val
...
+        let c = item.as_char();
+        c.is_alphanum() || c == '_'
+    })(input)
+}
+
+fn parse_colon_key<'a, E: ParseError<&'a str>>(input: &'a str) -> IResult<&'a str, &'a str, E> {
+    map(consumed(preceded(char(':'), parse_symbol_key)), |res| res.0)(input)
+}
+
+fn parse_key_arrow_hash<'a, E: HashParseError<&'a str>>(
```
Comment (JeanMertz) [inline lib/vrl/stdlib/src/parse_ruby_hash.rs:165]: Also known as the "[hash rocket](https://web.archive.org/web/20130909062027/http://peepcode.com/blog/2011/rip-ruby-hash-rocket-syntax)".

Comment (jdrouet) [reply lib/vrl/stdlib/src/parse_ruby_hash.rs:165]: From where I come from it's `fat arrow` 🤷‍♂️

File: lib/vrl/stdlib/src/parse_ruby_hash.rs (hunk 1 above)
Comment (jdrouet) [reply lib/vrl/stdlib/src/parse_ruby_hash.rs]: I think my explanation was not clear enough 😅 
Vector is not a Ruby parser but a log parser (in that case). So should we really consider all the cases that it shouldn't parse considering those should not happen? If a ruby program generates `{ foo => "bar" }` should we throw an error or parse it? Would this even happen?
Should we increase the code complexity of the code base and handle all those little cases that should probably not appear in the logs?
IMO, we should parse it, even if Ruby doesn't, `{ foo => "bar" }` generating the `{ "foo": "bar" }` equivalent.
@JeanMertz does this seem ok with you?

**Review by JeanMertz — APPROVED** [review]
LGTM. We can iterate on this further as cases arise
