### PR TITLE
fix(remap): re-enable @ in identifiers.

### LINKED ISSUE #6489: allow `@` in field names
This worked before, but got removed in the recent parser refactor.

We want this to work:

```
.@timestamp = now()
```

### PR DESCRIPTION
**Pull request by FungusHumungus**
Closes #6489 

This allows `@` in identifiers such as:

```
.@timestamp = now()
```

Signed-off-by: Stephen Wakely <stephen.wakely@datadoghq.com>

### CODE REVIEW

**Review by JeanMertz — CHANGES_REQUESTED** [review]
Sweet, thanks @FungusHumungus.

Two points we might want to address:

1. Let's add this change to our UI tests to make sure it works across the board, and not just in the lexer.

2. I propose we _only_ allow `@` in external paths, _not_ in any other places that accept identifiers (e.g. function and variable names). This will require a bit more work, but I believe it's a good change to make.

**Comment by FungusHumungus** [comment]
Ok, have added a new `PathField` lexer token for any identifiers that contain a `@`. This is only accepted by queries.

File: lib/vrl/parser/src/lex.rs [hunk 1]
```diff
@@ -1069,7 +1074,7 @@ impl<'input> Lexer<'input> {
 // -----------------------------------------------------------------------------
 
 fn is_ident_start(ch: char) -> bool {
-    matches!(ch, 'a'..='z')
+    matches!(ch, '@' | 'a'..='z')
```
Comment (JeanMertz) [inline lib/vrl/parser/src/lex.rs:1077]: I'm surprised this doesn't break anything else. Given that we now have different definitions of identifiers.

But, if all tests are still passing, then we should be good.

**Review by JeanMertz — APPROVED** [review]

File: lib/vrl/parser/src/lex.rs (hunk 1 above)
Comment (FungusHumungus) [reply lib/vrl/parser/src/lex.rs:1077]: > I'm surprised this doesn't break anything else. Given that we now have different definitions of identifiers.

The differences are handled [here](https://github.com/timberio/vector/blob/17d0fa0027d3594b825506193acea79c04f29c94/lib/vrl/parser/src/lex.rs#L429). The lexer for identifiers doesn't know what type of identifier it is parsing until it has finished, so here we just have to accept all possible characters and then differentiate at the end..

Comment (JeanMertz) [reply lib/vrl/parser/src/lex.rs:1077]: That's partially true, but we also delegate to this function in `is_ident_continue` and `is_query_start`, which are used in other places. But I have nothing that comes to mind that would break because of this, and given that the tests are green, I don't see a reason to change this 👍
