### PR TITLE
fix(networking): Handle unexpected errors in ARC controller

### LINKED ISSUE #5259: Do not crash on unhandled error at the adaptive concurrency controller
This was reported in Discord: https://ptb.discord.com/channels/742820443487993987/759444241637179452/781818400065323008

Vector crashes if it encounters a certain network condition due to incorrect error handling.

Vector logs (no sensitive info):

```
Xxx xx xx:xx:xx.xxA DEBUG hyper::proto::h1::conn: parse error (connection closed before message completed) with 0 bytes
Xxx xx xx:xx:xx.xxA DEBUG hyper::proto::h1::dispatch: read_head error: connection closed before message completed
Xxx xx xx:xx:xx.xxA DEBUG http: vector::internal_events::http_client: HTTP error. error=connection closed before message completed
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: Unhandled error response! CallRequest { source: hyper::Error(IncompleteMessage) }', src/sinks/util/auto_concurrency/controller.rs:246:21
Xxx xx xx:xx:xx.xxA ERROR sink{component_kind="sink" component_name=sink_splunk_hec component_type=splunk_hec}: vector::topology: An error occurred that vector couldn't handle.
Xxx xx xx:xx:xx.xxB ERROR transform{component_kind="transform" component_name=reduce component_type=reduce}: vector::buffers: Sender error. error=send failed because receiver is gone
```

Check Discord for more info.

Looks like this corresponds to the following code:

https://github.com/timberio/vector/blob/6dae0b54b2a9066a40d7ee712820f971b5916868/src/sinks/util/adaptive_concurrency/controller.rs#L238-L249

cc @bruceg

### PR DESCRIPTION
**Pull request by bruceg**
Signed-off-by: Bruce Guenter <bruce@timber.io>

Closes #5259

### CODE REVIEW

**Review by MOZGIII — APPROVED** [review]
I was thinking about a fix just like this, looks good!

File: src/sinks/util/adaptive_concurrency/controller.rs [hunk 1]
```diff
@@ -243,7 +243,12 @@ where
                 } else if error.downcast_ref::<Elapsed>().is_some() {
                     true
                 } else {
-                    unreachable!("Unhandled error response! {:?}", error)
+                    warn!(
```
Comment (jszwedko) [inline src/sinks/util/adaptive_concurrency/controller.rs:246]: Would it make sense to emit an event here for this?

**Review by jszwedko — APPROVED** [review]
This seems ok as a quick fix, but should we add explicit handling of `hyper` errors? https://docs.rs/hyper/0.13.9/hyper/struct.Error.html

**Comment by bruceg** [comment]
> This seems ok as a quick fix, but should we add explicit handling of `hyper` errors? [docs.rs/hyper/0.13.9/hyper/struct.Error.html](https://docs.rs/hyper/0.13.9/hyper/struct.Error.html)

I initially had that, but pulled it. However, it would make sense to handle them separately since they are no longer unexpected.

File: src/sinks/util/adaptive_concurrency/controller.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/util/adaptive_concurrency/controller.rs:246]: I don't think so, as it's more of a programming error than an operational error, but I could be convinced otherwise.

Comment (jszwedko) [reply src/sinks/util/adaptive_concurrency/controller.rs:252]: Gotcha, I see. Maybe we could print a message asking them to file a bug then? I've seen that for some other programs where "unreachable" code is reached.

Comment (binarylogic) [reply src/sinks/util/adaptive_concurrency/controller.rs:252]: @jszwedko this is blocking 0.11. Can we defer this and open an issue?

Comment (jszwedko) [reply src/sinks/util/adaptive_concurrency/controller.rs:252]: That's fine with me :+1:
