### PR TITLE
fix(kubernetes_logs source): Always use file checkpoints if they exist

### LINKED ISSUE #6761: Checkpointing doesn't work on kubernetes_logs after upgrading to 0.12.1
### Vector Version

```
0.12.1 (also appears on 0.12.0) installed on Kubernetes via Helm.
```

### Vector Configuration File

```toml
  managed.toml: |
    # Configuration for vector.
    # Docs: https://vector.dev/docs/

    data_dir = "/vector-data-dir"

    [api]
      enabled = false
      address = "0.0.0.0:8686"
      playground = true

    [log_schema]
      host_key = "host"
      message_key = "message"
      source_type_key = "source_type"
      timestamp_key = "timestamp"

    # Ingest logs from Kubernetes.
    [sources.kubernetes_logs]
      type = "kubernetes_logs"

    # Capture the metrics from the host.
    [sources.host_metrics]
      type = "host_metrics"


    # Emit internal Vector metrics.
    [sources.internal_metrics]
      type = "internal_metrics"

    # Expose metrics for scraping in the Prometheus format.
    [sinks.prometheus_sink]
      address = "0.0.0.0:9090"
      inputs = ["internal_metrics", "host_metrics"]
      type = "prometheus"


    [sinks.stdout]
      encoding = "json"
      inputs = ["kubernetes_logs"]
      target = "stdout"
      type = "console"

```

### Expected Behavior

Log files that were being watched by Vector continued sinking from checkpoints (i.e. from last sinked lines before upgrade&restart). Should be messages about resuming to watch log files in Vector logs.

### Actual Behavior

Vector started sinking log files from the beginning. There are messages about vector finding new files to watch, although they were already watched before upgrade. Vector also starts to watch files from the beginning as if they were new after restarting its pod.

```
Mar 15 10:24:22.771  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info"
 Mar 15 10:24:22.771  INFO vector::sources::host_metrics: PROCFS_ROOT is set in envvars. Using custom for procfs. custom="/host/proc"
 Mar 15 10:24:22.771  INFO vector::sources::host_metrics: SYSFS_ROOT is set in envvars. Using custom for sysfs. custom="/host/sys"
 Mar 15 10:24:22.772  INFO vector::app: Loading configs. path=[("/etc/vector/managed.toml", None)]
 Mar 15 10:24:22.779  INFO vector::sources::kubernetes_logs: Obtained Kubernetes Node name to collect logs for (self). self_node_name="<redacted>"
 Mar 15 10:24:22.792  INFO vector::topology: Running healthchecks.
 Mar 15 10:24:22.792  INFO vector::topology: Starting source. name="internal_metrics"
 Mar 15 10:24:22.792  INFO vector::topology: Starting source. name="kubernetes_logs"
 Mar 15 10:24:22.792  INFO vector::topology: Starting source. name="host_metrics"
 Mar 15 10:24:22.792  INFO vector::topology: Starting sink. name="stdout"
 Mar 15 10:24:22.792  INFO vector::topology: Starting sink. name="prometheus_sink"
 Mar 15 10:24:22.793  INFO vector: Vector has started. version="0.12.1" git_version="v0.12.1" released="Fri, 12 Mar 2021 21:27:28 +0000" arch="x86_64"
 Mar 15 10:24:22.793  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
 Mar 15 10:24:22.811  INFO vector::topology::builder: Healthcheck: Passed.
 Mar 15 10:24:22.811  INFO vector::topology::builder: Healthcheck: Passed.
 Mar 15 10:24:22.829  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: file_source::checkpointer: Loaded checkpoint data.
 Mar 15 10:25:24.317  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: vector::internal_events::file::source: Found new file to watch. path=<redacted>
 Mar 15 10:25:24.318  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: vector::internal_events::file::source: Found new file to watch. path=<redacted>
 Mar 15 10:25:24.318  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: vector::internal_events::file::source: Found new file to watch. path=<redacted>
 Mar 15 10:25:24.318  INFO source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}:file_server: vector::internal_events::file::source: Found new file to watch. path=/<redacted>
```

It looks like checkpoints.json file is being updated and read normally by vector according to stat.

### PR DESCRIPTION
**Pull request by jszwedko**
Closes #6761 

The `kubernetes_logs` source exposes a `PathProvider` that breaks one of
the `FileServer`s assumptions that all available files will be listed at
Vector startup time. Instead, the files are only returned once the k8s
metadata is available to the `kubernetes_logs` source. This caused the
`FileServer` to ignore any checkpoints that existed for these files.

As a short-term fix, we just always use the checkpoint, if available,
for any new files that are seen. This fixes the case for the
`kubernetes_logs` source where they are seen as "new" after start-up.

https://github.com/timberio/vector/pull/6564 exists to test this
behavior, but it seems to pass even without this change, so that test
will need to be updated. I did test it out locally though.

Thanks to @lukesteensen for talking this one through!

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

File: lib/file-source/src/file_server.rs [hunk 1]
```diff
@@ -392,24 +392,30 @@ where
...
+            self.read_from
         } else {
             // Always read new files that show up while we're running from the beginning. There's
             // not a good way to determine if they were moved or just created and written very
             // quickly, so just make sure we're not missing any data.
             ReadFrom::Beginning
         };
 
+        // Always prefer the stored checkpoint unless the user has opted out.
+        // Previously, the checkpoint was only loaded for new files when Vector wast started up,
```
Comment (JeanMertz) [inline lib/file-source/src/file_server.rs:405]:
```suggestion
        // Previously, the checkpoint was only loaded for new files when Vector was started up,
```

**Review by JeanMertz — APPROVED** [review]
Makes sense, and the follow-up tasks are well documented in #7139 👍

**Review by lukesteensen — APPROVED** [review]
