### PR TITLE
fix(reduce transform): improve array handling

### LINKED ISSUE #3074: bug: Reduce transform has unexpected behavior on arrays
Given the file `test.json` with content:

```json
{ "operations": ["insert", "select"] }
{ "operations": ["select"] }
{ "operations": ["select"] }
{ "operations": ["select"] }
{ "operations": ["select"] }
{ "operations": ["select"] }
{ "operations": ["select"] }
{ "operations": ["drop"], "transaction_state": "commit" }
```

And the configuration of:

```toml
data_dir = "var"

[sources.database_file]
  type = "file"
  include = ["test.json"]


[transforms.database_log]
  type = "json_parser"
  inputs = ["database_file"]

[transforms.reducer]
  type = "reduce"
  inputs = ["database_log"]
  merge_strategies."operations" = "concat"
  ends_when.type = "check_fields"
  ends_when."transaction_state.eq" = "commit"

[sinks.sink0]
  inputs = ["reducer"]
  type = "console"
  encoding = "json"
```

On latest main branch checkout, seems to produce unexpected output.

```bash
hoverbear@OBSIDIAN:/git/timberio/vector$ ./target/debug/vector --config test.toml 
Jul 15 13:07:36.188  INFO vector: Log level "info" is enabled.
Jul 15 13:07:36.191  INFO vector: Loading configs. path=["test.toml"]
Jul 15 13:07:36.204  INFO vector: Vector is starting. version="0.10.0" git_version="v0.9.0-341-g6358cac" released="Mon, 13 Jul 2020 20:39:08 +0000" arch="x86_64"
Jul 15 13:07:36.205  INFO vector::topology: Running healthchecks.
Jul 15 13:07:36.205  INFO vector::topology: Starting source "database_file"
Jul 15 13:07:36.205  INFO vector::topology::builder: Healthcheck: Passed.
Jul 15 13:07:36.206  INFO vector::topology: Starting transform "database_log"
Jul 15 13:07:36.206  INFO vector::topology: Starting transform "reducer"
Jul 15 13:07:36.206  INFO source{name=database_file type=file}: vector::sources::file: Starting file server. include=["test.json"] exclude=[]
Jul 15 13:07:36.206  INFO vector::topology: Starting sink "sink0"
Jul 15 13:07:36.208  INFO source{name=database_file type=file}:file_server: file_source::file_server: Found file to watch. path="test.json" file_position=0
{"file":"test.json","host":"OBSIDIAN","operations":["insert","select"],"source_type":"file","timestamp":"2020-07-15T20:07:36.223375960Z","timestamp_end":"2020-07-15T20:07:36.224779276Z","transaction_state":"commit"}
```

Expected output should have the final line as :

```json
{"file":"test.json","host":"OBSIDIAN","operations":["insert","select","select","select","select","select","select","select","drop"],"source_type":"file","timestamp":"2020-07-15T20:07:36.223375960Z","timestamp_end":"2020-07-15T20:07:36.224779276Z","transaction_state":"commit"}
```

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #3074 

Two bugs fixed here:

1. Using `all_fields` instead of `into_iter` gaves us paths instead of keys, so thing like arrays and objects would not get strategized correctly.
2. Special casing arrays when constructing the `ArrayMerger` meant that the initial array would be flattened in the result but subsequent additions would not.

### CODE REVIEW

File: src/transforms/reduce/mod.rs [hunk 1]
```diff
@@ -77,12 +77,11 @@ impl ReduceState {
     fn new(e: LogEvent, strategies: &IndexMap<String, MergeStrategy>) -> Self {
         Self {
             stale_since: Instant::now(),
-            // TODO: all_fields alternative that consumes
```
Comment (Hoverbear) [inline src/transforms/reduce/mod.rs:80]: As it was foretold.

File: src/transforms/reduce/mod.rs [hunk 2]
```diff
@@ -493,4 +493,59 @@ identifier_fields = [ "request_id" ]
...
         );
     }
+
+    #[test]
+    fn arrays() {
+        let mut reduce = toml::from_str::<ReduceConfig>(
+            r#"
+identifier_fields = [ "request_id" ]
+
+merge_strategies.foo = "array"
```
Comment (Hoverbear) [inline src/transforms/reduce/mod.rs:503]: How about one for concat?

**Comment by lukesteensen** [comment]
> I think this needs to consider the concat strategy as well!

I actually started down this path and backed out because it seemed slightly out of scope. The main thing that stopped me was that the current `concat` collects into a `BytesMut` and adding a second array "flavor" of concat adds a lot of edge cases where behavior will depend on the type of the first value seen, etc. We can totally do it, it just started to look more complex than I initially assumed.

**Comment by Hoverbear** [comment]
Ok that's fine with me!

**Comment by lukesteensen** [comment]
Just kidding, it wasn't that bad. Just pushed an implementation.
