### PR TITLE
s3: Add filename extension option and fix trailing slash

### LINKED ISSUE #582: Ability to specify file extension for `aws_s3` sink
Hi!

I'm planning to use Vector as a way to continuously write content of a Kafka topic to S3 (using [kafkacat](https://github.com/edenhill/kafkacat) and `stdin` source).

I would like the output objects to have extension `.jsonl.gz`, but it seems to be not possible to change the extension from default `.log.gz`.

Thanks for the amazing piece of software, by the way!

### PR DESCRIPTION
**Pull request by LucioFranco**
Closes #582, #517

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
Just a heads up, this needs a changelog addition as well as a docs update.

File: src/sinks/aws_s3.rs [hunk 1]
```diff
@@ -426,6 +465,7 @@ mod integration_tests {
 
         let keys = get_keys(prefix.unwrap());
         assert_eq!(keys.len(), 1);
+        println!("keys: {:?}", keys);
```
Comment (binarylogic) [inline src/sinks/aws_s3.rs]: Do we need this?
