### PR TITLE
fix(docker_logs source): Fix `retry_backoff_secs`

### LINKED ISSUE #7272: vector sends thousands of log lines when it cannot read the logs from docker containers
### Vector Version

```
vector 0.13.0 (v0.13.0 x86_64-unknown-linux-gnu 2021-04-21)
```
Docker version:
`Docker version 20.10.5, build 55c4c88`

### Vector Configuration File

```toml
# Read logs from Docker API and Send to loki sink

[sources.docker-local]
  type = "docker_logs"
  docker_host = "/var/run/docker.sock"
  exclude_containers = []

  # Identify zero-width space as first line of a multiline block.
  multiline.condition_pattern = '^\x{200B}' # required
  multiline.mode = "halt_before" # required
  multiline.start_pattern = '^\x{200B}' # required
  multiline.timeout_ms = 1000 # required, milliseconds

[sinks.loki]
  # General
  type = "loki" # required
  inputs = ["docker-local"] # required
  endpoint = "https://logs.example.com:443" # required


  # Auth
  auth.strategy = "basic" # required
  auth.user = "" # required
  auth.password = "" # required

  # Encoding
  encoding.codec = "json" # required

  # Healthcheck
  healthcheck.enabled = true # optional, default


  # Labels
  labels.forwarder = 'vector'
  labels.host = '{{ host }}'
  labels.container_name = '{{ container_name }}'
  labels.compose_service = '{{ label.com\.docker\.compose\.service }}'
  labels.compose_project = '{{ label.com\.docker\.compose\.project }}'
  labels.source = '{{ stream }}'
  labels.category = 'dockerlogs'

```

### Expected Behavior

* When vector cannot read docker logs, it should send minimal error message. 
* the error messages/ retries should be rate limited. 
* vector should log the problem on its own log

### Actual Behavior

* Vector sends more than 7000 lines of error message per minute per container, including all container metadata
* Vector uses a lot of cpu resources in that case for processing/pushing all those messages

### Example Data

Example message (without the metadata that is also sent):
```
�Error grabbing logs: error getting log reader: LogDriver.ReadLogs: logger does not exist for 888216b36e1adf224aea65ef1e6ffdcb67cf4697cf81b3f8bee402accc6cb32d
```
Full example message (json):
```json
{
  "container_created_at": "2021-02-01T19:33:25.594887482Z",
  "container_id": "b15818d4115f46bde077f6f7c1e868c52616c4b552a1fe02bd812fe5bb752627",
  "container_name": "webproxy_nginx-web",
  "host": "dev2",
  "image": "nginx:alpine",
  "label.com.docker.compose.config-hash": "9f8bf9324321705d7a74f7ac9201b605ec741019540455cf295a16cea54c2cad",
  "label.com.docker.compose.container-number": "1",
  "label.com.docker.compose.oneoff": "False",
  "label.com.docker.compose.project": "webproxy",
  "label.com.docker.compose.project.config_files": "/container/webproxy/docker-compose.yml",
  "label.com.docker.compose.project.working_dir": "/container/webproxy",
  "label.com.docker.compose.service": "nginx-web",
  "label.com.docker.compose.version": "1.28.2",
  "label.com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy": "true",
  "label.maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
  "message": "\u0003\u0000\u0000\u0000\u0000\u0000\u0000�Error grabbing logs: error getting log reader: LogDriver.ReadLogs: logger does not exist for b15818d4115f46bde077f6f7c1e868c52616c4b552a1fe02bd812fe5bb752627\n",
  "source_type": "docker",
  "stream": "console"
}
```

Full message as screenshot from grafana explore view of loki

grafik

### Additional Context

The log driver in use was the loki docker log driver which sometimes got stuck. that's why we want to replace it with vector ;-)

But the problem could also be happening with other cases where vector cannot read logs.

### PR DESCRIPTION
**Pull request by ktff**
Close #7272 

`retry_backoff_secs` option wasn't working properly so `docker` source immediately tried to reconnect.

### CODE REVIEW

**Comment by jszwedko** [comment]
Nice, thanks @ktff !

I tried this out and now I see logs like:

```
Jul 08 18:33:56.290  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:33:56.292 ERROR vector::internal_events::docker_logs: Docker engine is not using either the `jsonfile` or `journald`
                logging driver. Please enable one of these logging drivers
                to get logs from the Docker daemon. error=DockerResponseServerError { status_code: 501, message: "{\"message\":\"configured logging driver does not support reading\"}\n" } container_id="897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a" internal_log_rate_secs=10
Jul 08 18:33:56.292  INFO vector::internal_events::docker_logs: Stopped watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:33:58.297  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:33:58.299 ERROR vector::internal_events::docker_logs: Internal log [Docker engine is not using either the `jsonfile` or `journald`
                logging driver. Please enable one of these logging drivers
                to get logs from the Docker daemon.] is being rate limited.
Jul 08 18:33:58.299  INFO vector::internal_events::docker_logs: Stopped watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:34:00.304  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:34:00.306  INFO vector::internal_events::docker_logs: Stopped watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:34:02.311  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:34:02.319  INFO vector::internal_events::docker_logs: Stopped watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:34:04.330  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:34:04.336  INFO vector::internal_events::docker_logs: Stopped watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
Jul 08 18:34:06.342  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=897bb5fc35dff619cb63a7fdc44d9bab08e477bb2d92a72510f1081fc6e7b65a
```

They are thankfully much less frequent, but it is a bit award that the error one is rate limited and then we end up seeing a bunch of logs about it starting and stopping watching for a particular container.

I'm wondering if we should, when we encounter this specific `501 Not Implemented` error if we shouldn't just log once and then never try to fetch that container again since it is never going to be successful. What would you think?

**Comment by spencergilbert** [comment]
> ` 501 Not Implemented` can be a transient error. One scenario is that the log driver is replaced at a later time.

Can you replace the log driver of a running container? I was under the impression that required a new container.

**Comment by ktff** [comment]
@spencergilbert 

> Can you replace the log driver of a running container? I was under the impression that required a new container.

It would seem so, but there are other scenarios that can return this error as noted by [this comment](https://github.com/timberio/vector/issues/7272#issuecomment-860874790).

**Comment by ktff** [comment]
Although I'm now questioning why are we trying to watch container which isn't running.

**Comment by ktff** [comment]
It is actually running during build, but the log driver isn't set, so 
> 501 Not Implemented can be a transient error.

holds.

**Comment by ktff** [comment]
The two failing checks are unrelated.

**Comment by jszwedko** [comment]
> > Or, at the least, ensure that we output the error message once for each read attempt such that we'd always see it following Started watching for container logs and before Stopped watching for container logs.
> 
> It can be done by removing the internal log rate for that error. Other way around doesn't guarantee the order. Besides that, we can increase backoff for this specific error up to some limit, like... 15 sec.

Makes sense, thanks! I'm fine with increasing the backoff and ensuring that the error message appears with the `start/stop` messages.

**Comment by pgassmann** [comment]
> It is actually running during build, but the log driver isn't set, so
> 
> > 501 Not Implemented can be a transient error.
> 
> holds.

@ktff I think it is safe to assume that the logging driver does not change during the lifetime of a container. (except that it could be force-removed).
Also during a docker build, the build container is a separate container to build the image, it does not become the final running container.

**Comment by ktff** [comment]
@pgassmann I see, then we can just forget those containers. That would stop us from retrying and logging all those logs. There is a chance of us picking up that container again which would result in another set of logs but it should be rare, while the opposite of remembering every single one of those containers seems wasteful. Thanks.

**Comment by ktff** [comment]
@jszwedko now the logs look like:
```
Jul 13 14:44:56.805  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=fa9cb2c67a8d96eb0570ba8fd4f055ac2886eb5770ac69304b0969e0084d1e72
Jul 13 14:44:56.810 ERROR vector::internal_events::docker_logs: 
                Docker engine is not using either the `jsonfile` or `journald`
                logging driver. Please enable one of these logging drivers
                to get logs from the Docker daemon. error=DockerResponseServerError { status_code: 501, message: "{\"message\":\"configured logging driver does not support reading\"}\n" } container_id="fa9cb2c67a8d96eb0570ba8fd4f055ac2886eb5770ac69304b0969e0084d1e72"
Jul 13 14:44:56.810  INFO vector::internal_events::docker_logs: Stopped watching for container logs. container_id=fa9cb2c67a8d96eb0570ba8fd4f055ac2886eb5770ac69304b0969e0084d1e72
```

which is reported just once.

**Comment by ktff** [comment]
@prognant this is ready for review.

**Review by jszwedko — APPROVED** [review]
This looks good to me and behaves like I expected.

I guess a test here would involve the `internal_logs` source which is a bit flakey to test right now since that is a global resource. I'm ok with it as-is.

File: src/sources/docker_logs.rs [hunk 1]
```diff
@@ -657,6 +669,12 @@ fn add_hostname(mut event: Event, host_key: &str, hostname: &Option<String>) ->
     event
 }
 
+#[derive(Copy, Clone, Debug, Eq, PartialEq)]
+enum Persistence {
```
Comment (bruceg) [inline src/sources/docker_logs.rs:673]: I suggest renaming this to something like `ErrorType`. The name `Persistence` doesn't indicate what is persisting, which led me to think it was about the container at first, not the error from a container.

File: src/sources/docker_logs.rs [hunk 2]
```diff
@@ -596,18 +601,24 @@ impl EventStreamBuilder {
...
-                        Err(())
+                        }
                     }
                 }
             })
-            .take_while(|v| ready(v.is_ok()))
+            .take_while(|v| {
+                error = v.as_ref().err().cloned();
+                ready(v.is_ok())
+            })
```
Comment (bruceg) [inline src/sources/docker_logs.rs:621]: Any chance of using something like `.last` to get the final error value instead of potentially repeatedly setting `error`?

Comment (ktff) [reply src/sources/docker_logs.rs:621]: Not that I see. But the current code should set it max once.

**Review by bruceg — APPROVED** [review]
