### PR TITLE
chore(ci): Fix feature dependencies

### LINKED ISSUE #4676: Failing component check: sources-syslog
Example failure: https://github.com/timberio/vector/runs/1282359821#step:7:1340

```
cargo check --tests --no-default-features --features sources-syslog
warning: unused import: `self::socket::*`
   --> src/internal_events/mod.rs:168:16
    |
168 | pub(crate) use self::socket::*;
    |                ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

warning: unused import: `self::socket::*`
   --> src/internal_events/mod.rs:168:16
    |
168 | pub(crate) use self::socket::*;
    |                ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
```

### LINKED ISSUE #4677: Failing component check sources-tls
```
warning: associated function is never used: `acceptor`
  --> src/tls/incoming.rs:25:19
   |
25 |     pub(crate) fn acceptor(&self) -> crate::tls::Result<SslAcceptor> {
   |                   ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `bind`
  --> src/tls/incoming.rs:39:25
   |
39 |     pub(crate) async fn bind(&self, addr: &SocketAddr) -> crate::tls::Result<MaybeTlsListener> {
   |                         ^^^^

warning: field is never read: `listener`
  --> src/tls/incoming.rs:52:5
   |
52 |     listener: TcpListener,
   |     ^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `acceptor`
  --> src/tls/incoming.rs:53:5
   |
53 |     acceptor: Option<SslAcceptor>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `accept`
  --> src/tls/incoming.rs:57:25
   |
57 |     pub(crate) async fn accept(&mut self) -> crate::tls::Result<MaybeTlsIncomingStream<TcpStream>> {
   |                         ^^^^^^

warning: associated function is never used: `into_accept`
  --> src/tls/incoming.rs:67:14
   |
67 |     async fn into_accept(
   |              ^^^^^^^^^^^

warning: associated function is never used: `accept_stream`
  --> src/tls/incoming.rs:73:19
   |
73 |     pub(crate) fn accept_stream(
   |                   ^^^^^^^^^^^^^

warning: variant is never constructed: `Accepting`
   --> src/tls/incoming.rs:111:5
    |
111 |     Accepting(BoxFuture<'static, Result<SslStream<S>, HandshakeError<S>>>),
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `new`
   --> src/tls/incoming.rs:136:19
    |
136 |     pub(super) fn new(
    |                   ^^^

warning: 9 warnings emitted

warning: associated function is never used: `acceptor`
  --> src/tls/incoming.rs:25:19
   |
25 |     pub(crate) fn acceptor(&self) -> crate::tls::Result<SslAcceptor> {
   |                   ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `bind`
  --> src/tls/incoming.rs:39:25
   |
39 |     pub(crate) async fn bind(&self, addr: &SocketAddr) -> crate::tls::Result<MaybeTlsListener> {
   |                         ^^^^

warning: field is never read: `listener`
  --> src/tls/incoming.rs:52:5
   |
52 |     listener: TcpListener,
   |     ^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `acceptor`
  --> src/tls/incoming.rs:53:5
   |
53 |     acceptor: Option<SslAcceptor>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `accept`
  --> src/tls/incoming.rs:57:25
   |
57 |     pub(crate) async fn accept(&mut self) -> crate::tls::Result<MaybeTlsIncomingStream<TcpStream>> {
   |                         ^^^^^^

warning: associated function is never used: `into_accept`
  --> src/tls/incoming.rs:67:14
   |
67 |     async fn into_accept(
   |              ^^^^^^^^^^^

warning: associated function is never used: `accept_stream`
  --> src/tls/incoming.rs:73:19
   |
73 |     pub(crate) fn accept_stream(
   |                   ^^^^^^^^^^^^^

warning: variant is never constructed: `Accepting`
   --> src/tls/incoming.rs:111:5
    |
111 |     Accepting(BoxFuture<'static, Result<SslStream<S>, HandshakeError<S>>>),
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: associated function is never used: `new`
   --> src/tls/incoming.rs:136:19
    |
136 |     pub(super) fn new(
    |                   ^^^

warning: 9 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
```

### LINKED ISSUE #4678: Failing component check sources-splunk_hec
```
warning: associated function is never used: `new`
  --> src/sources/util/http.rs:28:12
   |
28 |     pub fn new(code: StatusCode, message: String) -> Self {
   |            ^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `is_valid`
  --> src/sources/util/http.rs:87:12
   |
87 |     pub fn is_valid(&self, header: &Option<String>) -> Result<(), ErrorMessage> {
   |            ^^^^^^^^

warning: 2 warnings emitted

warning: associated function is never used: `new`
  --> src/sources/util/http.rs:28:12
   |
28 |     pub fn new(code: StatusCode, message: String) -> Self {
   |            ^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `is_valid`
  --> src/sources/util/http.rs:87:12
   |
87 |     pub fn is_valid(&self, header: &Option<String>) -> Result<(), ErrorMessage> {
   |            ^^^^^^^^
```

### PR DESCRIPTION
**Pull request by jszwedko**
Fixes #4678
Fixes #4677 
Fixes #4676

### CODE REVIEW

**Comment by jszwedko** [comment]
Converted to draft as I figured it'd be easier to just fix all of the failing checks at once.

**Review by jamtur01 — APPROVED** [review]
LGTM

**Comment by jszwedko** [comment]
I'm especially curious to get feedback on the sources-tls changes though. I ended up just making some pub(crate)s into pub so that it wouldn't complain that no one was using the methods when only this feature was built

Alternatively, I could see not including that feature in the component checks, instead only targeting source-*, sink-*, and transform-* features

**Comment by jszwedko** [comment]
I realized we were already filtering for component features in the check so I just rename `sources-tls` to `tls` to avoid it being built independently given it isn't actually a component.

File: src/tls/mod.rs [hunk 1]
```diff
@@ -7,13 +7,13 @@ use std::{fmt::Debug, net::SocketAddr, path::PathBuf};
 use tokio::net::TcpStream;
 use tokio_openssl::{HandshakeError, SslStream};
 
-#[cfg(feature = "sources-tls")]
+#[cfg(feature = "tls")]
 mod incoming;
```
Comment (FungusHumungus) [inline src/tls/mod.rs:11]: If `incoming` is behind the `flag`, would it make sense for `outgoing` to also be behind the flag?

**Review by bruceg — COMMENTED** [review]
This looks ok as is, though I wonder if this new `"tls"` flag isn't misnamed still, as it only appears to manage TLS for sources.

**Comment by bruceg** [comment]
This brings up a couple of bigger questions about feature flags for me, all (mostly?) out of scope for this issue:

* The pluralization of the `sources-*` flags bothers me semantically, and leaves no room to separate a "group" flag like `sources-tls` from an "component" flag like `sources-socket`. Changing this will of course break the component test script.

* Would we do better to separate internal dependency flags (like `tls`) from external component flags with a leading underscore or something similar? This particular flag is only set by having one or more sources that depend on TLS, and isn't particularly useful to put on the command line, but in other packages the `tls` flag would be used to enable support for TLS.

**Comment by jszwedko** [comment]
Merged this taking Bruce's review as a tacit approval :smile: to unblock master. Happy to make any follow up changes though.

@bruceg 

> This looks ok as is, though I wonder if this new "tls" flag isn't misnamed still, as it only appears to manage TLS for sources.

Yeah, I tend to agree that the feature is not well named. I'm almost inclined to just drop it even if it does mean that it'll be compiled for components that don't depend on those `tls` types. Or we could move the source specific TLS bits into `src/sources/util/tls.rs`.

>The pluralization of the sources-* flags bothers me semantically, and leaves no room to separate a "group" flag like sources-tls from an "component" flag like sources-socket. Changing this will of course break the component test script.

I agree, I'd also prefer the singular `source-*`.

> Would we do better to separate internal dependency flags (like tls) from external component flags with a leading underscore or something similar? This particular flag is only set by having one or more sources that depend on TLS, and isn't particularly useful to put on the command line, but in other packages the tls flag would be used to enable support for TLS.

:+1: I'm a fan of that.

File: src/tls/mod.rs (hunk 1 above)
Comment (jszwedko) [reply src/tls/mod.rs:11]: Sorry, I missed this comment earlier. I believe this feature is really only intended to be used by sources, hence the `incoming` module. Per Bruce's comment below, I think it might make sense to extract some of the source specific bits from this module and into `src/sources/util/tls.rs`.
