### PR TITLE
fix(metrics, sinks): Move normalization out of MetricsBuffer

### LINKED ISSUE #6312: Batch buffer handling PartitionBatchSink breaks conversion of metrics
The batch buffer interface, `trait Batch`, specifies a `fn fresh` which produces a new buffer from the current one, possibly retaining state. `BatchSink` calls this indirectly through `Batch::fresh_replace` when sending a batch. `PartitionBatchSink` never does, and instead simply drops the buffer when the partition is closed and recreates it when a new partition is opened. This leads to incorrect behavior for metrics that need their state retained between batches due to being converted from the opposite kind, which in turn will lead to converted metrics either not being transmitted or being emitted with incorrect values.

This is likely the cause of #5698, which led to #5922, or at least a contributing factor.

I see two possible solutions:

1. Maintain partition state between batches instead of dropping the partitions. This requires the fewest changes to metrics sinks but raises the possibility of a memory "leak" if there are an increasing number of partitions (ex partition by date, etc). 
2. Maintain the metric conversion state outside of the `PartitionBatchSink` (and so the `MetricsBuffer`). Much of the work for this is done through `trait MetricNormalize` but would  need to be moved out of the metrics batch buffer into each metric sink. This option is growing on me, and should be relatively straightforward with the Tower framework.

Identified by @tustvold in https://github.com/timberio/vector/pull/6251#discussion_r567476683

Blocks #6062

### PR DESCRIPTION
**Pull request by bruceg**
MetricsBuffer included a `state` component that was used to convert
metrics between absolute and incremental kinds. This relied on the batch
buffer never being dropped but rather just regenerated through
`Batch::fresh`. However, `PartitionBatchSink` never calls `fresh` but
rather generates a new batch for each partition and then just drops it.

This moves the state management out of the buffer and into a flat map
before the metrics enter the buffer.

Signed-off-by: Bruce Guenter <bruce@timber.io>

Closes #6312

### CODE REVIEW

File: src/sinks/util/buffer/metrics.rs [hunk 1]
```diff
@@ -148,23 +144,22 @@ impl<N: MetricNormalize> Batch for MetricsBuffer<N> {
...
+                MetricKind::Absolute => MetricEntry(item),
+                MetricKind::Incremental => {
+                    // Incremental metrics update existing entries, if present
+                    let entry = MetricEntry(item);
+                    self.metrics
+                        .take(&entry)
+                        .map(|mut existing| {
+                            existing.data.update(&entry.data);
+                            existing
+                        })
```
Comment (pablosichert) [inline src/sinks/util/buffer/metrics.rs:158]:
```suggestion
                        .for_each(|mut existing| {
                            existing.data.update(&entry.data);
                        })
```

File: src/sinks/datadog/metrics.rs [hunk 2]
```diff
@@ -187,13 +187,16 @@ impl SinkConfig for DatadogConfig {
...
+        let mut normalizer = MetricNormalizer::<DatadogMetricNormalize>::default();
 
         let svc_sink = PartitionBatchSink::new(svc, buffer, batch.timeout, cx.acker())
             .sink_map_err(|error| error!(message = "Fatal datadog metric sink error.", %error))
             .with_flat_map(move |event: Event| {
-                let ep = DatadogEndpoint::from_metric(&event);
-                stream::iter(Some(PartitionInnerBuffer::new(event, ep))).map(Ok)
+                stream::iter(normalizer.apply(event).map(|event| {
+                    let ep = DatadogEndpoint::from_metric(&event);
+                    Ok(PartitionInnerBuffer::new(event, ep))
```
Comment (pablosichert) [inline src/sinks/datadog/metrics.rs:198]:
```suggestion
                    let endpoint = DatadogEndpoint::from_metric(&event);
                    Ok(PartitionInnerBuffer::new(event, endpoint))
```

File: src/sinks/util/buffer/metrics.rs [hunk 3]
```diff
@@ -350,18 +366,21 @@ mod test {
...
+        let mut buffer = MetricsBuffer::new(batch_size);
         let mut result = vec![];
 
-        for event in events {
-            match buffer.push(Event::Metric(event)) {
-                PushResult::Overflow(_) => panic!("overflowed too early"),
-                PushResult::Ok(true) => {
-                    result.push(buffer.fresh_replace().finish());
+        for metric in metrics {
+            if let Some(event) = normalizer.apply(Event::Metric(metric)) {
```
Comment (pablosichert) [inline src/sinks/util/buffer/metrics.rs:376]: Under which condition does this evaluate to `None`, and is no handling needed in that case?

**Review by pablosichert — APPROVED** [review]
LGTM.

Some small suggestions / questions.

File: src/sinks/util/buffer/metrics.rs (hunk 1 above)
Comment (bruceg) [reply src/sinks/util/buffer/metrics.rs:158]: Unless I mistyped it, that doesn't work. The return from `metrics.take` is an `Option` not an iterator.

File: src/sinks/datadog/metrics.rs (hunk 2 above)
Comment (bruceg) [reply src/sinks/datadog/metrics.rs:198]: I copied that naming over from the existing code, but you're right, the full name is better since I was rewriting the code anyways. Fixed.

File: src/sinks/util/buffer/metrics.rs (hunk 3 above)
Comment (bruceg) [reply src/sinks/util/buffer/metrics.rs:376]: The normalizer emits `None` if it absorbs the metric into its state. For example, when converting absolute metrics to incremental, the first metric in a series is used to set the state and so would return `None` here, and then each subsequent one would result in `Some(…)`.

File: src/sinks/util/buffer/metrics.rs (hunk 1 above)
Comment (pablosichert) [reply src/sinks/util/buffer/metrics.rs:158]: Whoops, missed that this is an `Option` 😄

File: src/sinks/util/buffer/metrics.rs (hunk 3 above)
Comment (pablosichert) [reply src/sinks/util/buffer/metrics.rs:376]: Thanks! I think we should add the explanation for the `Option` return type in a comment to the `MetricNormalizer::apply` and `MetricNormalize::apply_state` methods as well.

A follow up question, but I'm not sure if this applies to the same context of your answer: In the case of absolute -> incremental, wouldn't the first increment correspond to the absolute value?

Comment (bruceg) [reply src/sinks/util/buffer/metrics.rs:376]: Yes, better internal documentation is always a good idea. I'll add some.

The first increment corresponding to the absolute value only works if the previous value is assumed to be zero. That could introduce big spikes in the time series if it is not, though.

File: src/sinks/util/buffer/metrics.rs [hunk 4]
```diff
@@ -228,6 +230,10 @@ impl<N: MetricNormalize> MetricNormalizer<N> {
 /// source, the buffer will compare it's values with the previous known
 /// and calculate the delta.
 pub trait MetricNormalize {
+    /// Apply normalize the given `metric` using `state` to save any
```
Comment (pablosichert) [inline src/sinks/util/buffer/metrics.rs:233]:
```suggestion
    /// Apply normalizes the given `metric` using `state` to save any
```

File: src/sinks/util/buffer/metrics.rs (hunk 3 above)
Comment (pablosichert) [reply src/sinks/util/buffer/metrics.rs:382]: Does that mean that the metric provider should emit a `0` first if the first value indeed was supposed to be absolute?

I don't know too much about the context in which this buffer is used, this edge case just came up thinking about it.

Comment (pablosichert) [reply src/sinks/util/buffer/metrics.rs:382]: Just discussed with Bruce: This can indeed cause some janky behavior. If the first seed value would be emitted as increment, the metric would have some big jumps when Vector restarts. On the other hand, if it is simply ignored, values like "uptime seconds" could show inaccurate/misleading values when the seed value is not emitted.

Any solution to this is vastly out of scope for this PR, though.

**Review by lukesteensen — APPROVED** [review]
