### PR TITLE
enhancement(aws_cloudwatch_logs sink): Enforce age requirements

### LINKED ISSUE #1483: Ensure the `cloudwatch_logs` sink follows event requirements
Cloudwatch log's `PutLogEvents` endpoint has a few requirements that we should ensure we follow or enforce. Listed below are the main ones:

- [ ] None of the log events in the batch can be more than 2 hours in the future.
- [ ] None of the log events in the batch can be older than 14 days or older than the retention period of the log group.
- [x] The log events in the batch must be in chronological ordered by their timestamp
- [ ] A batch of log events in a single request cannot span more than 24 hours. Otherwise, the operation fails.

For the first two we should ensure that if a subset of the logs sent contains invalid logs that the valid ones are still accepted. In this case we don't need to change our implementation since rejected logs still count as a successful request.

The 3rd one, I am not totally sure how we should solve this but it seems like it wants us to sort them but that sounds a bit more expensive than what we may want to do?

This last one can only happen when you hit a break in logs such that you get some logs that are older and some that are younger, this might happen when you restart vector after a long crash. This can't happen normally due to batch timeouts. This might be something we want to enforce but sounds like it may introduce some complex logic to where we would need to split outgoing batches into two separate ones.

### PR DESCRIPTION
**Pull request by ktff**
Closes #1483 

### Open questions
 - [x] Regarding 

    > or older than the retention period of the log group

    part of the second constraint I'm unsure in how to deal with it? 
    Actually implementing this would somewhat complicate the sink, for a case which would happen rarely. If this isn't added, in the worst case `aws` may drop that batch which would have a limited effect since we are splitting the batches into 24h pieces. And dropping older messages also shouldn't be a problem since there is already a precedent of dropping messages older than 14 days. (EDIT: filtering on 14day should be enough)

### CODE REVIEW

File: src/sinks/aws_cloudwatch_logs/request.rs [hunk 1]
```diff
@@ -169,15 +173,22 @@ impl Future for CloudwatchFuture {
 
                     let next_token = res.next_sequence_token;
 
-                    info!(message = "putting logs was successful.", ?next_token);
+                    if let Some(events) = self.events.take() {
+                        info!(message = "putting logs.", ?next_token);
```
Comment (binarylogic) [inline src/sinks/aws_cloudwatch_logs/request.rs:177]: Is this necessary? Or should it be moved to `debug`? Don't we already have request logs?

**Comment by binarylogic** [comment]
Thanks @ktff. Just confirming, performance-wise does anything jump out here that might reduce that?

File: src/sinks/aws_cloudwatch_logs/request.rs (hunk 1 above)
Comment (ktff) [reply src/sinks/aws_cloudwatch_logs/request.rs:177]: > Don't we already have request logs?

We have, but this will be called only in rare scenarios so I would like to make it clear when it happens, and I agree that `info` is too strong for this, `debug` would better fit it's purpose.

**Comment by ktff** [comment]
@binarylogic The `sort` we introduced in #2320 , which I just moved in this PR to another location, it could on larger batches. It helps that in most cases messages will be almost sorted.

Other than that, there is an additional passage over messages for splitting them into 24h batches, but I now see that we can optimize it and introduce a fast path for majority case.

**Comment by binarylogic** [comment]
Perfect, thanks!

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 2]
```diff
@@ -882,6 +899,86 @@ mod integration_tests {
...
+        let response = rt.block_on(client.get_log_events(request)).unwrap();
+
+        let events = response.events.unwrap();
+
+        let output_lines = events
+            .into_iter()
+            .map(|e| e.message.unwrap())
+            .collect::<Vec<_>>();
+
+        assert_eq!(output_lines, lines);
```
Comment (LucioFranco) [inline src/sinks/aws_cloudwatch_logs/mod.rs:979]: we should probably add a test that shows the output events to be less than what were sent to the sink?

File: src/sinks/aws_cloudwatch_logs/request.rs [hunk 3]
```diff
@@ -189,9 +200,39 @@ impl Client {
...
         sequence_token: Option<String>,
         mut log_events: Vec<InputLogEvent>,
-    ) -> RusotoFuture<PutLogEventsResponse, PutLogEventsError> {
-        // Sort by timestamp
-        log_events.sort_by_key(|e| e.timestamp);
+    ) -> (
+        RusotoFuture<PutLogEventsResponse, PutLogEventsError>,
+        Option<Vec<InputLogEvent>>,
+    ) {
+        // We will only send events that happened in the 24h window since the oldest event.
```
Comment (LucioFranco) [inline src/sinks/aws_cloudwatch_logs/request.rs:207]: What is the reason for handling this logic here and not doing it all combined in the outer module?

Comment (ktff) [reply src/sinks/aws_cloudwatch_logs/request.rs:207]: At the time, it seemed like it would require the least amount of changes in this place. But, yes, we could handle this by pulling it back to the outer module and passing `Vec<Vec<InputLogEvent>>` to the future.

File: src/sinks/aws_cloudwatch_logs/mod.rs (hunk 2 above)
Comment (ktff) [reply src/sinks/aws_cloudwatch_logs/mod.rs:979]: This does test that. The `lines` only contains that what should pass through the filters.

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 4]
```diff
@@ -314,16 +315,29 @@ impl Service<Vec<Event>> for CloudwatchLogsSvc {
 
     fn call(&mut self, req: Vec<Event>) -> Self::Future {
         if self.token_rx.is_none() {
-            let events = req
+            // We need to take into account the flight time from here to aws servers,
+            // so we are reducing timestamp acceptable range from both sides
+            // for this amount.
+            let buffer_time = Duration::minutes(1);
```
[the remark this answers is not in the document]
Comment (ktff) [reply src/sinks/aws_cloudwatch_logs/mod.rs:321]: No, just a speculation and defensive programming on my side since I'm not sure how strictly does aws check for this.  

> two hours is the buffer 

Now I see, yes this is not needed, I'll remove it.

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 5]
```diff
@@ -314,16 +315,29 @@ impl Service<Vec<Event>> for CloudwatchLogsSvc {
...
                     self.encoding.apply_rules(&mut e);
                     e
                 })
                 .map(|e| e.into_log())
                 .map(|e| self.encode_log(e))
+                .filter(|e| age_range.contains(&e.timestamp))
                 .collect::<Vec<_>>();
 
+            // Sort by timestamp
+            events.sort_by_key(|e| e.timestamp);
```
[the remark this answers is not in the document]
Comment (ktff) [reply src/sinks/aws_cloudwatch_logs/mod.rs:339]: True. I missed this even though the same optimization was applied to the 24/h filter.

[the remark this answers is not in the document]
Comment (ktff) [reply src/sinks/aws_cloudwatch_logs/mod.rs:339]: After working on this for a bit, I don't think it's worth it. We can't avoid iterating since we need to transform `Event` to `InputLogEvent`. While yes we could almost completely avoid cost of the filter, it's just 2 integer comparisons and `&&` for each event, we would need to add additional complexity which would have a negative performance for smaller event counts, while when we do have something to filter out from the start of the `Vec` we would need to shift everything else. While the current solution, when we do have something to filter, has benefit of reducing number of events to be sorted. 

All in all, I would say it's a blurry tie on performance side, but simplicity is on the side of the current solution.

File: src/sinks/aws_cloudwatch_logs/mod.rs (hunk 2 above)
Comment (LucioFranco) [reply src/sinks/aws_cloudwatch_logs/mod.rs:1010]: Does this also check separate batches are produced?

File: src/sinks/aws_cloudwatch_logs/mod.rs [hunk 6]
```diff
@@ -314,27 +315,71 @@ impl Service<Vec<Event>> for CloudwatchLogsSvc {
...
+                    // We will find none or one of the events with timestamp==limit.
+                    // In the case of more events with limit, we can just split them
+                    // at found event, and send those before at with this batch, and
+                    // those after at with the next batch.
+                    let at = events
+                        .binary_search_by_key(&limit, |e| e.timestamp)
+                        .unwrap_or_else(|at| at);
+
+                    // Can't be empty
+                    let remainder = events.drain(at..).collect();
```
Comment (LucioFranco) [inline src/sinks/aws_cloudwatch_logs/mod.rs:367]: do we want to use https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.split_off?

Comment (ktff) [reply src/sinks/aws_cloudwatch_logs/mod.rs:367]: Yes, yes we do.

File: src/sinks/aws_cloudwatch_logs/mod.rs (hunk 2 above)
Comment (ktff) [reply src/sinks/aws_cloudwatch_logs/mod.rs:1042]: It doesn't.
