### PR TITLE
fix(wasm transform): Update WASM transform to implement TaskTransform

### LINKED ISSUE #4930: `wasm` transform no longer compiles
The `wasm` transform stopped compiling following the updating of `Transform` to be an enum.

```
error[E0404]: expected trait, found enum `Transform`
  --> src/transforms/wasm.rs:64:1
   |
64 | #[async_trait::async_trait]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a trait

error[E0404]: expected trait, found enum `Transform`
  --> src/transforms/wasm.rs:97:6
   |
97 | impl Transform for Wasm {
   |      ^^^^^^^^^ not a trait

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0404`.
error: could not compile `vector`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by jszwedko**
Follow-up to https://github.com/timberio/vector/pull/4684

Fixes #4930 

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

File: src/transforms/wasm.rs [hunk 1]
```diff
@@ -94,19 +95,31 @@ impl Wasm {
...
+    ) -> Box<dyn Stream01<Item = Event, Error = ()> + Send> {
+        let mut inner = self;
+
+        Box::new(
+            task.filter_map(move |event| {
+                inner
+                    .module
+                    .process(event)
+                    .map(|events| futures01::stream::iter_ok(events))
+                    .ok()
```
Comment (jszwedko) [inline src/transforms/wasm.rs:111]: I felt it was a bit weird to just drop any errors, but this maintains the current behavior.

Comment (Hoverbear) [reply src/transforms/wasm.rs:111]: WASM events are able to output events to stderr but later this will need to change to support reporting errors up to our internal metrics.

File: src/transforms/wasm.rs [hunk 2]
```diff
@@ -137,157 +150,148 @@ mod tests {
         Ok(Some(event))
     }
 
-    #[test]
-    fn protobuf_happy() -> crate::Result<()> {
+    async fn test_config(config: &str, input: &str, output: &str) {
+        let transform = parse_config(config).expect("could not init transform");
+
+        let input = vec![parse_event_artifact(input)
+            .expect("could not load input protobuf")
```
Comment (Hoverbear) [inline src/transforms/wasm.rs:157]: This error is about protobufs but it's used in the add fields test which does not use protobufs. I am confused.

**Review by Hoverbear — APPROVED** [review]
I think this looks good once the confusing error message is refined a bit!

File: src/transforms/wasm.rs (hunk 2 above)
Comment (jszwedko) [reply src/transforms/wasm.rs:157]: Doh, yeah, I'll update.
