### PR TITLE
fix(influxdb_metrics sink): Pass tls to healthcheck

### LINKED ISSUE #2237: Healthchecks should use the same http client
Ref #2234 

Currently, many of our healthchecks instantiate their own http client. This opens up the possibility for mismatched configs, etc.

We should go through each sink and ensure that, as much as possible, things like http clients are created in `build` and used for both the healthcheck and the sink itself.
For non-http-based sinks, we should at least double check that all connection settings are propogated correctly and look for ways to consolidate them.

### Todo

- [x] Construct `tcp healthcheck` with TLS.
  - Affects sinks: `vector`, `datadog`, `papertrail`, `tcp`, `socket`.
<p>

- [x] Build `HttpClient` once.
  - All of our http sinks now depend on our `util` so this is actually quite straight forward.
  - Affects sinks: `splunk_hec`, `loki`, `logdna`, `http`, ...
<p>

- [x] Build `aws` clients once.
  - Affects all `aws` sinks.

### PR DESCRIPTION
**Pull request by LucioFranco**
Closes #2237

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

File: src/sinks/influxdb_metrics.rs [hunk 1]
```diff
@@ -219,11 +225,10 @@ impl InfluxDBSvc {
 
         let request = hyper::Request::get(uri).body(hyper::Body::empty()).unwrap();
 
-        let https = HttpsConnector::new(4).expect("TLS initialization failed");
-        let client = hyper::Client::builder().build(https);
+        let mut client = HttpClient::new(resolver, None)?;
```
Comment (lukesteensen) [inline src/sinks/influxdb_metrics.rs:228]: Do we not support the usual TLS options here?

Comment (LucioFranco) [reply src/sinks/influxdb_metrics.rs:228]: Looks like it, I didn't want to change the behavior this just consolidates all tls building to one part of the codebase.
