### PR TITLE
enhancement(remap): added rate limit parameter to log function.

### LINKED ISSUE #6307: Default the Remap `log` function to implement rate-limiting
Any internal Vector log in the hot path should be rate-limited, this is why Vector rate-limits many of its internal logs. Remap should be no exception, therefore, the Remap `log` method should take a `rate_limit_secs` parameter that defaults to `1`:

```
log("Hello, world!") // defaults to 1 second
log("Hello, world!", rate_limit_secs: 2)
log("Hello, world!", rate_limit_secs: 0) // disabled
```

### PR DESCRIPTION
**Pull request by FungusHumungus**
Closes #6307

This adds a rate_limit_secs parameter to the remap log function, defaulting to 1 second.

This changes VRL to wrap each function call in:

```rust
span!(Level::ERROR, "remap", vrl_position = &self.span.start()).in_scope(|| {
           ...
        })
```

thus ensuring that each tracing call made in a VRL function is keyed on the position of the function call in the remap source.

Note, it is keyed on position rather than line number. This is perhaps not as ergonomic to the user should that get reported in the logs. However, it is probably theoretically more correct as it is technically possible to have more than one log message on the same line:

```
log(.this); log(.that)
```

So, really it would need both pieces of information. There need to be some enhancements to the parser `Span` struct to enable it to hold the line number before this can be done.

Currently pending #6615 

Signed-off-by: Stephen Wakely <stephen.wakely@datadoghq.com>

### CODE REVIEW

**Comment by jszwedko** [comment]
Taking a look at this now, it seems like the span isn't being associated for some reason 🤔 

```
Mar 04 09:32:14.161  INFO transform{component_kind="transform" component_name=remap component_type=remap}: vrl_stdlib::log: "bar" internal_log_rate_secs=1
```

I would have expected to see the `remap` span added here in there too.

**Review by JeanMertz — APPROVED** [review]
I'm not sure about the `compile_with_span` solution, but it gets us where we need to be for now, so we can revisit that solution later 👍

I realize this isn't working properly yet, but happy to see this land once it does.

**Review by jszwedko — COMMENTED** [review]
This seems like a good start to me!

My suggestion would be: Instead of adding a `compile_with_span` method, have whatever calls `execute` on the function create the span. This would ensure that any other tracing calls appearing in VRL will have the same span context. For the topology span (`transform{component_kind="transform" component_name=remap component_type=remap}` for example), we actually just use `error_span!` for everything, I believe to make sure the span is not filtered out by a lower verbosity level.

I know you mentioned it might not be possible to annotate the line number. Is that the case? I think the line number would be much more useful than the position.

**Comment by FungusHumungus** [comment]
> I'm not sure about the `compile_with_span` solution

I'm not keen on it either. It's just there for expediency at the moment. I think ultimately I need to add `Span` as a parameter to `compile`.. although that's not ideal either as very few functions will use it. Perhaps another struct that contains the `Span` and the `ParameterList` would be the tidiest?

**Comment by jszwedko** [comment]
> > I'm not sure about the `compile_with_span` solution
> 
> I'm not keen on it either. It's just there for expediency at the moment. I think ultimately I need to add `Span` as a parameter to `compile`.. although that's not ideal either as very few functions will use it. Perhaps another struct that contains the `Span` and the `ParameterList` would be the tidiest?

👍 I think my suggestion would be for none of the functions to be aware of it and instead inject the span at a level above that.

File: lib/vrl/stdlib/src/log.rs [hunk 1]
```diff
@@ -54,27 +67,47 @@ impl Function for Log {
...
+            b"warn" => {
+                let span = warn_span!("remap", vrl_position = &self.span.start());
+                let _ = span.enter();
+                warn!(message = %value, internal_log_rate_secs = rate_limit_secs)
+            }
             b"error" => error!("{}", value),
-            _ => info!("{}", value),
+            _ => {
+                let span = info_span!("remap", vrl_position = &self.span.start());
+                let _ = span.enter();
```
[the remark this answers is not in the document]
Comment (FungusHumungus) [reply lib/vrl/stdlib/src/log.rs:108]: >  `let _ = ` doesn't behave the same as `let _foo = `.

Ah, wasn't aware of that. Thanks. Yes that fixes it.

**Comment by FungusHumungus** [comment]
> I think my suggestion would be for none of the functions to be aware of it and instead inject the span at a level above that.

I like this idea a lot! I presume the performance hit is negligible?

**Comment by jszwedko** [comment]
> > I think my suggestion would be for none of the functions to be aware of it and instead inject the span at a level above that.
> 
> I like this idea a lot! I presume the performance hit is negligible?

That would be my assumption at least 😄 I feel like tracing usually likes to be minimally invasive, but I could definitely be wrong in this particular case. I'll run a quick bench to check. I think another advantage here is that any other events (`info!`, etc.) will have the span context linking them to a place in the remap source.

**Comment by jszwedko** [comment]
Ran a quick benchmark:

```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use tracing::{span, Level};

#[inline]
fn fibonacci(n: u64) -> u64 {
    match n {
        0 => 1,
        1 => 1,
        n => fibonacci(n - 1) + fibonacci(n - 2),
    }
}

fn benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("tracing");
    group.bench_function("no_span", |b| {
        b.iter(|| fibonacci(black_box(30)));
    });
    group.bench_function("span", |b| {
        b.iter(|| {
            let span = span!(Level::ERROR, "span");
            let _enter = span.enter();
            fibonacci(black_box(30))
        })
    });
}
criterion_group!(benches, benchmark);
criterion_main!(benches);
```

The overhead seems to be minimal:

```
tracing/no_span         time:   [2.4556 ms 2.4605 ms 2.4657 ms]
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild
tracing/span            time:   [2.7179 ms 2.8010 ms 2.8890 ms]
```

Screen Shot 2021-03-04 at 10 59 12 AM

The distribution is not quite so narrow, but still seems fine to me.

**Comment by FungusHumungus** [comment]
> I think my suggestion would be for none of the functions to be aware of it and instead inject the span at a level above that.

Yeah have got this down now and it works really well, is much cleaner to implement and has all those other advantages! Thanks for the suggestion.

**Review by jszwedko — APPROVED** [review]
Nice! This looks good!

File: lib/vrl/stdlib/src/log.rs [hunk 2]
```diff
@@ -21,6 +21,11 @@ impl Function for Log {
                 kind: kind::BYTES,
                 required: false,
             },
+            Parameter {
+                keyword: "rate_limit_secs",
+                kind: kind::INTEGER,
```
Comment (pablosichert) [inline lib/vrl/stdlib/src/log.rs:26]: I'm a bit late on the review, but maybe one follow-up here: I can imagine users wanting to specify rate limits such as `0.1s` or `1.5s`.

Does `internal_log_rate_secs` not support floats, or is there any other reason why fractions of a second shouldn't be allowed?

Comment (jszwedko) [reply lib/vrl/stdlib/src/log.rs:26]: The internal rate limiting logic only handles seconds right now. Interestingly it looks like tracing doesn't have support for passing floats around (https://docs.rs/tracing/0.1.25/tracing/trait.Value.html) so we'd need to adjust it to be something like `internal_rate_limit_ms` to allow finer granularity. Here it could still be represented as a float though.

Comment (pablosichert) [reply lib/vrl/stdlib/src/log.rs:26]: Opened https://github.com/timberio/vector/issues/6643 to track this one.
