### PR TITLE
fix(remap): Accept quoted lists in `parse_aws_alb_log` function

### LINKED ISSUE #6826: `parse_aws_alb_log` remap function doesn't parse quoted addresses
Reported on [Discord](https://discord.com/channels/742820443487993987/764187584452493323/822498232734187541).

It seems, despite their documentation, AWS sends log lines with the IP Addresses quoted. This causes the `parse_aws_alb_log` function to fail.

It would be useful if we could loosen the parsing requirements to allow all fields in the line to be quoted.

### PR DESCRIPTION
**Pull request by ktff**
Closes #6826

### CODE REVIEW

File: lib/vrl/stdlib/src/parse_aws_alb_log.rs [hunk 1]
```diff
@@ -499,5 +515,113 @@ mod tests {
                              user_agent: "curl/7.46.0"})),
             tdef: TypeDef::new().fallible().object::<&str, Kind>(inner_type_def()),
         }
+
+        eight {
```
Comment (JeanMertz) [inline lib/vrl/stdlib/src/parse_aws_alb_log.rs:519]: I know the other tests in this file use this naming convention as well, but I'd prefer it if we use more descriptive names to make it easier to find tests that validate a certain condition.

**Review by JeanMertz — APPROVED** [review]
LGTM, except for the test names.

File: lib/vrl/stdlib/src/parse_aws_alb_log.rs (hunk 1 above)
Comment (ktff) [reply lib/vrl/stdlib/src/parse_aws_alb_log.rs:519]: > that validate a certain condition.

That will be hard since, at least the tests added here, are an example of real logs returned by AWS and as such they haven't been created to test a specific condition but are testing multiple unrelated things.

Comment (JeanMertz) [reply lib/vrl/stdlib/src/parse_aws_alb_log.rs:519]: Ah okay. I assumed, since they were added in this PR, that they all tested some variation of "quoted lists". So `quoted_lists_1` etc would suffice.

But it's a minor thing, so happy to leave it as-is 👍
