### PR TITLE
enhancement(loki sink): Validate label names

### LINKED ISSUE #8702: loki sink does not work for Grafana Cloud when endpoint does not have /loki/...
### Vector Version

```
0.15.2 (and nightly)
```

### Vector Configuration File

```toml
[sinks.loki]
type = "loki"
inputs = ["varlogs"]
encoding.codec = "json"
endpoint = "https://logs-prod-eu-west-0.grafana.net"
auth.strategy = "basic"
auth.user = "****"
auth.password = "****"
healthcheck.enabled = false

  [sinks.loki.labels]
  "*" = "vector"
```

### Expected Behavior

Logs to be uploaded to Grafana Cloud Loki instance. Used the nightly build to support http proxy.

### Actual Behavior

Getting error:

```
Response failed. response=Response { status: 400, version: HTTP/1.1, headers: {"content-type": "text/plain; charset=utf-8", "x-content-type-options": "nosniff", "date": "Fri, 13 Aug 2021 11:07:12 GMT", "content-length": "58", "via": "1.1 google", "alt-svc": "clear"}, body: b"1:2: parse error: unexpected character inside braces: '*'\n" }
```

### Additional Context

When looking at endpoint Grafana Cloud expect loki to receive logs at it is `https://logs-prod-eu-west-0.grafana.net/api/prom/push`, and not `https://logs-prod-eu-west-0.grafana.net/loki/api/prom/push`. Seems like the code is appending `/loki/api/prom/push` to the endpoint url, which does not work in this case.

Maybe need a way to either override the url segment it is adding (/loki/...) or be able to set full url.

### PR DESCRIPTION
**Pull request by ktff**
Closes #8702

I wasn't able to find some documentation that explicitly says `[a-zA-Z_][a-zA-Z0-9_]*` is the regex, but going through loki code and testing against Grafana Cloud it seems they follow Prometheus convention https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels. The closest mention of this is for LogQL under [Parser Expression](https://grafana.com/docs/loki/latest/logql/).

### CODE REVIEW

File: src/sinks/loki.rs [hunk 1]
```diff
@@ -322,6 +328,21 @@ async fn fetch_status(
     Ok(client.send(req).await?.status())
 }
 
+fn valid_label_name(label: &Template) -> bool {
+    label.is_dynamic() || {
+        // Loki follows prometheus on this
+        // [a-zA-Z_][a-zA-Z0-9_]*
```
Comment (jszwedko) [inline src/sinks/loki.rs:334]: Would you mind adding the links you mentioned in the PR description to this?

**Review by jszwedko — APPROVED** [review]
Nice, thanks @ktff !

**Review by spencergilbert — APPROVED** [review]
