### PR TITLE
fix(aws_s3 sink): Propagate close for Fanout and buffers::disk::Writer

### LINKED ISSUE #4247: Convert Service sink adapters to StreamSink
For many of our sinks that are based on `tower::Service` we use shared components like `PartitionBatchSink` and `BatchSink` to convert them to `futures01::Sink`. As part of our effort to remove `futures01`, we should convert these components to implement our new `StreamSink` abstraction.

This should hopefully let us simplify the code a bit, but the focus at first should be on converting them in the most straightforward way possible. As a follow-up, once they're converted and working, we can make a pass to simplify as much as possible and move away from the `poll`-style towards an `async`/`await` style.

### LINKED ISSUE #4256: topology::Fanout doesn't propagate Sink::close to RouterSinks
So I've been trying to hunt down why shutdown termination is currently failing for an s3_sink using an image based on #4049. The behaviour manifests as all sources and transforms terminating cleanly, but the service getting stuck waiting for the S3 sink to terminate.

Running with LOG=trace filtered with

```
grep -v "vector::sinks::util::sink: Adding event to batch." | grep -v "vector::internal_events::kubernetes_logs: Received one event" | grep -v "file_server: file_source::file_server: read bytes. path="
```
yielded the following on shutdown

```
 Oct 01 11:21:31.644  INFO vector: Vector has stopped.
 Oct 01 11:21:31.644 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
 Oct 01 11:21:31.644 TRACE hyper::proto::h1::conn: shut down IO complete
 Oct 01 11:21:31.644 TRACE hyper::proto::h1::conn: State::close()
 Oct 01 11:21:31.644 TRACE hyper::proto::h1::conn: State::close_read()
 Oct 01 11:21:31.644 TRACE hyper::proto::h1::decode: decode; state=Chunked(Size, 0)
 Oct 01 11:21:31.644 TRACE hyper::proto::h1::decode: Read chunk hex size
 Oct 01 11:21:31.644 TRACE hyper::proto::h1::dispatch: body receiver dropped before eof, draining or closing
 Oct 01 11:21:31.644 TRACE mio::poll: deregistering handle with poller    
 Oct 01 11:21:31.644 TRACE source{topology_component_name=kubernetes topology_component_type=kubernetes_logs}: vector::sources::kubernetes_logs::lifecycle: A lifecycle-managed future completed after shutdown was requested
 Oct 01 11:21:31.644 TRACE source{topology_component_name=kubernetes topology_component_type=kubernetes_logs}: vector::sources::kubernetes_logs::lifecycle: Lifecycle got a global shutdown request
 Oct 01 11:21:31.645 DEBUG transform{topology_component_name=filtered topology_component_type=filter}: vector::topology::builder: Finished
 Oct 01 11:21:31.645 DEBUG transform{topology_component_name=split.other topology_component_type=swimlane}: vector::topology::builder: Finished
 Oct 01 11:21:31.645 DEBUG transform{topology_component_name=split.proxy_logs topology_component_type=swimlane}: vector::topology::builder: Finished
 Oct 01 11:21:31.645  INFO source{topology_component_name=kubernetes topology_component_type=kubernetes_logs}: vector::sources::kubernetes_logs: event processing loop completed gracefully
 Oct 01 11:21:31.645 TRACE source{topology_component_name=kubernetes topology_component_type=kubernetes_logs}: vector::sources::kubernetes_logs::lifecycle: A lifecycle-managed future completed after shutdown was requested
 Oct 01 11:21:31.645 TRACE want: poll_want: closed    
 Oct 01 11:21:31.645 TRACE want: signal: Closed    
 Oct 01 11:21:31.645 TRACE want: signal found waiting giver, notifying    
 Oct 01 11:21:31.646 DEBUG transform{topology_component_name=access_logs topology_component_type=logfmt_parser}: vector::topology::builder: Finished
 Oct 01 11:21:31.646 DEBUG transform{topology_component_name=split.access_logs topology_component_type=swimlane}: vector::topology::builder: Finished
 Oct 01 11:21:31.646 DEBUG transform{topology_component_name=stripped topology_component_type=ansi_stripper}: vector::topology::builder: Finished
 Oct 01 11:21:31.646  INFO source{topology_component_name=kubernetes topology_component_type=kubernetes_logs}: vector::sources::kubernetes_logs: done
 Oct 01 11:21:31.646  INFO source{topology_component_name=kubernetes topology_component_type=kubernetes_logs}: vector::sources::kubernetes_logs: file server completed gracefully
 Oct 01 11:21:31.646  INFO vector::topology: Shutting down... Waiting on: s3, split.access_logs, split.proxy_logs, stripped, kubernetes, access_logs. 59 seconds left
 Oct 01 11:21:31.646 TRACE source{topology_component_name=kubernetes topology_component_type=kubernetes_logs}: vector::sources::kubernetes_logs::lifecycle: A lifecycle-managed future completed after shutdown was requested
 Oct 01 11:21:31.647 DEBUG source{topology_component_name=kubernetes topology_component_type=kubernetes_logs}: vector::topology::builder: Finished
 Oct 01 11:21:32.028 DEBUG hyper::proto::h1::io: read 0 bytes
 Oct 01 11:21:32.028 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Closed, writing: Init, keep_alive: Disabled }
 Oct 01 11:21:32.028 TRACE hyper::proto::h1::conn: found EOF on idle connection, closing
 Oct 01 11:21:32.028 TRACE hyper::proto::h1::conn: State::close_read()
 Oct 01 11:21:32.029 TRACE hyper::proto::h1::conn: shut down IO complete
 Oct 01 11:21:32.029 TRACE mio::poll: deregistering handle with poller    
 Oct 01 11:21:32.029 TRACE want: signal: Closed    
 Oct 01 11:21:32.484 TRACE vector: Beep.
 Oct 01 11:21:33.485 TRACE vector: Beep.
 Oct 01 11:21:34.484 TRACE vector: Beep.
 Oct 01 11:21:35.484 TRACE vector: Beep.
 Oct 01 11:21:36.485 TRACE vector: Beep.
 Oct 01 11:21:36.645  INFO vector::topology: Shutting down... Waiting on: s3. 54 seconds left
 Oct 01 11:21:37.484 TRACE vector: Beep.
 Oct 01 11:21:38.485 TRACE vector: Beep.
 Oct 01 11:21:39.484 TRACE vector: Beep.
 Oct 01 11:21:40.484 TRACE vector: Beep.
 Oct 01 11:21:41.485 TRACE vector: Beep.
 Oct 01 11:21:41.645  INFO vector::topology: Shutting down... Waiting on: s3. 49 seconds left
 Oct 01 11:21:42.485 TRACE vector: Beep.
 Oct 01 11:21:43.484 TRACE vector: Beep.
 Oct 01 11:21:44.484 TRACE vector: Beep.
 Oct 01 11:21:45.484 TRACE vector: Beep.
 Oct 01 11:21:46.484 TRACE vector: Beep.
 Oct 01 11:21:46.646  INFO vector::topology: Shutting down... Waiting on: s3. 44 seconds left
 Oct 01 11:21:47.484 TRACE vector: Beep.
 Oct 01 11:21:48.485 TRACE vector: Beep.
 Oct 01 11:21:49.484 TRACE vector: Beep.
 Oct 01 11:21:50.484 TRACE vector: Beep.
 Oct 01 11:21:51.485 TRACE vector: Beep.
 Oct 01 11:21:51.645  INFO vector::topology: Shutting down... Waiting on: s3. 39 seconds left
 Oct 01 11:21:52.484 TRACE vector: Beep.
 Oct 01 11:21:53.484 TRACE vector: Beep.
 Oct 01 11:21:54.485 TRACE vector: Beep.
 Oct 01 11:21:55.484 TRACE vector: Beep.
 Oct 01 11:21:56.484 TRACE vector: Beep.
 Oct 01 11:21:56.645  INFO vector::topology: Shutting down... Waiting on: s3. 34 seconds left
 Oct 01 11:21:57.485 TRACE vector: Beep.
 Oct 01 11:21:58.485 TRACE vector: Beep.
 Oct 01 11:21:59.485 TRACE vector: Beep.
 Oct 01 11:22:00.484 TRACE vector: Beep.
 Oct 01 11:22:01.484 TRACE vector: Beep.
 Oct 01 11:22:01.645  INFO vector::topology: Shutting down... Waiting on: s3. 29 seconds left
 Oct 01 11:22:02.484 TRACE vector: Beep.
 Oct 01 11:22:03.485 TRACE vector: Beep.
 Oct 01 11:22:04.484 TRACE vector: Beep.
 Oct 01 11:22:05.484 TRACE vector: Beep.
 Oct 01 11:22:06.485 TRACE vector: Beep.
 Oct 01 11:22:06.645  INFO vector::topology: Shutting down... Waiting on: s3. 24 seconds left
 Oct 01 11:22:07.484 TRACE vector: Beep.
 Oct 01 11:22:08.484 TRACE vector: Beep.
 Oct 01 11:22:09.485 TRACE vector: Beep.
 Oct 01 11:22:10.485 TRACE vector: Beep.
 Oct 01 11:22:11.484 TRACE vector: Beep.
 Oct 01 11:22:11.646  INFO vector::topology: Shutting down... Waiting on: s3. 19 seconds left
 Oct 01 11:22:12.485 TRACE vector: Beep.
 Oct 01 11:22:13.484 TRACE vector: Beep.
 Oct 01 11:22:14.484 TRACE vector: Beep.
 Oct 01 11:22:15.484 TRACE vector: Beep.
 Oct 01 11:22:16.485 TRACE vector: Beep.
 Oct 01 11:22:16.645  INFO vector::topology: Shutting down... Waiting on: s3. 14 seconds left
 Oct 01 11:22:17.485 TRACE vector: Beep.
 Oct 01 11:22:18.485 TRACE vector: Beep.
 Oct 01 11:22:19.484 TRACE vector: Beep.
 Oct 01 11:22:20.484 TRACE vector: Beep.
 Oct 01 11:22:21.485 TRACE vector: Beep.
 Oct 01 11:22:21.630 TRACE hyper::client::pool: idle interval checking for expired
 Oct 01 11:22:21.630 TRACE hyper::client::pool: idle interval evicting closed for ("https", s3.us-east-1.amazonaws.com)
 Oct 01 11:22:21.646  INFO vector::topology: Shutting down... Waiting on: s3. 9 seconds left
 Oct 01 11:22:22.485 TRACE vector: Beep.
 Oct 01 11:22:23.484 TRACE vector: Beep.
 Oct 01 11:22:24.484 TRACE vector: Beep.
 Oct 01 11:22:25.484 TRACE vector: Beep.
 Oct 01 11:22:26.484 TRACE vector: Beep.
 Oct 01 11:22:26.645  INFO vector::topology: Shutting down... Waiting on: s3. 4 seconds left
 Oct 01 11:22:27.485 TRACE vector: Beep.
 Oct 01 11:22:28.484 TRACE vector: Beep.
 Oct 01 11:22:29.484 TRACE vector: Beep.
 Oct 01 11:22:30.484 TRACE vector: Beep.
 Oct 01 11:22:31.484 TRACE vector: Beep.
 Oct 01 11:22:31.645 ERROR vector::topology: Failed to gracefully shut down in time. Killing: s3
 Oct 01 11:22:31.645  INFO vector::topology: Shutting down... Waiting on: s3. overdue
 Oct 01 11:22:31.645 TRACE mio::poll: deregistering handle with poller    
 Oct 01 11:22:31.645 TRACE mio::poll: deregistering handle with poller    
 Oct 01 11:22:31.645 TRACE mio::poll: deregistering handle with poller    
 Oct 01 11:22:31.645 TRACE mio::poll: deregistering handle with poller    

```

Of particular note is the lack of

```
Closing partition batch sink.
```

Which you'd expect to see as a result of

```
fn close(&mut self) -> Poll<(), Self::SinkError> {
        trace!("Closing partition batch sink.");
        self.closing = true;
        self.poll_complete()
    }
```

This is what triggers PartitionBatchSink to "prematurely" consider batches to be flushed and so is critical to the shutdown proceeding.

Having followed the chain up it would appear that Fanout only calls close on its RouterSink objects when it receives removal messages on its control channel, which only occurs on removal of a downstream from the topology. The use of the default close implementation that just calls poll_complete means it never closes the buffer, which means the sink is never actually instructed to shutdown.

I could be completely wrong about this, it is rather late and I'm not intimately familiar with the codebase but would appreciate if someone could let me know if I'm on the right track. I'll probably experiment with this further tomorrow.

### PR DESCRIPTION
**Pull request by tustvold**
Ensures close is propagated to the inner sink(s) for Fanout and buffers::disk::Writer.

Also ensures on error Fanout removes the Sink that actually returned an error

Closes #4256

### CODE REVIEW

File: src/topology/fanout.rs [hunk 1]
```diff
@@ -129,7 +129,30 @@ impl Sink for Fanout {
...
+    }
+
+    fn close(&mut self) -> Poll<(), Self::SinkError> {
+        self.process_control_messages();
+
+        let mut all_complete = true;
+
+        for i in 0..self.sinks.len() {
+            let (_name, sink) = &mut self.sinks[i];
+            match sink.close() {
```
Comment (lukesteensen) [inline src/topology/fanout.rs:150]: Should we remove sinks that have returned `Ready` from `close` to avoid calling it after they're already closed? It seems like that could potentially cause issues (futures don't like being polled after they're complete), but I don't see anything in the docs saying not to do it. So maybe not a big deal?

We could also reset and reuse `self.i`, since it is not allowed to call `start_send` or `poll_complete` after calling `close`.

Comment (tustvold) [reply src/topology/fanout.rs:150]: I've not seen anything in the docs to indicate this as a limitation so am inclined to avoid the added complication. In most cases it should behave the same as `poll_complete` where it just returns Ready again

**Comment by tustvold** [comment]
I've added an additional change to use compat map on VectorSink's stream instead of the sink, which avoids the chicken-and-egg situation on close that was also discussed on the ticket

File: src/topology/fanout.rs [hunk 2]
```diff
@@ -129,7 +129,30 @@ impl Sink for Fanout {
...
+        }
+
+        if all_complete {
+            Ok(Async::Ready(()))
+        } else {
+            Ok(Async::NotReady)
+        }
+    }
+
+    fn close(&mut self) -> Poll<(), Self::SinkError> {
```
Comment (JeanMertz) [inline src/topology/fanout.rs:143]: It seems the only difference between `close` and `poll_complete` is `match sink.close()` vs `match sink.poll_complete()`. Is there any way we can DRY this up a bit?

**Review by lukesteensen — APPROVED** [review]
Thanks for this @tustvold! And apologies for the delay in getting this merged.
