### PR TITLE
enhancement(remap): Add assert_eq! function

### LINKED ISSUE #7833: Add `assert` and `assert_eq` functions to VRL to for use in unit tests
These functions will make it more straightforward to write unit tests, but could also be used in `remap` transforms.

Ideally the output of these would clearly highlight what assertion failed.

### PR DESCRIPTION
**Pull request by jszwedko**
This PR adds an `assert_eq!` function with the goal of making writing
unit tests easier.

The output may change with
https://github.com/timberio/vector/issues/6261 to make it easier to see
the condition that failed.

Closes #7833

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

File: lib/vrl/stdlib/src/assert_eq.rs [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+        &[
+            Example {
+                title: "success",
+                source: "asserteq!(true, true)",
+                result: Ok("true"),
+            },
+            Example {
+                title: "failure",
+                source: "asserteq!(true, false)",
+                result: Err(r#"function call error for "assert_eq" at (0:22): assertion failed"#),
```
Comment (spencergilbert) [inline lib/vrl/stdlib/src/assert_eq.rs:41]: Looking below wouldn't this error message be: `"assertion failed: {} == {}"`

Comment (jszwedko) [reply lib/vrl/stdlib/src/assert_eq.rs:41]: Oops, yes, I neglected to update these examples. Thanks!

Comment (spencergilbert) [reply lib/vrl/stdlib/src/assert_eq.rs:41]: NP, my first comment was asking about if we could message out the inputs 😄

Comment (spencergilbert) [reply lib/vrl/stdlib/src/assert_eq.rs]: Whoops, didn't even catch the incorrect function names :|

**Review by spencergilbert — APPROVED** [review]

File: lib/vrl/stdlib/benches/benches.rs [hunk 2]
```diff
@@ -10,6 +10,7 @@ criterion_group!(
     // https://github.com/timberio/vector/pull/6408
     config = Criterion::default().noise_threshold(0.05);
     targets = assert,
+    assert_eq,
```
Comment (JeanMertz) [inline lib/vrl/stdlib/benches/benches.rs:13]:
```suggestion
        assert_eq,
```

**Review by JeanMertz — APPROVED** [review]
Sweet. This will definitely be useful in unit-testing.

**Comment by binarylogic** [comment]
Just a small note, we forgot to add docs here which is being covered in https://github.com/timberio/vector/pull/8265

**Comment by jszwedko** [comment]
> Just a small note, we forgot to add docs here which is being covered in #8265

Doh, yep. Thanks @lucperkins
