### PR TITLE
fix(splunk_hec sink): Send time in <sec>.<ms> format

### LINKED ISSUE #2568: `humio_logs` | `splunk_hec` sinks - Incorrect timestamp format
I'm encountering an issue with the `humio_logs` sink.

The bug has been introduced by #2382 / #2376 .

Concretely all events sent from vector to humio end up with `timestamp was set to a value in the future. Setting it to now` on the humio side.

The [endpoint spec](https://docs.humio.com/integrations/data-shippers/hec/) for the Humio HEC endpoint clearly states for the `time` field:
> Time in _seconds_ since January 1, 1970 in UTC. This can be a decimal or real number to support milliseconds. Humio represents time with millisecond precision.

In order words, Humio expects timestamps to be sent as second-precision integers or as second floats where the fractional part may denote milliseconds (e.g. 1537537729.234).
I believe Humio will also be able to deal with additional fractionals to denote nanoseconds, although it'll probably internally ignore the nano part (which splunk probably does too).

Since #2382 however vector sends the `time` field as nanosecond integers, with no way to configure that which doesn't match the format Humio expects.

It seems like on the Splunk side the timestamp format can be configured on the collector endpoint, but that isn't the case for Humio. I'm no expert in Splunk, but I also doubt that it internally actually can deal with nanosecond precision.
[Splunks docs](https://docs.splunk.com/Documentation/DSP/1.0.1/User/FormatEvents) also mention a couple of times something called _Splunk epoch time format_ (`<sec>.<ms>`) which seems to be the actual default and which is basically what Humio expects as well.

I think it would be best if the splunk_hec sink sends the events in that format by default and maybe introduce a config option to send things as nanosecond integer values optionally (although technically the nanosecond precision can be also represented as fractions, so maybe this option is superfluous anyways). The humio_logs sink should not expose this option and just always use the default format.

Btw just wanted to say thank for this project! I spend way too much time trying to get fluent-bit to work with k8s+humio well until I found vector, which seems to have much less gotchas and a more sane config format overall.

### PR DESCRIPTION
**Pull request by fanatid**
From splunk docs "Format events for HTTP Event Collector" event key
"time" should be formatted as "\<sec>.\<ms>".

https://docs.splunk.com/Documentation/Splunk/8.0.3/Data/FormateventsforHTTPEventCollector

Signed-off-by: Kirill Fomichev <fanatid@ya.ru>

Should resolve #2568

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks @fanatid , I’m curious how we test for this in the humio_logs sink to prevent regression?

**Comment by fanatid** [comment]
Indeed. I'll add tests to humio_logs sink for this.

File: src/sinks/splunk_hec.rs [hunk 1]
```diff
@@ -117,13 +117,11 @@ impl HttpSink for HecSinkConfig {
...
-            event.remove(&event::log_schema().timestamp_key())
-        {
-            ts.timestamp_nanos()
-        } else {
-            chrono::Utc::now().timestamp_nanos()
+        let timestamp = match event.remove(&event::log_schema().timestamp_key()) {
+            Some(Value::Timestamp(ts)) => ts,
+            _ => chrono::Utc::now(),
         };
+        let timestamp = (timestamp.timestamp_millis() as f64) / 1000f64;
```
Comment (Hoverbear) [inline src/sinks/splunk_hec.rs:124]: This is definitely incorrect. Floats can't accurately represent whole number domains. (Eg 1.00001, 1.000002, 1.000003, ...).

While many test runs won't see this, I'm fairly sure this is the reson why `humio_valid_time_field` test fails fairly often on CI.
