### PR TITLE
fix(docker_logs source): Docker logs missing when container has a tty

### LINKED ISSUE #5903: `docker_logs` source doesn't source logs when container is run with a tty
I was trying to investigate a user report: https://discord.com/channels/742820443487993987/746070591097798688/796409845254979624 which reported logs not being sourced from a container.

It appears that if the target container is run with a TTY  ala `docker run --tty`, `vector` is unable to fetch these logs. I did note, however, that `docker logs` can still fetch them so I'm wondering if we also could.

To test, I ran:

```
docker run --name foobar --log-driver json-file --tty --rm mingrammer/flog -l -d 1000ms
```

### Vector Version

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-musl 2020-12-17)
```

### Vector Configuration File

```toml
[sources.in]
  type = "docker_logs"
  include_containers = ["foobar"]

[sinks.out]
  type = "console"
  inputs = ["in"]
  encoding.codec = "json"
```

### Debug Output

```
Jan 07 03:18:39.348  INFO vector::app: Log level is enabled. level="vector=trace,codec=trace,file_source=trace,tower_limit=trace,rdkafka=trace"
Jan 07 03:18:39.348  INFO vector::app: Loading configs. path=[("/tmp/tmp.toml", None)]
Jan 07 03:18:39.350  INFO vector::sources::docker_logs: Capturing logs from now on. now=2021-01-07T03:18:39.350714449+00:00
Jan 07 03:18:39.350  INFO vector::sources::docker_logs: Listening to docker log events.
Jan 07 03:18:39.350  INFO vector::topology: Running healthchecks.
Jan 07 03:18:39.350  INFO vector::topology: Starting source. name="in"
Jan 07 03:18:39.351  INFO vector::topology::builder: Healthcheck: Passed.
Jan 07 03:18:39.351  INFO vector::topology: Starting sink. name="out"
Jan 07 03:18:39.351  INFO vector: Vector has started. version="0.11.1" git_version="v0.11.1" released="Thu, 17 Dec 2020 17:03:52 +0000" arch="x86_64"
Jan 07 03:18:39.351  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
Jan 07 03:18:39.351 TRACE vector: Beep.
Jan 07 03:18:39.352 TRACE source{component_kind="source" component_name=in component_type=docker_logs}: vector::sources::docker_logs: Found already running container. id=f110545e17f6f36f2f5140647ab22783b7723b7119898e3fc7eaa3d133dfef81 names=["/foobar"]
Jan 07 03:18:39.356  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=f110545e17f6f36f2f5140647ab22783b7723b7119898e3fc7eaa3d133dfef81
Jan 07 03:18:40.352 TRACE vector: Beep.
Jan 07 03:18:41.352 TRACE vector: Beep.
Jan 07 03:18:42.352 TRACE vector: Beep.
Jan 07 03:18:43.352 TRACE vector: Beep.
^CJan 07 03:18:44.039  INFO vector: Vector has stopped.
Jan 07 03:18:44.040  INFO vector::internal_events::docker_logs: Stopped watching for container logs. container_id=f110545e17f6f36f2f5140647ab22783b7723b7119898e3fc7eaa3d133dfef81
Jan 07 03:18:44.040 DEBUG source{component_kind="source" component_name=in component_type=docker_logs}: vector::topology::builder: Finished.
Jan 07 03:18:44.040 ERROR vector::sources::docker_logs: Unable to return ContainerLogInfo to main. error=channel closed
Jan 07 03:18:44.040 DEBUG sink{component_kind="sink" component_name=out component_type=console}: vector::topology::builder: Finished.
```

### Expected Behavior

I should have seen logs from the `foobar` container.

### Actual Behavior

No `foobar` logs are output.

### PR DESCRIPTION
**Pull request by saez0pub**
Enum bollard::container::LogOutput is Console when docker started
with a tty. LogOutput::Console was missing in the new_event of a
stream value received

https://docs.rs/bollard/0.10.1/bollard/container/enum.LogOutput.html

Fixes #5903

### CODE REVIEW

File: src/sources/docker_logs.rs [hunk 1]
```diff
@@ -790,6 +791,7 @@ impl ContainerLogInfo {
         let (stream, mut bytes_message) = match log_output {
             LogOutput::StdErr { message } => (STDERR.clone(), message),
             LogOutput::StdOut { message } => (STDOUT.clone(), message),
+            LogOutput::Console { message } => (CONSOLE.clone(), message),
             _ => return None,
```
Comment (jszwedko) [inline src/sources/docker_logs.rs:795]: I feel like we could just make this `LogOutput::Stdin` for completeness given that all of the other enum variants are listed.

**Review by jszwedko — COMMENTED** [review]
Awesome, thanks @saez0pub ! This was a smaller change than I expected.

I tested it out locally and it seems to work. A couple of notes:

* Would you mind adding an integration test for this? I think you could add an additional parameter to https://github.com/timberio/vector/blob/48d2a84b1b11ba54db7bd892944f2a479238edb4/src/sources/docker_logs.rs#L1213-L1233 indicating whether the TTY should be attached and have a test that sets it to `true`. See the other tests below there for reference.
* It seems like the events can end in a `\r\n` when they come from `LogOutput::Console` so they end up coming through with the trailing `\r`: `{"container_created_at":"2021-04-13T19:42:28.605739900Z","container_id":"b2287e2f495a0a319354253657af8cbe5ca9be2f97ac9b7600ea88b9536df026","container_name":"bold_hofstadter","host":"COMP-C02DV25MML87","image":"busybox","message":"hello\r","source_type":"docker","stream":"console","timestamp":"2021-04-13T19:42:29.171195Z"}`. I think you could update the logic here to avoid that: https://github.com/timberio/vector/blob/48d2a84b1b11ba54db7bd892944f2a479238edb4/src/sources/docker_logs.rs#L841-L855

File: src/sources/docker_logs.rs (hunk 1 above)
Comment (saez0pub) [reply src/sources/docker_logs.rs:795]: Hello,

Thank you for your review :bow:
I added a dedicated test for a log sent by a container started with a tty.

For the LogOutput::Stdin I was also wondering if it wouldn't be better an explicit case and other match could lead to emitting a debug log because it would be easier to debug if bollard change  LogOutput. But I'm not sure if I am not overthinking it  :shrug: 
Maybe just adding LogOutput::Stdin => return None, would be sufficient ?

Comment (jszwedko) [reply src/sources/docker_logs.rs:795]: Thanks for adding the test and fixing the `\r`!

It's actually not clear to me under what conditions the the log output would be `LogOutput::StdIn`. I think it'd be reasonable to just map it to `None` though which is the current state of things.

Comment (saez0pub) [reply src/sources/docker_logs.rs]: I added the StdIn, now we will know if a pattern is not covered at compilation time :+1:

**Review by jszwedko — APPROVED** [review]
Awesome, thanks again @saez0pub !
