### PR TITLE
fix(datadog_logs sink): Enable tls by default

### LINKED ISSUE #2436: Datadog Sink should require TLS
I followed the tutorial at https://vector.dev/guides/integrate/sinks/datadog_logs/ - Unbeknownst to me at the time, this lead to me exposing our datadog API key on the wire as plain text. It was a surprise to me when I dug into the configuration further and discovered that TLS was not the default.

I understand that you're not shipping the application with a CA bundle, so may feel like you can't make TLS the default. On the other hand, you could make TLS config required as part of the sink, and force the user to explicitly disable TLS through that config if a CA bundle is not available to them.

If you don't want to do the above, the tutorial could still be updated to include TLS config, so that people following it are aware that not using it will lead to their API key being exposed.

### PR DESCRIPTION
**Pull request by LucioFranco**
Fixes #2436

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

File: src/sinks/datadog/logs.rs [hunk 1]
```diff
@@ -38,22 +38,20 @@ impl SinkConfig for DatadogLogsConfig {
...
-            (
-                "intake.logs.datadoghq.com".to_string(),
-                10516,
-                Some(TlsSettings::default()),
-            )
+            let tls = self.tls.clone().unwrap_or({
+                let mut tls = TlsConfig::default();
+                tls.enabled = Some(true);
+                tls
+            });
```
Comment (bruceg) [inline src/sinks/datadog/logs.rs:47]: Maybe `TlsConfig` needs a `default_enabled` function. Either that or one day we just make TLS default to enabled across the board.

Comment (LucioFranco) [reply src/sinks/datadog/logs.rs:47]: hmm honestly, I think defaulting tls to enabled like this would be a good idea. @lukesteensen and @binarylogic thoughts?

**Comment by LucioFranco** [comment]
So for the docs this is hard, because by default if you don't set `endpoint` its enabled but if you set `endpoint` then its not by default enabled? So I think in this case the docs are fine. 

I actually like the idea of enabling tls by default across the board.

File: src/sinks/datadog/logs.rs (hunk 1 above)
Comment (binarylogic) [reply src/sinks/datadog/logs.rs:47]: I tend to agree but don’t understand all of the potential problems that might cause. In general defaulting towards secure makes sense.

Comment (LucioFranco) [reply src/sinks/datadog/logs.rs:47]: https://github.com/timberio/vector/issues/2528

Comment (lukesteensen) [reply src/sinks/datadog/logs.rs:47]: Agree. There may be cases where it doesn't make sense, but we should definitely do it for things that ~always go over the internet (i.e. sinks for hosted services).

**Comment by LucioFranco** [comment]
@binarylogic I'd like your feeddback on my comment above around docs.
