### PR TITLE
fix(kubernetes_logs source): Refactor stream and invocation errors to support recoverable error types

### LINKED ISSUE #6795: kubernetes_logs source stop glob after [unexpected EOF during chunk size line] occurred
### Vector Version

```
v0.11.1-debian
```

### Vector Configuration File

https://gist.github.com/CasparChou/70234ddf69d18291f27f04df106f0c5d#file-vector-agent-config

### Debug Output

debug logs still collecting

### Expected Behavior

if error can't be handled, exit process
if process can handle the exception and resume collecting/sink, will be better
after restart pod, file checkpoint forward to current time and seems losing logs

### Actual Behavior

kubernetes_logs source stuck and stop collecting logs, and increased `vector_k8s_watch_requests_failed_total`
but process still alive, it's hard to know logs is stop collecting

```
Mar 16 22:46:59.121 ERROR source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::internal_events::kubernetes::instrumenting_watcher: Watch invocation failed. error=Reading { source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: "unexpected EOF during chunk size line" }) } rate_limit_secs=5
Mar 16 22:46:59.121 ERROR source{component_kind="source" component_name=kubernetes_logs component_type=kubernetes_logs}: vector::sources::kubernetes_logs: Reflector process exited with an error. error=streaming error
```

### Additional Context

losing logs when agent is not working, and not recovering logs when agent is back (by terminated pod)
image

Error occurred on all agent in same time (first graph), and all of agents' source/sink plugin stop process any event (second graph)
image

### PR DESCRIPTION
**Pull request by eeyun**
This slightly refactors our stream and invocation errors to allow for continuing our processing in the case of an http invocation error.

Closes #6795

The new behavior should now automatically retry infinitely in the case of HTTP errors and should warn the user that their metadata could be stale.

Signed-off-by: Ian Henry <ianjhenry00@gmail.com>

### CODE REVIEW

File: src/kubernetes/api_watcher.rs [hunk 1]
```diff
@@ -64,25 +64,37 @@ where
...
             response: &response
         });
+        // let response = self
+        //     .client
+        //     .send(request)
+        //     .await
+        //     .context(invocation::Request)?;
+        // emit!(internal_events::ResponseReceived {
+        //     response: &response
+        // });
```
Comment (blt) [inline src/kubernetes/api_watcher.rs:91]: Intentionally left?

Comment (eeyun) [reply src/kubernetes/api_watcher.rs:91]: nope! good catch!

**Comment by eeyun** [comment]
As a follow on to this pr and to have the link in gh metadata https://github.com/timberio/vector/issues/6817

**Comment by jszwedko** [comment]
@JeanMertz do you mind taking a look at this one? We'd like to get it in this week if feasible.

**Comment by jszwedko** [comment]
@FungusHumungus @JeanMertz is there any chance we could have this reviewed this week? It'd be nice to get into the release next week if we could.

File: src/kubernetes/api_watcher.rs [hunk 2]
```diff
@@ -64,11 +64,20 @@ where
...
 
         // Send request, get response.
-        let response = self
-            .client
-            .send(request)
-            .await
-            .context(invocation::Request)?;
+        let response = match self.client.send(request).await {
+            Ok(response) => response,
+            Err(source @ crate::http::HttpError::CallRequest { .. }) => {
```
Comment (jszwedko) [inline src/kubernetes/api_watcher.rs:69]: Just noting for other readers that this appears to be the error we get if any `hyper` error occurs.

File: src/kubernetes/api_watcher.rs [hunk 3]
```diff
@@ -77,12 +86,7 @@ where
         let status = response.status();
         if status != StatusCode::OK {
             let source = invocation::Error::BadStatus { status };
-            let err = if status == StatusCode::GONE {
-                watcher::invocation::Error::desync(source)
```
Comment (jszwedko) [inline src/kubernetes/api_watcher.rs:81]: Do we not want to handle `desync` events specifically anymore? Or do they end up as a `hyper::Error` and thus mapped to `Recoverable`.

File: src/kubernetes/reflector.rs [hunk 4]
```diff
@@ -82,15 +82,11 @@ where
...
-                    self.resource_version.reset();
-                    self.state_writer.resync().await;
+                Err(watcher::invocation::Error::Recoverable { source }) => {
+                    emit!(internal_events::InvocationHttpErrorReceived { error: source });
                     continue;
                 }
                 Err(watcher::invocation::Error::Other { source }) => {
-                    // Not a desync, fail everything.
                     error!(message = "Watcher error.", error = ?source);
                     return Err(Error::Invocation { source });
```
Comment (jszwedko) [inline src/kubernetes/reflector.rs:91]: I think we might actually just want to retry _any_ error we get rather than specifically only retrying HTTP errors. Encountering an error that hits this match arm is going to result in the same behavior described by https://github.com/timberio/vector/issues/6795 where the `kubernetes_logs` component just stops processing but Vector continues to run.

**Review by jszwedko — COMMENTED** [review]
In general I think this is an improvement, so I'm happy to see it go in as-is, but I am wondering if we shouldn't expand this to just retry _any_ error occurred when making a watch invocation. As I noted in the inline comment, any other, non-`hyper`, error encountered (I'm not sure what these actually would be) would result in the same poor behavior noted in https://github.com/timberio/vector/issues/6795 where the `kubernetes_logs` component just stops processing. If we really think those errors are fatal, we should shutdown Vector.

File: src/kubernetes/api_watcher.rs (hunk 3 above)
Comment (JeanMertz) [reply src/kubernetes/api_watcher.rs:81]: Related to this,

if they _are_ part of `Recoverable`, shouldn't we still reset the internal state as was previously done?

**Review by JeanMertz — COMMENTED** [review]
Overall looks good to me, but I agree with Jesse's remark on retrying on as many errors as possible, and also posed a question on whether we still need to reset internal state when an error occurs.

File: src/kubernetes/api_watcher.rs (hunk 3 above)
Comment (jszwedko) [reply src/kubernetes/api_watcher.rs:81]: Agreed. It seems like, specifically on desync, we should be clearing the internal state (looking at https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes).

My opinion is to re-add the existing specific handling of `desync` events and retry everything else.

Comment (jszwedko) [reply src/kubernetes/api_watcher.rs:81]: Upon closer inspection the desync events are actually also handled lower down in `api_watcher.rs` by reading the status code from the body. I'm guessing k8s still returns a JSON payload with the 410 that has the status within the body. However, https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes, specifically mentions handling HTTP 410 responses, so I readded that logic.

> if they are part of Recoverable, shouldn't we still reset the internal state as was previously done?

I don't think we want to clear the state if there was a network blip. I think it's better to just keep running with the stale state. I could be convinced otherwise though.

**Comment by jszwedko** [comment]
I spent some time trying to refactor this to retry more errors but it ended up being a bigger rabbit hole than I expected due to the way that the tests expect to terminate the reflector by triggering an error. I think we should still do it, but would like to break that off into a separate issue so that we can get this partial fix into the next release.

I did re-add explicit handling of the HTTP 410 responses for desync though.

In my opinion, I think this could still go-in as-is as it at least handles the reported case of a network connectivity error talking to k8s.

@JeanMertz would you be cool with that? Do you mind giving this another look?

**Review by StephenWakely — APPROVED** [review]
Looks good to me.

File: src/kubernetes/reflector.rs (hunk 4 above)
Comment (MOZGIII) [reply src/kubernetes/reflector.rs:101]: Not here, this should be done at the watcher level, and the abstraction at this level shouldn't deal with transport errors at all.
