### PR TITLE
fix(syslog source): improve frame handling for the octet decoder

### LINKED ISSUE #4895: Sending `1 <23>4` twice to the `syslog` source will cause it to go into an infinite loop
### Vector Version

master

### Vector Configuration File

```toml
[sources.remote_syslog]
  type = "syslog"
  address = "0.0.0.0:6515"
  mode = "tcp"

[sinks.stdout]
  type = "console"
  inputs = ["remote_syslog"]
  target = "stdout"
  encoding = "json"
```

### Debug Output

Send this to Vector: 

```sh
echo "1 <23>4\n1 <23>4" | nc localhost 6515 
```

The source will go into an infinite loop with this message:

```
Nov 05 23:47:06.467  WARN source{component_kind="source" component_name=remote_syslog component_type=syslog}:connection{peer_addr=127.0.0.1}: vector::sources::util::tcp: Failed to read data from TCP source. error=Unable to decode message len as number
```

repeated ad infinitum.

You have to `kill -9` Vector to stop it.

### Expected Behavior

I'm not 100% sure what should happen. The `1 ` at the start of the message is saying the syslog message is 1 byte long, which is probably a ridiculous length for a message to be. It should probably not get stuck in a loop though.

### PR DESCRIPTION
**Pull request by FungusHumungus**
Closes #4895 

This makes a number of changes to the octet decoder for the syslog source.

1. If we receive invalid data, the source position needs to be advanced past the erroneous bytes, otherwise the decoder loops forever on that invalid data.
2. We need to handle data coming in over multiple frames. Before the decoder assumed all the data would come in a single frame and treat the next frame as a new message. This may not be the case. So now the decoder maintains some state to allow it to handle a single message coming in over separate frames.

### CODE REVIEW

File: src/sources/syslog.rs [hunk 1]
```diff
@@ -219,59 +224,105 @@ impl SyslogDecoder {
...
+                        Err(_) => {
+                            // Advance the buffer past the erroneous bytes
+                            // to prevent us getting stuck in an infinite loop.
+                            src.advance(i + 1);
+                            self.in_octet = false;
+                            return Err(LinesCodecError::Io(io::Error::new(
+                                io::ErrorKind::InvalidData,
+                                "Unable to decode message len as number",
+                            )));
+                        }
```
Comment (bruceg) [inline src/sources/syslog.rs:268]: Would this be better written as another `map_err` adapter?
```suggestion
                        .map_err(|_| {
                            // Advance the buffer past the erroneous bytes
                            // to prevent us getting stuck in an infinite loop.
                            src.advance(i + 1);
                            self.in_octet = false;
                            LinesCodecError::Io(io::Error::new(
                                io::ErrorKind::InvalidData,
                                "Unable to decode message len as number",
                            ))
                        })?;
```

File: src/sources/syslog.rs [hunk 2]
```diff
@@ -219,59 +224,105 @@ impl SyslogDecoder {
...
+                                // Advance the buffer past the erroneous bytes
+                                // to prevent us getting stuck in an infinite loop.
+                                src.advance(to);
+                                self.in_octet = false;
+                                return Err(LinesCodecError::Io(io::Error::new(
+                                    io::ErrorKind::InvalidData,
+                                    "Unable to decode message as UTF8",
+                                )));
+                            }
+                        };
```
Comment (bruceg) [inline src/sources/syslog.rs:287]: Ditto on the `map_err` comment above.

**Review by bruceg — APPROVED** [review]
The logic looks hairy, but these kinds of decoders always do. I have a couple of suggestions that might clean up the logic flow, but nothing blocking.

**Comment by bruceg** [comment]
Hmm, looks like I should have checked the tests before giving my approval — `octet_decode_moves_past_exceeded_frame_length` looks to be still failing.

File: src/sources/syslog.rs (hunk 1 above)
Comment (FungusHumungus) [reply src/sources/syslog.rs:268]: I'm not too keen on this. Personally I think that map functions should be reserved for functions without side effects. Here we have some side effects - we are advancing the buffer position and changing the value on `in_octet`. So I would prefer to keep it procedural here.

Theoretically it could be possible for `map_err` to call the closure twice which could cause unintended effects if the closure is not idempotent. Of course we know in this case it will only call it once, but that's only because we rely on our understanding of the calling code. Also, it is then doing more than just a mapping, so we are doing more than we are claiming to do by calling map.

Do you feel strongly otherwise?

File: src/sources/syslog.rs [hunk 3]
```diff
@@ -219,59 +224,105 @@ impl SyslogDecoder {
...
+                self.in_octet = true;
             }
         }
-        None
+
+        if self.in_octet {
+            Some(self.octet_decode(src))
+        } else {
+            None
+        }
```
[the remark this answers is not in the document]
Comment (FungusHumungus) [reply src/sources/syslog.rs:325]: Nice.

File: src/sources/syslog.rs (hunk 1 above)
Comment (bruceg) [reply src/sources/syslog.rs:268]: No strong opinion, and your preference makes sense.

**Review by bruceg — APPROVED** [review]

File: src/sources/syslog.rs [hunk 4]
```diff
@@ -808,4 +865,79 @@ mod test {
...
+        assert!(result.unwrap().is_err());
+        assert_eq!(b""[..], buffer);
+    }
+
+    #[test]
+    fn octet_decode_moves_past_exceeded_frame_length() {
+        let mut decoder = SyslogDecoder::new(16);
+        let mut buffer = BytesMut::with_capacity(32);
+
+        // An invalid syslog message containing invalid utf8 bytes.
```
Comment (pablosichert) [inline src/sources/syslog.rs:919]: I think this comment has been erroneously copied from the previous test.

```suggestion
```

File: src/sources/syslog.rs [hunk 5]
```diff
@@ -808,4 +865,79 @@ mod test {
...
+        assert!(result.unwrap().is_err());
+        assert_eq!(b""[..], buffer);
+    }
+
+    #[test]
+    fn octet_decode_moves_past_exceeded_frame_length_multiple_frames() {
+        let mut decoder = SyslogDecoder::new(16);
+        let mut buffer = BytesMut::with_capacity(32);
+
+        // An invalid syslog message containing invalid utf8 bytes.
```
Comment (pablosichert) [inline src/sources/syslog.rs:932]:
```suggestion
```

File: src/sources/syslog.rs [hunk 6]
```diff
@@ -219,59 +224,110 @@ impl SyslogDecoder {
...
-                            "Unable to decode message as UTF8",
-                        ))
-                    })?
-                    .to_string();
-                src.advance(to);
-                Ok(Some(s))
-            } else {
-                Ok(None)
+        loop {
+            let read_to = cmp::min(self.other.max_length().saturating_add(1), src.len());
```
Comment (pablosichert) [inline src/sources/syslog.rs:228]: What is the purpose of the `+ 1` here?

File: src/sources/syslog.rs [hunk 7]
```diff
@@ -219,59 +224,110 @@ impl SyslogDecoder {
...
+                (false, _, Some(i)) => {
+                    let len: usize = match std::str::from_utf8(&src[..i])
+                        .map_err(|_| ())
+                        .and_then(|num| num.parse().map_err(|_| ()))
+                    {
+                        Ok(len) => len,
+                        Err(_) => {
+                            // Advance the buffer past the erroneous bytes
+                            // to prevent us getting stuck in an infinite loop.
+                            src.advance(i + 1);
```
Comment (pablosichert) [inline src/sources/syslog.rs:262]: If I understand correctly, `space_pos` is an index while `advance` takes a `count`.

Do we always start reading the buffer at `0`?

File: src/sources/syslog.rs [hunk 8]
```diff
@@ -219,59 +224,110 @@ impl SyslogDecoder {
...
+                            self.in_octet = false;
+                            return Err(LinesCodecError::Io(io::Error::new(
+                                io::ErrorKind::InvalidData,
+                                "Unable to decode message len as number",
+                            )));
+                        }
+                    };
+
+                    let from = i + 1;
```
Comment (pablosichert) [inline src/sources/syslog.rs:271]: I'd rename `i` to `space_pos`, otherwise the context is quickly lost in this relatively large branch.

File: src/sources/syslog.rs (hunk 6 above)
Comment (FungusHumungus) [reply src/sources/syslog.rs:228]: That's a good question. I'm not 100% sure. It comes from LinesCodec:

https://github.com/tokio-rs/tokio/blob/master/tokio-util/src/codec/lines_codec.rs#L114

File: src/sources/syslog.rs (hunk 7 above)
Comment (FungusHumungus) [reply src/sources/syslog.rs:262]: There are very few situations where we do actually loop. Thinking about it, I can probably get rid of the loop completely which would simplify the logic. I'll have a go at that.

File: src/sources/syslog.rs [hunk 9]
```diff
@@ -219,59 +223,108 @@ impl SyslogDecoder {
...
+                            src.advance(to);
+                            self.in_octet = false;
+                            return Err(LinesCodecError::Io(io::Error::new(
+                                io::ErrorKind::InvalidData,
+                                "Unable to decode message as UTF8",
+                            )));
+                        }
+                    };
+
+                    src.advance(to);
```
Comment (pablosichert) [inline src/sources/syslog.rs:284]: It seems like advancing the buffer can be done unconditionally here:

```suggestion
                    src.advance(to);

                    let s = match std::str::from_utf8(msg) {
                        Ok(s) => s.to_string(),
                        Err(_) => {
                            self.in_octet = false;
                            return Err(LinesCodecError::Io(io::Error::new(
                                io::ErrorKind::InvalidData,
                                "Unable to decode message as UTF8",
                            )));
                        }
                    };
```

File: src/sources/syslog.rs (hunk 6 above)
Comment (pablosichert) [reply src/sources/syslog.rs]: If I understand correctly: `max_length` refers to the maximum line length, excluding the `\n` character. To include `\n`, `1` is added.

File: src/sources/syslog.rs (hunk 9 above)
Comment (FungusHumungus) [reply src/sources/syslog.rs:284]: It would appear that way, but unfortunately this gives us a number of lifetime issues since `src.get` returns a reference which means that `src.advance` can't mutably borrow until we have finished the `match`.

File: src/sources/syslog.rs [hunk 10]
```diff
@@ -219,59 +223,108 @@ impl SyslogDecoder {
...
+                // discard the entire frame.
+                src.advance(src.len());
+                Ok(None)
+            }
+            (false, _, Some(space_pos)) => {
+                let len: usize = match std::str::from_utf8(&src[..space_pos])
+                    .map_err(|_| ())
+                    .and_then(|num| num.parse().map_err(|_| ()))
+                {
+                    Ok(len) => len,
```
Comment (FungusHumungus) [inline src/sources/syslog.rs:253]: This still isn't quite right. We aren't handling the case where you specify a length > maximum length, or a length for a message that is split over multiple frames.

Comment (FungusHumungus) [reply src/sources/syslog.rs]: We should be now.

File: src/sources/syslog.rs [hunk 11]
```diff
@@ -200,16 +200,22 @@ impl TcpSource for SyslogTcpSource {
 #[derive(Clone, Debug)]
 struct SyslogDecoder {
     other: LinesCodec,
+    is_discarding: bool,
+    discard_chars: Option<usize>,
```
Comment (bruceg) [inline src/sources/syslog.rs:204]: `discard_chars` is only examined when `is_discarding` is `true`. This strongly suggests it's state data that may be better encapsulated in a proper state, like this (but probably with better variant names):
```rust
enum State {
    NotDiscarding,
    Discarding(usize),
    DiscardingToEOL,
}
```
I also wonder if `in_octet` could be rolled into this state as well, but I can't quite tell from the logic here.

File: src/sources/syslog.rs [hunk 12]
```diff
@@ -219,59 +225,163 @@ impl SyslogDecoder {
...
+                src.advance(offset + 1);
+                self.is_discarding = false;
+                self.in_octet = false;
+                Err(LinesCodecError::Io(io::Error::new(
+                    io::ErrorKind::Other,
+                    "Frame length limit exceeded",
+                )))
+            }
+
+            (true, _, None, _) => {
```
Comment (bruceg) [inline src/sources/syslog.rs:272]: I'd tend to want the second `None` made explicit here rather than relying on the ordering of the cases. That is reserve the `_` for when we don't care, and put actual values for all other places.

Of course, using a state enum eliminates at least some of these.

File: src/sources/syslog.rs [hunk 13]
```diff
@@ -219,59 +225,163 @@ impl SyslogDecoder {
...
+                    // The length is greater than we want.
+                    // We need to discard the entire message.
+                    self.is_discarding = true;
+                    self.discard_chars = Some(len);
+                    src.advance(space_pos + 1);
+
+                    return Ok(None);
+                }
+
+                if let Some(msg) = src.get(from..to) {
```
Comment (bruceg) [inline src/sources/syslog.rs:316]:
```suggestion
                    Ok(None)
                } else if let Some(msg) = src.get(from..to) {
```

**Review by bruceg — COMMENTED** [review]
The state logic looks more comprehensible now, though I think it could benefit from a couple of tweaks.

File: src/sources/syslog.rs (hunk 11 above)
Comment (FungusHumungus) [reply src/sources/syslog.rs:204]: Yes, that's much better.
