### PR TITLE
fix(sources): Shutdown starting from `tcp` and `unix` sockets 

### LINKED ISSUE #2604: test_unix_stream_syslog fails at CI
The `test_unix_stream_syslog` occasionally fails at CI: https://github.com/timberio/vector/pull/2579/checks?check_run_id=674631518. This is from my docker-enabling branch, but there's nothing that suggests we should let this pass. On the contrary - this new setup is great because it uncovers this previously hidden problem.

The failing assertion is this one: https://github.com/timberio/vector/blob/0a0f8d5b6478237d7402ca9e356c9ff4ea6f8497/tests/syslog.rs#L186

This is a rather odd issue. How I see it, the problem is that when the topology stops, the messages in the inner buffers aren't released properly. Isn't the new two-phase shutdown system supposed to help solve this issue?

There are other tests that fail in similar conditions - and the way we solved that was by adding a timeout, effectively muting the problem. But I think there's a real issue somewhere there, and we get to the bottom of it.

Related:
- https://github.com/timberio/vector/issues/2102

### PR DESCRIPTION
**Pull request by ktff**
Closes #2604.

Adds `ReadUntil` for `AsyncRead` similar to `TakeUntil` for `Stream`.

This wraps `tcp` and `unix` sockets with `ReadUntil` and `ShutdownSignal`. So once the shutdown starts there will be no more reads from the sockets, but all that have been read will be processed.  

This also fixes `mock` source.

### CODE REVIEW

**Comment by MOZGIII** [comment]
I think there's an issue: users will be able to submit data to the TCP connections, get a TCP ACK for their data, and when shutdown signal comes and we discard all the data that's still left in the kernel buffers.
What if we handle it differently: upon shutdown, [`shutdown(2)`](http://man7.org/linux/man-pages/man2/shutdown.2.html) the underlying socket (so that the other end knows it shouldn't send any more data), and read all the data until the ends from the descriptors before closing. This way would be more graceful than just giving up reading from the underlying `Read`.

**Comment by MOZGIII** [comment]
Did some diging, and it seems like `shutdown` with `SHUT_RD` is a noop:
https://github.com/torvalds/linux/blob/f85c1598ddfe83f61d0656bd1d2025fa3b148b99/net/ipv4/tcp.c#L2317-L2335

But still, we should even without involving shutdown - I think we should at least try to attempt to the whole kernel-buffered data up until the underlying socket returns `WouldBlock` (or, since that can actually never happen under certain conditions, up to some force-stop timeout - but the important part is to also read till `WouldBlock`).

File: src/async_read.rs [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+{
+    fn read(&mut self, buf: &mut [u8]) -> Result<usize, std::io::Error> {
+        self.reader.read(buf)
+    }
+}
+
+impl<S, F, O> AsyncRead for ReadUntil<S, F, O>
+where
+    S: AsyncRead,
+    F: Future<Item = O, Error = ()>,
```
Comment (MOZGIII) [inline src/async_read.rs:51]: Since it doesn't seem like we really want an error here, can we maybe use [`Infallible`](https://doc.rust-lang.org/std/convert/enum.Infallible.html) for `Error`?

File: src/async_read.rs [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+    free: bool,
+}
+
+/// This `AsyncRead` extension trait provides a `read_until` method that terminates the reader once
+/// the given future resolves.
+pub trait AsyncReadExt: AsyncRead {
+    /// Read data from this reader until the given future resolves.
+    ///
+    /// If the future produces an error, the read will be allowed to continue indefinitely.
+    fn read_until<U, O>(self, until: U) -> ReadUntil<Self, U::Future, O>
```
Comment (MOZGIII) [inline src/async_read.rs:23]: We should probably use another name, this is confusing cause it conflicts with [`futures::io::AsyncBufReadExt::read_until`](https://docs.rs/futures/0.3.5/futures/io/trait.AsyncBufReadExt.html#method.read_until).
The same applies to the `ReadUntil` struct itself.

File: tests/buffering.rs [hunk 3]
```diff
@@ -67,21 +67,14 @@ fn test_buffering() {
         .send_all(input_events_stream);
     let _ = rt.block_on(send).unwrap();
 
-    // A race caused by `rt.block_on(send).unwrap()` is handled here. For some
-    // reason, at times less events than were sent actually arrive to the
-    // `source`.
-    // We mitigate that by waiting on the event counter provided by our source
-    // mock.
-    test_util::wait_for_atomic_usize(source_event_counter, |x| x == num_events);
```
Comment (MOZGIII) [inline tests/buffering.rs:75]: Instead of removing this altogether, can we switch from `test_util::wait_for_atomic_usize` to an `assert!(x == num_events)`? This would be great help to spot the problem in case it comes back again.

File: tests/support/mod.rs [hunk 4]
```diff
@@ -108,21 +108,34 @@ impl SourceConfig for MockSourceConfig {
...
+                            shutdown.take();
+                        }
+                        Ok(Async::NotReady) => {}
                     }
-                    x
-                })
-                .forward(out.sink_map_err(|e| error!("Error sending in sink {}", e)))
-                .map(|_| info!("finished sending"))
+                }
+                recv.poll()
```
Comment (MOZGIII) [inline tests/support/mod.rs:129]: These changes look good! :+1:

File: src/async_read.rs [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+    S: Read,
+{
+    fn read(&mut self, buf: &mut [u8]) -> Result<usize, std::io::Error> {
+        self.reader.read(buf)
+    }
+}
+
+impl<S, F, O> AsyncRead for ReadUntil<S, F, O>
+where
+    S: AsyncRead,
```
Comment (MOZGIII) [inline src/async_read.rs:50]: I wish there was a way to ensure at the type level that `AsyncRead` is unbuffered. :frowning_face: However, even if we don't have a buffer for the type on our end (i.e. it's a socket) - the kernel might have one. We should probably assume all `S` are buffered.
This correlates to what I've already mentioned at the PR-level discussion, so let's continue the discussion on this part there.

**Comment by ktff** [comment]
> whole kernel-buffered data up until the underlying socket returns WouldBlock

That wouldn't help, there is always a window of time between receiving WouldBlock and shutting down the connection, in which OS could receive more data which we would lose.  

The only way that I see to avoid any loss is to close the connection without dropping it so we can read until the end. But `TcpStream::shutdown` is no good for the reason 

> Did some digging, and it seems like shutdown with SHUT_RD is a noop:
https://github.com/torvalds/linux/blob/f85c1598ddfe83f61d0656bd1d2025fa3b148b99/net/ipv4/tcp.c#L2317-L2335

@MOZGIII do you have some other idea?

File: src/async_read.rs (hunk 1 above)
Comment (ktff) [reply src/async_read.rs:51]: We can't since`ShutdownSignal` isn't infallible.

File: src/async_read.rs (hunk 2 above)
Comment (ktff) [reply src/async_read.rs:23]: What about `AsyncAllowReadExt` and `allow_read_until`?

File: tests/buffering.rs (hunk 3 above)
Comment (ktff) [reply tests/buffering.rs:75]: True.

**Comment by MOZGIII** [comment]
> The only way that I see to avoid any loss is to close the connection without dropping it so we can read until the end. But `TcpStream::shutdown` is no good for the reason

Right, but when socket is closed - we can't read anymore...

> @MOZGIII do you have some other idea?

In essence, we want to 1) consume the stuff that's at the receive queue for a socket, but 2) without letting the kernel accepting any new data. We could easily do (1), but not the (2).

Yeah, I'm not sure it's something we can achieve with raw TCP... So, I think what we have currently is good! :+1:

File: src/async_read.rs (hunk 2 above)
Comment (MOZGIII) [reply src/async_read.rs]: `allow_read_until` sounds good! Struct name can be simply derived from the method name: `AllowReadUntil` in this case.

I'm assuming `AsyncAllowReadExt` is the proposed new trait name. For the trait, I suggest either use `AllowReadUntilExt` or just `AsyncReadExt` (given it's mod-namespaced it's ok as is). `AsyncReadExt` works better if we plan to all other methods in it, and the more specific `AllowReadUntilExt` works if we use it as an ext for only `allow_read_until` - and we plan on adding other similar traits exts for other things.
If you like `AsyncAllowReadExt` better - I'm fine with that too, the trait name isn't really a concern for me :smile:

**Comment by ktff** [comment]
Let's wait for @bruceg before merging, maybe he has an idea on how to get those bytes in OS buffers.

**Comment by binarylogic** [comment]
Nice work @ktff, thanks for the review @MOZGIII.

File: tests/buffering.rs [hunk 6]
```diff
@@ -67,12 +67,12 @@ fn test_buffering() {
...
+    // There was a race caused by a channel in the mock source, and this
+    // check is here to ensure it's really gone.
+    test_util::wait_for_atomic_usize(source_event_counter, |x| {
```
Comment (MOZGIII) [inline tests/buffering.rs:72]: `test_util::wait_for_atomic_usize` would hide the problem if it comes back again. I meant we for us to do a simple comparison instead of cycled wait. I assume that's supposed to always pass now, right?

Comment (MOZGIII) [reply tests/buffering.rs:72]:
```rust
assert_eq!(source_event_counter.load(Ordering::Relaxed), num_events);
```

**Comment by bruceg** [comment]
> Did some digging, and it seems like `shutdown` with `SHUT_RD` is a noop:

Can we do `shutdown(socket, SHUT_RDWR)`? Vector won't be writing to the socket, and this will mark its state properly in the kernel.

**Comment by MOZGIII** [comment]
> > Did some digging, and it seems like `shutdown` with `SHUT_RD` is a noop:
> 
> Can we do `shutdown(socket, SHUT_RDWR)`? Vector won't be writing to the socket, and this will mark its state properly in the kernel.

Technically, we can do `shutdown(socket, SHUT_WR)` immediately when we obtain the socket. And we probably should. This won't help us with the issue at hand though. :frowning_face:

**Comment by ktff** [comment]
@lukesteensen Didn't know that was the convention. Do you have an idea on how common it is? I ask so to determine should we add a timer for such connections with duration shorter than the shutdown timer, something like a few seconds, or just to rely on the shutdown timer for those that don't follow it.

**Comment by MOZGIII** [comment]
> Basically, the receiver can signal to the sender that it should stop writing by closing its own write half of the socket.

This looks like it’s a protocol layer atop of TCP. I would expect the receiver closing the write end asap, rather than when it’s done reading. It’s a clever way to implement the required signalling atop of a protocol that doesn’t implement it, but I think it’s a non-standard contract. The downside is we can’t really automatically detect if that contract is respected by a particular sender. Looks like we can use it by default though, and if it works - it works, if it doesn’t - well, nothing breaks, and we just fallback to the scenario equivalent to the current situation.

**Comment by lukesteensen** [comment]
I'm not sure I'd call it an entire protocol, but I agree it is at least a simple convention on top of TCP. Depending on the socket implementation, it does give [a much more graceful closure within the TCP protocol itself](https://stackoverflow.com/a/23483487).

You are right that we can't ensure the client follows that convention, but there is no harm in trying and it degrades to exactly the same situation as before if they do not.

**Comment by lukesteensen** [comment]
> Do you have an idea on how common it is? I ask so to determine should we add a timer for such connections with duration shorter than the shutdown timer, something like a few seconds, or just to rely on the shutdown timer for those that don't follow it.

Good question, I am not entirely sure :smile: 

I would think that something on the order of 5 seconds should be long enough to wait. It's probably not wise to assume most clients will follow that convention.

**Comment by Hoverbear** [comment]
I think a shutdown timer is reasonable. :) 5 seconds is plenty generous.

**Comment by ktff** [comment]
A timeout was already added in #278. It's configurable through `toml` so I've just reused it and left the default 30sec.

Latest commit contains a test and a fix for `TcpSink`. The test checks that we aren't loosing any events in `TcpSink` -> `Socket::Tcp` topology because of a source shutdown. It showed that `TcpSink` wasn't flushing it's buffers, when we signaled it to disconnect by closing write part of the channel from the source side.

File: src/sources/socket/mod.rs [hunk 7]
```diff
@@ -347,7 +347,6 @@ mod test {
 
     #[test]
     fn tcp_shutdown_infinite_stream() {
-        crate::test_util::trace_init();
```
Comment (MOZGIII) [inline src/sources/socket/mod.rs]: Is this really intended?

Comment (ktff) [reply src/sources/socket/mod.rs]: Yes, I added it in the previous commit and forgot to remove it.

Comment (MOZGIII) [reply src/sources/socket/mod.rs]: Oh, got it.
We probably should add this to every test out there - at least that's how I understand it. The reason some tests don't have it seem to be it was added after the tests.
Not sure though.
