### PR TITLE
fix(remap): `parse_grok` should error when it fails to parse

### LINKED ISSUE #6252: Remap: parse_grok doesn't error on failure
### Vector Version

```
vector 0.12.0 (g87a2147 x86_64-unknown-linux-gnu 2021-01-26)
```

### Expected Behavior

Based on the [current docs](https://master.vector.dev/docs/reference/vrl/functions/#parse_grok), and the cue files `parse_grok` should return an error if it can't match the value with the given pattern.

### Actual Behavior

When testing in the VRL REPL I get an empty map back?
```
$ parse_grok("8", "%{NUMBER:number}")
{ "number": "8" }

$ parse_grok("foobar", "%{NUMBER:number}")
{  }
```

### PR DESCRIPTION
**Pull request by FungusHumungus**
Closes #6252 
Ref #6249 

This make `parse_grok` return an error if it doesn't parse the input string correctly.

There was also a bug in the type_def which was declaring it's return type to be an Array. I have fixed it to return Map.

Signed-off-by: Stephen Wakely <fungus.humungus@gmail.com>

### CODE REVIEW

File: lib/remap-functions/src/parse_grok.rs [hunk 1]
```diff
@@ -103,15 +103,15 @@ impl Expression for ParseGrokFn {
 
                 Ok(Value::from(result))
             }
-            None => Ok(Value::from(BTreeMap::new())),
+            None => Err("unable to parse input with grok pattern".into()),
```
Comment (pablosichert) [inline lib/remap-functions/src/parse_grok.rs:106]: I think the error message should be capitalized and end with a period according to the [logging-style](https://github.com/timberio/vector/blob/master/CONTRIBUTING.md#logging-style).

File: lib/remap-functions/src/parse_grok.rs [hunk 2]
```diff
@@ -170,7 +171,7 @@ mod test {
         let cases = vec![
             (
                 map!["message": "an ungrokkable message"],
-                Ok(Value::from(map![])),
+                Err("function call error: unable to parse input with grok pattern".into()),
```
Comment (pablosichert) [inline lib/remap-functions/src/parse_grok.rs:174]: Same here.

File: lib/remap-functions/src/parse_grok.rs [hunk 3]
```diff
@@ -181,7 +182,7 @@ mod test {
             ),
             (
                 map!["message": "2020-10-02T23:22:12.223222Z an ungrokkable message"],
-                Ok(Value::from(map![])),
+                Err("function call error: unable to parse input with grok pattern".into()),
```
Comment (pablosichert) [inline lib/remap-functions/src/parse_grok.rs:185]: And here.

File: lib/remap-functions/src/parse_grok.rs [hunk 4]
```diff
@@ -103,15 +103,15 @@ impl Expression for ParseGrokFn {
...
         }
     }
 
     fn type_def(&self, state: &state::Compiler) -> TypeDef {
         self.value
             .type_def(state)
-            .fallible_unless(value::Kind::Bytes)
-            .with_constraint(value::Kind::Array)
+            .into_fallible(true)
+            .with_constraint(value::Kind::Map)
```
Comment (pablosichert) [inline lib/remap-functions/src/parse_grok.rs:114]: I don't fully understand how the type changed from `Array` to `Map`, could you help me out here?

File: lib/remap-functions/src/parse_grok.rs [hunk 5]
```diff
@@ -103,15 +103,15 @@ impl Expression for ParseGrokFn {
 
                 Ok(Value::from(result))
```
Comment (pablosichert) [inline lib/remap-functions/src/parse_grok.rs:104]: This still seems to return a `Map`, not an `Array`.

**Review by pablosichert — CHANGES_REQUESTED** [review]

File: lib/remap-functions/src/parse_grok.rs (hunk 1 above)
Comment (FungusHumungus) [reply lib/remap-functions/src/parse_grok.rs:106]: So the standards for remap errors are generally lower case without the trailing period since the error raised here is appended to another error message. So that will be reported as: `"function call error: unable to parse input with grok pattern"`, it would look a bit out of sorts if the`U` was capitalized there.

File: lib/remap-functions/src/parse_grok.rs (hunk 4 above)
Comment (FungusHumungus) [reply lib/remap-functions/src/parse_grok.rs:114]: It didn't. It should never have been `Array` in the first place. I'm not sure what I was thinking at the time..

Until recently these types weren't really used much - I believe the only place was the condition system would check that the return was a Boolean. So the error was never spotted until I was looking over this file for this PR.

Recent changes mean that we do actually check the types much more, so if function expecting a Map as a parameter took the output from this function it would have incorrectly errored.

File: lib/remap-functions/src/parse_grok.rs (hunk 5 above)
Comment (FungusHumungus) [reply lib/remap-functions/src/parse_grok.rs:104]: > This still seems to return a `Map`, not an `Array`.

Correct. It was the type_def that was wrong.

File: lib/remap-functions/src/parse_grok.rs (hunk 1 above)
Comment (pablosichert) [reply lib/remap-functions/src/parse_grok.rs:106]: That also works, as long we are consistent with it, I guess.

File: lib/remap-functions/src/parse_grok.rs (hunk 4 above)
Comment (pablosichert) [reply lib/remap-functions/src/parse_grok.rs:114]: I see - thanks!

**Review by pablosichert — APPROVED** [review]
