### PR TITLE
fix(file source): write checkpoints before shutdown

### LINKED ISSUE #7898: Checkpoint files during shutdown
While investigating https://github.com/timberio/vector/issues/7896 @spencergilbert and I observed that the `FileServer` seems to immediately cease checkpointing once shutdown is started:

https://github.com/timberio/vector/blob/56619b87eaadf69276530df9bff40d895445c604/lib/file-source/src/file_server.rs#L138-L173

We think this may be causing the test failure we saw if the vector pod running in the test failed to write its checkpoints before it was restarted.

@lukesteensen is my understanding here right? Is there a reason we have it like this? I would have expected us to stop reading files but also flush the checkpoints one more time during shutdown.

### PR DESCRIPTION
**Pull request by lukesteensen**
Fixes #7898

### CODE REVIEW

File: lib/file-source/src/file_server.rs [hunk 1]
```diff
@@ -139,12 +138,11 @@ where
...
         let checkpointer = Arc::new(checkpointer);
         let sleep_duration = self.glob_minimum_cooldown;
-        self.handle.spawn(async move {
-            let mut done = false;
+        let checkpoint_task_handle = self.handle.spawn(async move {
             loop {
                 let sleep = sleep(sleep_duration);
                 tokio::select! {
-                    _ = &mut shutdown2 => done = true,
+                    _ = &mut shutdown2 => return checkpointer,
```
Comment (bruceg) [inline lib/file-source/src/file_server.rs:145]: `checkpointer` is an `Arc` box at this point. Is passing it in and returning it better than the surrounding code just adding another reference?

File: lib/file-source/src/file_server.rs [hunk 2]
```diff
@@ -160,10 +158,6 @@ where
                 .instrument(trace_span!("writing checkpoints file"))
```
Comment (bruceg) [inline lib/file-source/src/file_server.rs:158]: I meant to ask about the actual checkpoint write here. Why is it being spawned in a task, when the caller just `await`s on it anyways?

**Review by bruceg — COMMENTED** [review]
This looks reasonable.

**Comment by bruceg** [comment]
This will also fix #7988 once I rewrite #8224 to just make the test wait for shutdown instead of a pause.

File: lib/file-source/src/file_server.rs (hunk 2 above)
Comment (lukesteensen) [reply lib/file-source/src/file_server.rs:158]: I believe that's just to mark the thread as blocking so that we don't starve the normal runtime threads. It's likely not a big deal in this specific circumstances, but technically correct since we're spawning this as a task.

File: lib/file-source/src/file_server.rs (hunk 1 above)
Comment (lukesteensen) [reply lib/file-source/src/file_server.rs:145]: Not necessarily, but it would be nice if we enforced a single writer for the checkpoint file and this is more compatible with that design should we choose to refactor.

**Review by bruceg — APPROVED** [review]
